#!/usr/bin/env bun

import * as fs from "node:fs/promises";
import { createRequire } from "node:module";
import * as path from "node:path";

const utilsDir = path.join(import.meta.dir, "..", "src", "utils");
const helperPath = path.join(utilsDir, "mupdf-wasm-embed.ts");
const wasmCopyPath = path.join(utilsDir, "mupdf-wasm.wasm");
const mupdfJsCopyPath = path.join(utilsDir, "mupdf-embedded.js");
const mupdfWasmJsCopyPath = path.join(utilsDir, "mupdf-wasm-embedded.js");

const placeholder = `// AUTOGENERATED -- managed by scripts/embed-mupdf-wasm.ts. Do not edit by hand.

export interface EmbeddedMupdfModuleFiles {
	version: string;
	mupdfJs: string;
	mupdfWasmJs: string;
}

export function loadEmbeddedMupdfWasm(): Uint8Array | undefined {
	return undefined;
}

export function loadEmbeddedMupdfModuleFiles(): EmbeddedMupdfModuleFiles | undefined {
	return undefined;
}
`;

if (process.argv.includes("--reset")) {
	await Bun.write(helperPath, placeholder);
	for (const copy of [wasmCopyPath, mupdfJsCopyPath, mupdfWasmJsCopyPath]) {
		try {
			await fs.unlink(copy);
		} catch (err) {
			if ((err as NodeJS.ErrnoException).code !== "ENOENT") throw err;
		}
	}
	process.exit(0);
}

const require = createRequire(import.meta.url);
const mupdfDist = path.dirname(require.resolve("mupdf"));
const mupdfVersion: string = require("mupdf/package.json").version;
const sources = [
	{ from: path.join(mupdfDist, "mupdf-wasm.wasm"), to: wasmCopyPath },
	{ from: path.join(mupdfDist, "mupdf.js"), to: mupdfJsCopyPath },
	{ from: path.join(mupdfDist, "mupdf-wasm.js"), to: mupdfWasmJsCopyPath },
];
for (const { from, to } of sources) {
	const file = Bun.file(from);
	if (!(await file.exists())) {
		throw new Error(`mupdf runtime file not found at ${from}; run \`bun install\` first.`);
	}
	await Bun.write(to, file);
}

const generated = `// AUTOGENERATED -- managed by scripts/embed-mupdf-wasm.ts. Do not edit or commit.
import { readFileSync } from "node:fs";
import mupdfJsPath from "./mupdf-embedded.js" with { type: "file" };
import mupdfWasmJsPath from "./mupdf-wasm-embedded.js" with { type: "file" };
import wasmPath from "./mupdf-wasm.wasm" with { type: "file" };

export interface EmbeddedMupdfModuleFiles {
	version: string;
	mupdfJs: string;
	mupdfWasmJs: string;
}

export function loadEmbeddedMupdfWasm(): Uint8Array | undefined {
\treturn readFileSync(wasmPath);
}

export function loadEmbeddedMupdfModuleFiles(): EmbeddedMupdfModuleFiles | undefined {
\treturn { version: ${JSON.stringify(mupdfVersion)}, mupdfJs: mupdfJsPath, mupdfWasmJs: mupdfWasmJsPath };
}
`;

await Bun.write(helperPath, generated);
console.log(
	`Embedded mupdf ${mupdfVersion} runtime (wasm + js modules) into ${path.relative(process.cwd(), utilsDir)}`,
);
