#!/usr/bin/env bun

// Embeds mupdf's runtime files into the compiled single-file binary.
//
// mupdf loads its wasm by reading the `mupdf-wasm.wasm` sibling of its own
// module via `new URL(..., import.meta.url)` + `readFileSync`. A `bun --compile`
// binary has no node_modules, so that read fails (`ENOENT .../mupdf-wasm.wasm`),
// and marking mupdf `--external` instead makes `bun --compile` eagerly fail to
// resolve the package at startup (the static `import * as mupdf` lives in a lazy
// chunk but is hoisted). The wasm bytes are embedded here and handed to the WASM
// module as `$libmupdf_wasm_Module.wasmBinary` (see src/utils/markit.ts).
//
// Additionally, `mupdf/dist/mupdf.js` contains a top-level await (WASM
// instantiation), and Bun's bytecode compilation rejects any bundled module
// with a top-level await. So the binary build keeps mupdf's JS out of the
// bundle graph entirely: `mupdf.js` and `mupdf-wasm.js` are embedded as opaque
// file assets, materialized to a cache directory on first PDF use, and imported
// at runtime by path (src/markit/converters/pdf/extract.ts).
//
// `--generate` copies the files next to src/utils/mupdf-wasm-embed.ts and
// rewrites that module to import them via `with { type: "file" }`; `--reset`
// restores the checked-in placeholder and removes the copies. The npm
// `dist/cli.js` bundle never runs this — it keeps mupdf external and loads
// everything from node_modules.

import * as fs from "node:fs/promises";
import { createRequire } from "node:module";
import * as path from "node:path";

const utilsDir = path.join(import.meta.dir, "..", "src", "utils");
const helperPath = path.join(utilsDir, "mupdf-wasm-embed.ts");
const wasmCopyPath = path.join(utilsDir, "mupdf-wasm.wasm");
const mupdfJsCopyPath = path.join(utilsDir, "mupdf-embedded.js");
const mupdfWasmJsCopyPath = path.join(utilsDir, "mupdf-wasm-embedded.js");

const placeholder = `// AUTOGENERATED -- managed by scripts/embed-mupdf-wasm.ts. Do not edit by hand.
//
// Compiled single-file binaries cannot let mupdf resolve its \`mupdf-wasm.wasm\`
// sibling from the read-only bunfs, and mupdf's top-level await is incompatible
// with bytecode compilation, so the binary build (scripts/build-binary.ts and
// scripts/ci-release-build-binaries.ts) regenerates this module to embed the
// wasm bytes plus mupdf's JS modules via \`with { type: "file" }\`. Source
// checkouts, \`bun test\`, and the npm \`dist/cli.js\` bundle keep mupdf external
// and load everything from node_modules, so this placeholder returns undefined
// and the build resets back to it afterward.

/** Embedded mupdf JS module assets, materialized to a cache dir at runtime. */
export interface EmbeddedMupdfModuleFiles {
	/** mupdf package version the assets were embedded from (cache key). */
	version: string;
	/** Embedded-asset path of \`mupdf/dist/mupdf.js\`. */
	mupdfJs: string;
	/** Embedded-asset path of \`mupdf/dist/mupdf-wasm.js\`. */
	mupdfWasmJs: string;
}

export function loadEmbeddedMupdfWasm(): Uint8Array | undefined {
	return undefined;
}

export function loadEmbeddedMupdfModuleFiles(): EmbeddedMupdfModuleFiles | undefined {
	return undefined;
}
`;

if (process.argv.includes("--reset")) {
	await Bun.write(helperPath, placeholder);
	for (const copy of [wasmCopyPath, mupdfJsCopyPath, mupdfWasmJsCopyPath]) {
		try {
			await fs.unlink(copy);
		} catch (err) {
			if ((err as NodeJS.ErrnoException).code !== "ENOENT") throw err;
		}
	}
	process.exit(0);
}

const require = createRequire(import.meta.url);
const mupdfDist = path.dirname(require.resolve("mupdf"));
const mupdfVersion: string = require("mupdf/package.json").version;
const sources = [
	{ from: path.join(mupdfDist, "mupdf-wasm.wasm"), to: wasmCopyPath },
	{ from: path.join(mupdfDist, "mupdf.js"), to: mupdfJsCopyPath },
	{ from: path.join(mupdfDist, "mupdf-wasm.js"), to: mupdfWasmJsCopyPath },
];
for (const { from, to } of sources) {
	const file = Bun.file(from);
	if (!(await file.exists())) {
		throw new Error(`mupdf runtime file not found at ${from}; run \`bun install\` first.`);
	}
	await Bun.write(to, file);
}

const generated = `// AUTOGENERATED -- managed by scripts/embed-mupdf-wasm.ts. Do not edit or commit.
import { readFileSync } from "node:fs";
import mupdfJsPath from "./mupdf-embedded.js" with { type: "file" };
import mupdfWasmJsPath from "./mupdf-wasm-embedded.js" with { type: "file" };
import wasmPath from "./mupdf-wasm.wasm" with { type: "file" };

export interface EmbeddedMupdfModuleFiles {
	version: string;
	mupdfJs: string;
	mupdfWasmJs: string;
}

export function loadEmbeddedMupdfWasm(): Uint8Array | undefined {
\treturn readFileSync(wasmPath);
}

export function loadEmbeddedMupdfModuleFiles(): EmbeddedMupdfModuleFiles | undefined {
\treturn { version: ${JSON.stringify(mupdfVersion)}, mupdfJs: mupdfJsPath, mupdfWasmJs: mupdfWasmJsPath };
}
`;

await Bun.write(helperPath, generated);
console.log(
	`Embedded mupdf ${mupdfVersion} runtime (wasm + js modules) into ${path.relative(process.cwd(), utilsDir)}`,
);
