import * as fs from "node:fs/promises";
import * as path from "node:path";
import { allPromptIds, PROMPT_REGISTRIES } from "../src/prompts/all-registries";

const OUT = path.join(import.meta.dirname, "..", "src", "prompts", "ids.generated.ts");

export function renderPromptIdModule(ids: readonly string[], registries: number): string {
	const rows = [...ids].sort().map(id => `\t"${id}",`);
	return `/**
 * Every prompt id in this build. GENERATED by \`bun run gen:prompt-ids\` — never edited.
 *
 * The refusal that catches an unknown \`VEYYON_EVAL_PROMPTS\` id needs the id space and
 * no prompt text. Reading it from the registries themselves put every prompt module on
 * the launch path, so the ids are written down here instead and
 * \`a-prompt-id-list-is-the-build-it-was-generated-from.test.ts\` keeps this file equal to
 * them.
 */

export const PROMPT_REGISTRY_COUNT = ${registries};

export const PROMPT_IDS: readonly string[] = [
${rows.join("\n")}
];
`;
}

if (import.meta.main) {
	const rendered = renderPromptIdModule(allPromptIds(), PROMPT_REGISTRIES.length);
	const existing = await fs.readFile(OUT, "utf8").catch(() => "");
	if (existing === rendered) {
		console.log(`${path.relative(process.cwd(), OUT)} is up to date`);
	} else {
		await fs.writeFile(OUT, rendered);
		console.log(`wrote ${path.relative(process.cwd(), OUT)} (${allPromptIds().length} ids)`);
	}
}
