#!/usr/bin/env bun
import * as fs from "node:fs/promises";
import * as os from "node:os";
import * as path from "node:path";

const PLAYWRIGHT_TAG = "v1.61.0";
const RAW_BASE = `https://raw.githubusercontent.com/microsoft/playwright/${PLAYWRIGHT_TAG}/packages`;

const OUTPUT = path.join(import.meta.dir, "..", "src", "tools", "browser", "aria", "aria-snapshot.bundle.txt");

const VENDOR_FILES: Array<[string, string]> = [
	["injected/src/ariaSnapshot.ts", "injected/ariaSnapshot.ts"],
	["injected/src/roleUtils.ts", "injected/roleUtils.ts"],
	["injected/src/domUtils.ts", "injected/domUtils.ts"],
	["isomorphic/ariaSnapshot.ts", "isomorphic/ariaSnapshot.ts"],
	["isomorphic/stringUtils.ts", "isomorphic/stringUtils.ts"],
	["isomorphic/cssTokenizer.ts", "isomorphic/cssTokenizer.ts"],
	["isomorphic/yaml.ts", "isomorphic/yaml.ts"],
];

const ENTRY_SOURCE = `
import { generateAriaTree, renderAriaTree } from "./injected/ariaSnapshot";

export interface AriaSnapshotRequest {
	depth?: number;
	boxes?: boolean;
}

function walkElements(fn: (el: Element) => void): void {
	const walk = (root: { querySelectorAll(s: string): ArrayLike<Element> }): void => {
		for (const el of Array.from(root.querySelectorAll("*"))) {
			fn(el);
			const shadow = (el as Element & { shadowRoot?: { querySelectorAll(s: string): ArrayLike<Element> } | null }).shadowRoot;
			if (shadow) walk(shadow);
		}
	};
	walk(document as unknown as { querySelectorAll(s: string): ArrayLike<Element> });
}
type RefElement = Element & { _ariaRef?: { role: string; name: string; ref: string } };

export function ariaSnapshot(root: Element | null, request: AriaSnapshotRequest = {}): string {
	walkElements(el => {
		if ((el as RefElement)._ariaRef) delete (el as RefElement)._ariaRef;
	});
	const target = root ?? document.body ?? document.documentElement;
	const options = { mode: "ai", depth: request.depth, boxes: request.boxes } as const;
	const tree = generateAriaTree(target, options);
	return renderAriaTree(tree, options).text;
}

export function resolveAriaRef(ref: string): Element | null {
	let found: Element | null = null;
	walkElements(el => {
		if (!found && (el as RefElement)._ariaRef?.ref === ref) found = el;
	});
	return found;
}
`;

async function main(): Promise<void> {
	const tmp = await fs.mkdtemp(path.join(os.tmpdir(), "veyyon-aria-"));
	try {
		for (const [src, dst] of VENDOR_FILES) {
			const url = `${RAW_BASE}/${src}`;
			const res = await fetch(url);
			if (!res.ok) throw new Error(`Failed to fetch ${url}: ${res.status}`);
			await Bun.write(path.join(tmp, dst), await res.text());
		}
		const entry = path.join(tmp, "entry.ts");
		await Bun.write(entry, ENTRY_SOURCE);

		const aliasPlugin: Bun.BunPlugin = {
			name: "aria-vendor-alias",
			setup(build) {
				build.onResolve({ filter: /^@isomorphic\// }, args => ({
					path: path.join(tmp, "isomorphic", `${args.path.slice("@isomorphic/".length)}.ts`),
				}));
				build.onResolve({ filter: /^yaml$/ }, () => ({ path: "yaml", namespace: "aria-yaml-stub" }));
				build.onLoad({ filter: /.*/, namespace: "aria-yaml-stub" }, () => ({
					contents: "export {};",
					loader: "ts",
				}));
			},
		};

		const result = await Bun.build({
			entrypoints: [entry],
			target: "browser",
			format: "cjs",
			minify: true,
			plugins: [aliasPlugin],
		});
		if (!result.success) {
			for (const log of result.logs) console.error(log);
			throw new Error("aria snapshot bundle failed");
		}
		const code = await result.outputs[0].text();
		const header = `// @generated by scripts/generate-aria-snapshot.ts from Playwright ${PLAYWRIGHT_TAG}\n// Bundled from Playwright's injected ARIA-snapshot sources (Apache-2.0, (c) Microsoft).\n// Do not edit by hand. Regenerate with: bun scripts/generate-aria-snapshot.ts\n`;
		await Bun.write(OUTPUT, header + code);
		console.log(`bundled ${path.relative(process.cwd(), OUTPUT)} (${code.length}b)`);
	} finally {
		await fs.rm(tmp, { recursive: true, force: true });
	}
}

await main();
