// Tests for the site navigation owner (website/tools/nav.mjs) and for the built
// pages that consume it.
//
// The nav used to be nine hand-copied blocks across six HTML files. Nothing
// compared the copies, so 404.html quietly lost the Blog link and every generated
// blog page failed to mark Blog as the current page. These tests are the reason
// that cannot happen again: the first group pins the renderer, the second reads
// the pages on disk and fails if any of them drifts from the one link list.

import { readFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { describe, expect, it } from "bun:test";
// @ts-expect-error — plain .mjs module, no types; imported for its exports.
import { CTA, LINKS, renderNav } from "./nav.mjs";

const WEBSITE = join(dirname(import.meta.dir), ".");
type Link = { label: string; href: string; page?: string; absolute?: boolean };
const links: Link[] = LINKS;

/** Link labels and hrefs found inside a page's nav region. */
function navRegions(html: string): { links: { href: string; label: string; current: boolean }[]; raw: string }[] {
	const regions = [...html.matchAll(/<!--NAV:START-->([\s\S]*?)<!--NAV:END-->/g)];
	return regions.map(([, raw]) => ({
		raw,
		links: [...raw.matchAll(/<a href="([^"]+)"([^>]*)>([^<]+)<\/a>/g)].map(([, href, attrs, label]) => ({
			href,
			label,
			current: attrs.includes('aria-current="page"'),
		})),
	}));
}

describe("renderNav", () => {
	/** Every destination in the one list has to reach every nav. A link added to
	 *  LINKS and missing from a rendered nav is the exact drift this file exists
	 *  to stop. */
	it("renders every link in order, with the CTA last in header navs", () => {
		const html = renderNav({ prefix: "./", current: "install" });
		const labels = [...html.matchAll(/>([^<]+)<\/a>/g)].map(m => m[1]);
		expect(labels).toEqual([...links.map(l => l.label), CTA.label]);
	});

	/** The footer carries the same destinations but not the Get-started button;
	 *  two CTAs stacked on one page reads like a mistake. */
	it("omits the CTA when asked (the footer nav)", () => {
		const html = renderNav({ prefix: "./", cta: false });
		expect(html).not.toContain(CTA.label);
		expect(html).toContain(">Docs</a>");
	});

	/** Site-relative links take the page's prefix; an outbound link must not, or
	 *  the GitHub link would render as ./https://github.com/... */
	it("prefixes site links and leaves absolute links alone", () => {
		const root = renderNav({ prefix: "./" });
		const blog = renderNav({ prefix: "../" });
		expect(root).toContain('href="./models.html"');
		expect(blog).toContain('href="../models.html"');
		expect(root).toContain('href="https://github.com/santhreal/veyyon"');
		expect(blog).toContain('href="https://github.com/santhreal/veyyon"');
	});

	/** aria-current is what marks the page you are on, for a screen reader and for
	 *  the nav's own styling. It has to land on exactly one link, and only when the
	 *  page asks for it. */
	it("marks exactly one link aria-current, and none when no page is given", () => {
		const marked = renderNav({ prefix: "./", current: "changelog" });
		expect([...marked.matchAll(/aria-current="page"/g)]).toHaveLength(1);
		expect(marked).toContain('<a href="./changelog.html" aria-current="page">Changelog</a>');
		expect(renderNav({ prefix: "./" })).not.toContain("aria-current");
	});

	/** An unknown page id marking nothing is correct (the homepage passes none),
	 *  but it must never mark the wrong link instead. */
	it("marks nothing for a page id that is not in the list", () => {
		expect(renderNav({ prefix: "./", current: "not-a-page" })).not.toContain("aria-current");
	});
});

describe("built pages", () => {
	const PAGES = [
		{ file: "index.html", prefix: "./", current: undefined },
		{ file: "features.html", prefix: "./", current: "features" },
		{ file: "models.html", prefix: "./", current: "models" },
		{ file: "install.html", prefix: "./", current: "install" },
		{ file: "changelog.html", prefix: "./", current: "changelog" },
		{ file: "404.html", prefix: "./", current: undefined },
		{ file: "blog/index.html", prefix: "../", current: "blog" },
	];

	/** Three regions per page: desktop header, mobile disclosure, footer. A page
	 *  that lost a marker would silently stop being regenerated by build.mjs, which
	 *  is how a copy drifts in the first place. */
	it.each(PAGES)("$file carries three nav regions with the full link set", ({ file, prefix }) => {
		const html = readFileSync(join(WEBSITE, file), "utf8");
		const regions = navRegions(html);
		expect(regions).toHaveLength(3);
		for (const region of regions) {
			const hrefs = region.links.map(l => l.href);
			for (const link of links) {
				expect(hrefs).toContain(link.absolute ? link.href : `${prefix}${link.href}`);
			}
		}
		// Header navs end on the CTA, the footer nav does not.
		expect(regions[0]!.links.at(-1)!.label).toBe(CTA.label);
		expect(regions[1]!.links.at(-1)!.label).toBe(CTA.label);
		expect(regions[2]!.links.at(-1)!.label).toBe("GitHub");
	});

	/** 404.html is the page that actually lost its Blog link. Naming it explicitly
	 *  keeps the specific regression, not just the general rule. */
	it("404.html links to the blog (it silently lost that link once)", () => {
		const html = readFileSync(join(WEBSITE, "404.html"), "utf8");
		for (const region of navRegions(html)) {
			expect(region.links.map(l => l.href)).toContain("./blog/");
		}
	});

	/** Every page must announce itself. Blog pages are generated by gen-blog.mjs,
	 *  which kept its own nav copy and marked nothing at all. */
	it.each(PAGES.filter(p => p.current))("$file marks its own nav link current", ({ file, current, prefix }) => {
		const html = readFileSync(join(WEBSITE, file), "utf8");
		const expected = `${prefix}${links.find(l => l.page === current)!.href}`;
		for (const region of navRegions(html)) {
			const marked = region.links.filter(l => l.current);
			expect(marked).toHaveLength(1);
			expect(marked[0]!.href).toBe(expected);
		}
	});

	/** A rendered post is a reader's entry point from search, so it needs the same
	 *  chrome as the index: three regions, Blog marked. */
	it("a rendered post carries the same nav as the blog index", () => {
		const html = readFileSync(join(WEBSITE, "blog/argot.html"), "utf8");
		const regions = navRegions(html);
		expect(regions).toHaveLength(3);
		for (const region of regions) {
			expect(region.links.filter(l => l.current).map(l => l.href)).toEqual(["../blog/"]);
		}
	});
});

describe("page head contracts", () => {
	const CANONICAL: Record<string, string> = {
		"index.html": "https://veyyon.dev/",
		"features.html": "https://veyyon.dev/features.html",
		"models.html": "https://veyyon.dev/models.html",
		"install.html": "https://veyyon.dev/install.html",
		"changelog.html": "https://veyyon.dev/changelog.html",
		"blog/index.html": "https://veyyon.dev/blog/",
	};

	/** Cloudflare serves /install and /install.html for the same page, so both are
	 *  crawlable and one of them has to be declared the real address. */
	it.each(Object.entries(CANONICAL))("%s declares its canonical URL", (file, url) => {
		const html = readFileSync(join(WEBSITE, file), "utf8");
		expect(html).toContain(`<link rel="canonical" href="${url}" />`);
	});

	/** An indexed error page is a search result that wastes a reader's click. */
	it("404.html is noindex and declares no canonical", () => {
		const html = readFileSync(join(WEBSITE, "404.html"), "utf8");
		expect(html).toContain('<meta name="robots" content="noindex" />');
		expect(html).not.toContain('rel="canonical"');
	});

	/** The two fonts the first screen actually uses (the mono display face for the
	 *  h1, Inter for the body) are preloaded so the headline does not swap after
	 *  paint. crossorigin is mandatory on font preloads even same-origin: without
	 *  it the browser fetches the file twice. */
	it.each(Object.keys(CANONICAL))("%s preloads the two above-the-fold fonts with crossorigin", file => {
		const html = readFileSync(join(WEBSITE, file), "utf8");
		const preloads = [...html.matchAll(/<link rel="preload" href="([^"]+)"([^>]*)>/g)];
		expect(preloads.map(m => m[1]!.replace(/^\.\.?\//, ""))).toEqual([
			"fonts/JetBrainsMono-Bold.woff2",
			"fonts/Inter-Regular.woff2",
		]);
		for (const [, , attrs] of preloads) {
			expect(attrs).toContain('as="font"');
			expect(attrs).toContain('type="font/woff2"');
			expect(attrs).toContain("crossorigin");
		}
	});

	/** The hero capture is a 1.7MB gif. Without intrinsic dimensions the browser
	 *  cannot reserve its box, and everything below it jumps when the gif lands. */
	it("the hero capture declares intrinsic dimensions so the page cannot shift", () => {
		const html = readFileSync(join(WEBSITE, "index.html"), "utf8");
		const img = /<img class="capture"[^>]*>/.exec(html)?.[0] ?? "";
		expect(img).toContain('width="1400"');
		expect(img).toContain('height="800"');
		expect(img).toContain('decoding="async"');
		expect(img).toMatch(/alt="[^"]{20,}"/);
	});
});
