/**
 * The two shapes `native/embedded-addon.js` can take, and the argv flag that chooses between them.
 *
 * Extracted from `embed-native.ts` so the choice is callable. The script writes to a fixed path in
 * the checkout and needs a built `.node` beside it, so a test cannot run it without either poisoning
 * the tree or skipping on a machine that has not built the addon. The decision it makes is pure, and
 * a pure function is something a test can exercise directly.
 *
 * Why the decision matters is in the header of `a-source-tree-never-claims-to-be-compiled.test.ts`:
 * a populated module makes an ordinary source checkout claim to be a compiled binary and stage
 * 290 MB into `$HOME/.veyyon/natives/` on every CLI run.
 */

/** One addon variant as the metadata module lists it. */
export interface EmbeddedAddonEntry {
	variant: "modern" | "baseline" | "default";
	filename: string;
	size: number;
}

/** Everything the populated module needs to describe the archive it points at. */
export interface EmbeddedMetadataInput {
	platformTag: string;
	version: string;
	archiveFilename: string;
	files: EmbeddedAddonEntry[];
}

const TYPEDEFS = `/** @typedef {"modern" | "baseline" | "default"} EmbeddedAddonVariant */

/**
 * @typedef {Object} EmbeddedAddonFile
 * @property {EmbeddedAddonVariant} variant
 * @property {string} filename
 * @property {number} size
 * @property {string=} filePath
 */

/**
 * @typedef {Object} EmbeddedAddonArchive
 * @property {"tar.gz"} format
 * @property {string} filename
 * @property {string} filePath
 */

/**
 * @typedef {Object} EmbeddedAddon
 * @property {string} platformTag
 * @property {string} version
 * @property {EmbeddedAddonFile[]} files
 * @property {EmbeddedAddonArchive=} archive
 */`;

/** What a source checkout holds: the loader reads `null` and knows it is not a compiled binary. */
export const STUB_METADATA_MODULE = `
// AUTOGENERATED FILE -- DO NOT EDIT DIRECTLY
// See scripts/embed-native.ts

${TYPEDEFS}

/** @type {EmbeddedAddon|null} */
export const embeddedAddon = null;
`;

/** What only the release build writes, immediately before `bun build --compile`. */
export function populatedMetadataModule(input: EmbeddedMetadataInput): string {
	const files = input.files
		.map(
			addon =>
				`\t\t{ variant: ${JSON.stringify(addon.variant)}, filename: ${JSON.stringify(addon.filename)}, size: ${addon.size} },`,
		)
		.join("\n");
	return `
// AUTOGENERATED FILE -- DO NOT EDIT DIRECTLY
// See scripts/embed-native.ts

${TYPEDEFS}

import archivePath from ${JSON.stringify(`../native/${input.archiveFilename}`)} with { type: "file" };

export const embeddedAddon = {
\tplatformTag: ${JSON.stringify(input.platformTag)},
\tversion: ${JSON.stringify(input.version)},
\tarchive: {
\t\tformat: "tar.gz",
\t\tfilename: ${JSON.stringify(input.archiveFilename)},
\t\tfilePath: archivePath,
\t},
\tfiles: [
${files}
\t],
};
`;
}

/**
 * Which of the two a run writes.
 *
 * A rebuild passes `--stub-metadata` and keeps the stub; the archive it also writes is NOT
 * conditional on this, because a compiled binary loads what the archive holds and the two artifacts
 * must not drift.
 */
export function metadataModuleFor(argv: readonly string[], input: EmbeddedMetadataInput): string {
	return argv.includes("--stub-metadata") ? STUB_METADATA_MODULE : populatedMetadataModule(input);
}
