//! Embeds veyyon's bundled theme files.
//!
//! The themes are read out of the coding-agent package rather than copied here.
//! There is one set of theme files in this repository and both front ends load
//! it, so a theme added, renamed or recoloured for the terminal is the same
//! change for the GUI, with no second copy to fall out of step.
//!
//! The generated table is `BUNDLED: &[(&str, &str)]` — theme name, then the
//! file's bytes via `include_str!`, so the JSON is parsed at run time by the
//! same code that parses a user's theme and gets the same errors.

use std::{
	env, fs,
	path::{Path, PathBuf},
};

/// Where the bulk of the theme files live, relative to this crate.
const THEMES: &str = "../../../packages/coding-agent/src/modes/theme/defaults";

/// The two named defaults, which sit one directory above the rest.
///
/// Named rather than globbed: their directory also holds `theme-schema.json`,
/// which is a JSON Schema and not a theme, and a glob there would embed it as
/// one.
const NAMED_DEFAULTS: [&str; 2] = ["dark", "light"];

fn main() {
	let crate_dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR"));
	let themes = crate_dir.join(THEMES);

	let Ok(canonical) = themes.canonicalize() else {
		panic!(
			"bundled themes not found at {}\nThis crate embeds the theme files from the coding-agent \
			 package rather than keeping a copy. If that directory moved, update THEMES in \
			 {}/build.rs.",
			themes.display(),
			crate_dir.display()
		);
	};

	let mut entries: Vec<(String, PathBuf)> = fs::read_dir(&canonical)
		.unwrap_or_else(|error| panic!("reading {}: {error}", canonical.display()))
		.map(|entry| entry.expect("directory entry").path())
		.filter(|path| {
			path
				.extension()
				.is_some_and(|extension| extension == "json")
		})
		.map(|path| {
			let name = path
				.file_stem()
				.expect("json file has a stem")
				.to_str()
				.unwrap_or_else(|| panic!("theme file name is not utf-8: {}", path.display()))
				.to_owned();
			(name, path)
		})
		.collect();

	let theme_dir = canonical.parent().unwrap_or_else(|| {
		panic!(
			"{} has no parent directory, so the named defaults cannot be found",
			canonical.display()
		)
	});
	for name in NAMED_DEFAULTS {
		let path = theme_dir.join(format!("{name}.json"));
		assert!(
			path.is_file(),
			"named default theme `{name}` not found at {}\nIf it was renamed or moved, update \
			 NAMED_DEFAULTS in build.rs.",
			path.display()
		);
		entries.push((name.to_owned(), path));
	}

	assert!(
		!entries.is_empty(),
		"no theme files under {} — the directory exists but is empty",
		canonical.display()
	);

	// Sorted so the generated file is byte-identical between builds.
	entries.sort_by(|left, right| left.0.cmp(&right.0));

	let mut generated = String::from(
		"// Generated by build.rs. Do not edit.\n/// Every bundled theme: its name, and the bytes \
		 of its file.\npub const BUNDLED: &[(&str, &str)] = &[\n",
	);
	for (name, path) in &entries {
		generated.push_str(&format!(
			"\t({:?}, include_str!({:?})),\n",
			name,
			path.to_str().expect("theme path is utf-8")
		));
	}
	generated.push_str("];\n");

	let out = PathBuf::from(env::var("OUT_DIR").expect("OUT_DIR")).join("bundled.rs");
	fs::write(&out, generated).unwrap_or_else(|error| panic!("writing {}: {error}", out.display()));

	// A theme added or removed changes the directory; a theme edited changes a
	// file. Both have to re-run this script, so both are declared.
	println!("cargo::rerun-if-changed={}", rerun_path(&canonical));
	for (_, path) in &entries {
		println!("cargo::rerun-if-changed={}", rerun_path(path));
	}
}

fn rerun_path(path: &Path) -> &str {
	path.to_str().expect("path is utf-8")
}
