//! Behavioral tests for the loopback provider engine.

use std::{net::SocketAddr, time::Duration};

use bytes::Bytes;
use tokio::{
	io::{AsyncReadExt, AsyncWriteExt},
	net::TcpStream,
	time::timeout,
};

use crate::vmock::{
	engine::Engine,
	fault::FaultKind,
	guard::NetworkDenyGuard,
	script::{ResponseScript, WireChunk},
};

const TEST_TIMEOUT: Duration = Duration::from_secs(5);

/// WHY: A streaming provider reassembler must survive extreme transport
/// packetization without dropping or corrupting bytes. This test proves that
/// delivering an SSE response at 1 byte per TCP write arrives byte-for-byte
/// identical to the script.
///
/// What it does not catch: Transport-layer bit flips or TLS record corruption.
#[tokio::test]
async fn an_sse_body_delivered_at_1_byte_per_write_arrives_byte_identical_to_script() {
	timeout(TEST_TIMEOUT, async {
		let engine = Engine::bind().await.expect("bind loopback engine");
		let raw_payload =
			b"event: message\ndata: {\"text\":\"hello world\",\"idx\":1}\n\nevent: done\ndata: [DONE]\n\n";

		// Chunk size 1 byte
		let script = ResponseScript::sse_stream(raw_payload, 1);
		assert_eq!(script.chunks.len(), raw_payload.len());

		engine.route("/v1/chat", script);

		let mut stream = TcpStream::connect(engine.addr())
			.await
			.expect("connect to engine");
		let req =
			format!("GET /v1/chat HTTP/1.1\r\nHost: {}\r\nConnection: close\r\n\r\n", engine.addr());
		stream
			.write_all(req.as_bytes())
			.await
			.expect("write request");

		let mut resp_bytes = Vec::new();
		stream
			.read_to_end(&mut resp_bytes)
			.await
			.expect("read response");

		let resp_str = String::from_utf8_lossy(&resp_bytes);
		assert!(resp_str.starts_with("HTTP/1.1 200 OK\r\n"));
		assert!(
			resp_str
				.to_ascii_lowercase()
				.contains("content-type: text/event-stream")
		);

		// Extract body after \r\n\r\n
		let body_start = resp_bytes
			.windows(4)
			.position(|w| w == b"\r\n\r\n")
			.expect("found header delimiter")
			+ 4;
		let received_body = &resp_bytes[body_start..];
		assert_eq!(received_body, raw_payload, "1-byte writes must arrive byte-identical");
	})
	.await
	.expect("test must terminate within bounded deadline");
}

/// WHY: Multi-byte UTF-8 code points (e.g. emojis or CJK characters) may be
/// split across TCP packet boundaries. This test proves that the engine can
/// split a multi-byte UTF-8 sequence across chunk boundaries and that the
/// receiver can reconstruct the valid UTF-8 string.
///
/// What it does not catch: Invalid unicode scalar values generated by model
/// bugs.
#[tokio::test]
async fn an_event_split_mid_utf8_sequence_reassembles_correctly() {
	timeout(TEST_TIMEOUT, async {
		let engine = Engine::bind().await.expect("bind loopback engine");
		// "🦀" is 4 bytes: [0xF0, 0x9F, 0xA6, 0x80]
		let crab = "🦀";
		assert_eq!(crab.len(), 4);

		let mut script = ResponseScript::sse();
		// First chunk: "data: {\"emoji\": \"" + first 2 bytes of crab
		let mut chunk1 = Vec::from(b"data: {\"emoji\": \"".as_slice());
		chunk1.extend_from_slice(&crab.as_bytes()[..2]);
		script = script.chunk(Bytes::from(chunk1));

		// Second chunk: last 2 bytes of crab + "\"}\n\n"
		let mut chunk2 = Vec::from(&crab.as_bytes()[2..]);
		chunk2.extend_from_slice(b"\"}\n\n");
		script = script.chunk(Bytes::from(chunk2));

		engine.route("/v1/utf8", script);

		let mut stream = TcpStream::connect(engine.addr())
			.await
			.expect("connect to engine");
		let req =
			format!("GET /v1/utf8 HTTP/1.1\r\nHost: {}\r\nConnection: close\r\n\r\n", engine.addr());
		stream
			.write_all(req.as_bytes())
			.await
			.expect("write request");

		let mut resp_bytes = Vec::new();
		stream
			.read_to_end(&mut resp_bytes)
			.await
			.expect("read response");

		let body_start = resp_bytes
			.windows(4)
			.position(|w| w == b"\r\n\r\n")
			.expect("found header delimiter")
			+ 4;
		let received_body = &resp_bytes[body_start..];
		let body_text =
			std::str::from_utf8(received_body).expect("split UTF-8 must reassemble into valid UTF-8");
		assert_eq!(body_text, "data: {\"emoji\": \"🦀\"}\n\n");
	})
	.await
	.expect("test must terminate within bounded deadline");
}

/// WHY: HTTP/1.1 connection reuse (Keep-Alive) must process multiple sequential
/// requests on a single TCP connection without state leaking between requests.
///
/// What it does not catch: HTTP/2 multiplexed streams over one connection.
#[tokio::test]
async fn keep_alive_serves_two_requests_on_one_connection() {
	timeout(TEST_TIMEOUT, async {
		let engine = Engine::bind().await.expect("bind loopback engine");
		engine
			.route("/req1", ResponseScript::ok().raw_body(Bytes::from_static(b"{\"response\": 1}")));
		engine
			.route("/req2", ResponseScript::ok().raw_body(Bytes::from_static(b"{\"response\": 2}")));

		let mut stream = TcpStream::connect(engine.addr())
			.await
			.expect("connect to engine");

		// First request with keep-alive
		let req1 =
			format!("GET /req1 HTTP/1.1\r\nHost: {}\r\nConnection: keep-alive\r\n\r\n", engine.addr());
		stream.write_all(req1.as_bytes()).await.expect("write req1");

		// Read response 1 headers + body
		let mut buf = [0u8; 1024];
		let n1 = stream.read(&mut buf).await.expect("read resp1");
		let resp1 = String::from_utf8_lossy(&buf[..n1]);
		assert!(resp1.contains("HTTP/1.1 200 OK"));
		assert!(resp1.contains("{\"response\": 1}"));

		// Second request on the SAME connection
		let req2 =
			format!("GET /req2 HTTP/1.1\r\nHost: {}\r\nConnection: close\r\n\r\n", engine.addr());
		stream.write_all(req2.as_bytes()).await.expect("write req2");

		let mut remaining = Vec::new();
		stream
			.read_to_end(&mut remaining)
			.await
			.expect("read resp2 to end");
		let resp2 = String::from_utf8_lossy(&remaining);
		assert!(resp2.contains("HTTP/1.1 200 OK"));
		assert!(resp2.contains("{\"response\": 2}"));

		assert_eq!(engine.request_count(), 2);
	})
	.await
	.expect("test must terminate within bounded deadline");
}

/// WHY: A malformed HTTP request line or header must be cleanly answered with
/// HTTP 400 Bad Request and connection closed, rather than hanging or
/// panicking.
///
/// What it does not catch: Semantic validation of JSON bodies.
#[tokio::test]
async fn a_malformed_request_is_answered_400_bad_request() {
	timeout(TEST_TIMEOUT, async {
		let engine = Engine::bind().await.expect("bind loopback engine");

		let mut stream = TcpStream::connect(engine.addr())
			.await
			.expect("connect to engine");
		// Completely invalid HTTP request line (missing path and version)
		stream
			.write_all(b"NOT_A_VALID_HTTP_REQUEST\r\n\r\n")
			.await
			.expect("write garbage");

		let mut resp_bytes = Vec::new();
		stream
			.read_to_end(&mut resp_bytes)
			.await
			.expect("read response");

		let resp_str = String::from_utf8_lossy(&resp_bytes);
		assert!(
			resp_str.starts_with("HTTP/1.1 400 Bad Request\r\n"),
			"malformed request must be answered with 400 Bad Request"
		);
		assert!(resp_str.contains("Connection: close"));
	})
	.await
	.expect("test must terminate within bounded deadline");
}

/// WHY: Upstream error statuses (401, 429, 500, 503) must arrive with exact
/// status codes, payload structures, and headers like `Retry-After` on 429.
///
/// What it does not catch: Downstream client backoff algorithm correctness.
#[tokio::test]
async fn each_injected_status_arrives_with_its_headers_including_retry_after_on_429() {
	timeout(TEST_TIMEOUT, async {
		let engine = Engine::bind().await.expect("bind loopback engine");

		let test_cases = [
			(FaultKind::Http401, 401, "Unauthorized", false),
			(FaultKind::Http429, 429, "Too Many Requests", true),
			(FaultKind::Http500, 500, "Internal Server Error", false),
			(FaultKind::Http503, 503, "Service Unavailable", false),
		];

		for (fault, expected_status, expected_phrase, expect_retry_after) in test_cases {
			let path = format!("/fault-{}", fault.as_str());
			engine.route(&path, ResponseScript::from_fault(fault));

			let mut stream = TcpStream::connect(engine.addr()).await.expect("connect");
			let req =
				format!("GET {path} HTTP/1.1\r\nHost: {}\r\nConnection: close\r\n\r\n", engine.addr());
			stream
				.write_all(req.as_bytes())
				.await
				.expect("write request");

			let mut resp_bytes = Vec::new();
			stream
				.read_to_end(&mut resp_bytes)
				.await
				.expect("read response");
			let resp_str = String::from_utf8_lossy(&resp_bytes);

			let expected_status_line = format!("HTTP/1.1 {expected_status} {expected_phrase}\r\n");
			assert!(
				resp_str.starts_with(&expected_status_line),
				"Expected status line '{expected_status_line}', got '{}'",
				resp_str.lines().next().unwrap_or("")
			);

			if expect_retry_after {
				assert!(
					resp_str.to_ascii_lowercase().contains("retry-after: 5"),
					"HTTP 429 must include Retry-After header: got {resp_str}"
				);
			}
		}
	})
	.await
	.expect("test must terminate within bounded deadline");
}

/// WHY: Mid-stream socket disconnection (`ECONNRESET`-like abrupt drop) must
/// appear as an unexpected truncation / disconnection, never as a clean EOF.
///
/// What it does not catch: Kernel-level TCP RST packet generation vs FIN.
#[tokio::test]
async fn a_mid_stream_hard_close_is_observed_as_a_truncated_body_rather_than_clean_eof() {
	timeout(TEST_TIMEOUT, async {
		let engine = Engine::bind().await.expect("bind loopback engine");
		engine.route("/drop", ResponseScript::from_fault(FaultKind::MidStreamDrop));

		let mut stream = TcpStream::connect(engine.addr()).await.expect("connect");
		let req =
			format!("GET /drop HTTP/1.1\r\nHost: {}\r\nConnection: close\r\n\r\n", engine.addr());
		stream.write_all(req.as_bytes()).await.expect("write req");

		let mut resp_bytes = Vec::new();
		stream
			.read_to_end(&mut resp_bytes)
			.await
			.expect("read dropped stream");

		let resp_str = String::from_utf8_lossy(&resp_bytes);
		assert!(resp_str.contains("HTTP/1.1 200 OK"));
		// Verify that the body contains the partial start, but was truncated before
		// completion
		assert!(resp_str.contains("partial token payload"));
		assert!(!resp_str.contains("[DONE]"), "Hard-closed stream must not contain clean completion");
		assert!(
			!resp_str.ends_with("\n\n"),
			"Hard-closed stream must end abruptly without final event delimiter"
		);
	})
	.await
	.expect("test must terminate within bounded deadline");
}

/// WHY: When a provider hangs indefinitely (idle stall), the client must
/// terminate on its own bound / timeout rather than hanging the test process.
///
/// What it does not catch: OS socket keepalive timer tuning.
#[tokio::test]
async fn an_idle_stall_terminates_on_the_clients_own_bound_rather_than_hanging() {
	let engine = Engine::bind().await.expect("bind loopback engine");
	engine.route("/stall", ResponseScript::from_fault(FaultKind::IdleStall));

	let client_bound = Duration::from_millis(150);

	// Assert client timeout triggers
	let result = timeout(client_bound, async {
		let mut stream = TcpStream::connect(engine.addr()).await.expect("connect");
		let req =
			format!("GET /stall HTTP/1.1\r\nHost: {}\r\nConnection: close\r\n\r\n", engine.addr());
		stream.write_all(req.as_bytes()).await.expect("write req");

		let mut buf = [0u8; 512];
		// This read will wait indefinitely because the server stalls after headers
		loop {
			let n = stream.read(&mut buf).await.expect("read stall");
			if n == 0 {
				break;
			}
		}
	})
	.await;

	assert!(result.is_err(), "Client reading an idle stall must reach its timeout bound");
}

/// WHY: A network deny guard must prevent requests to unintended non-loopback
/// endpoints and explicitly name the disallowed destination in the failure
/// report.
///
/// What it does not catch: Out-of-band raw syscalls not checked against the
/// guard.
#[test]
fn a_deny_guard_names_a_non_loopback_destination() {
	let allowed_addr: SocketAddr = "127.0.0.1:8080".parse().expect("parse socket addr");
	let guard = NetworkDenyGuard::new(allowed_addr);

	// 1. Allowed loopback address passes
	assert!(guard.check_addr(allowed_addr).is_ok());
	assert!(
		guard
			.check_destination("http://127.0.0.1:8080/v1/chat")
			.is_ok()
	);
	assert!(guard.check_destination("http://localhost:8080").is_ok());

	// 2. Non-loopback IP fails and names destination
	let non_loopback_addr: SocketAddr = "192.168.1.100:8080".parse().unwrap();
	let err1 = guard
		.check_addr(non_loopback_addr)
		.expect_err("must deny non-loopback IP");
	assert_eq!(err1.destination, "192.168.1.100:8080");
	assert!(err1.to_string().contains("192.168.1.100:8080"));

	// 3. External domain URL fails and names destination
	let err2 = guard
		.check_destination("https://api.openai.com/v1/chat/completions")
		.expect_err("must deny external domain");
	assert_eq!(err2.destination, "https://api.openai.com/v1/chat/completions");
	assert!(err2.to_string().contains("api.openai.com"));

	// 4. Guard reports recorded violations
	assert_eq!(guard.violations().len(), 2);
	assert!(guard.assert_no_violations().is_err());
}

/// WHY: Variant space must be derived at runtime from `FaultKind::ALL` and
/// fail by default if a new variant is added without being handled.
///
/// What it does not catch: Semantic bugs in downstream consumer event decoders.
#[test]
fn sweep_all_fault_kinds_from_source_fails_by_default_on_new_member() {
	let all_faults = FaultKind::all();
	assert_eq!(
		all_faults.len(),
		10,
		"Expected 10 fault kinds; if a new member is added, update this suite and explicit handling"
	);

	for fault in all_faults {
		let script = ResponseScript::from_fault(*fault);
		match fault {
			FaultKind::MidStreamDrop => {
				assert_eq!(script.status, 200);
				assert!(
					script
						.chunks
						.iter()
						.any(|c| matches!(c, WireChunk::HardClose))
				);
			},
			FaultKind::IdleStall => {
				assert_eq!(script.status, 200);
				assert!(
					script
						.chunks
						.iter()
						.any(|c| matches!(c, WireChunk::IdleStall))
				);
			},
			FaultKind::Http401 => {
				assert_eq!(script.status, 401);
				assert!(!script.chunks.is_empty());
			},
			FaultKind::Http429 => {
				assert_eq!(script.status, 429);
				assert!(
					script
						.headers
						.iter()
						.any(|(k, _)| k.eq_ignore_ascii_case("retry-after"))
				);
			},
			FaultKind::Http500 => {
				assert_eq!(script.status, 500);
			},
			FaultKind::Http503 => {
				assert_eq!(script.status, 503);
			},
			FaultKind::TruncatedJson => {
				assert_eq!(script.status, 200);
			},
			FaultKind::InvalidUtf8 => {
				assert_eq!(script.status, 200);
			},
			FaultKind::UnterminatedEvent => {
				assert_eq!(script.status, 200);
			},
			FaultKind::UnexpectedThinkingBlock => {
				assert_eq!(script.status, 200);
			},
		}
	}
}

/// WHY: Provider requests with HTTP chunked request bodies must be parsed
/// correctly into contiguous bytes.
///
/// What it does not catch: Infinite streaming chunked request uploads.
#[tokio::test]
async fn chunked_request_body_is_parsed_correctly() {
	timeout(TEST_TIMEOUT, async {
		let engine = Engine::bind().await.expect("bind engine");
		engine.route(
			"/chunked_in",
			ResponseScript::ok().raw_body(Bytes::from_static(b"{\"status\":\"received\"}")),
		);

		let mut stream = TcpStream::connect(engine.addr()).await.expect("connect");
		let req = format!(
			"POST /chunked_in HTTP/1.1\r\nHost: {}\r\nTransfer-Encoding: chunked\r\nConnection: \
			 close\r\n\r\n5\r\nhello\r\n6\r\n world\r\n0\r\n\r\n",
			engine.addr()
		);
		stream
			.write_all(req.as_bytes())
			.await
			.expect("write chunked req");

		let mut resp = Vec::new();
		stream.read_to_end(&mut resp).await.expect("read response");
		let resp_str = String::from_utf8_lossy(&resp);
		assert!(resp_str.contains("HTTP/1.1 200 OK"));

		let recorded = engine.recorded_requests_for("/chunked_in");
		assert_eq!(recorded.len(), 1);
		assert_eq!(recorded[0].body_str().unwrap(), "hello world");
	})
	.await
	.expect("test must terminate within bounded deadline");
}

/// WHY: Engine drop must terminate background server listener task immediately.
///
/// What it does not catch: OS socket port release `TIME_WAIT` interval.
#[tokio::test]
async fn engine_shuts_down_cleanly_on_drop() {
	timeout(TEST_TIMEOUT, async {
		let addr = {
			let engine = Engine::bind().await.expect("bind engine");
			engine.addr()
		}; // engine is dropped here

		// After drop, connecting to that address should fail or be rejected
		tokio::time::sleep(Duration::from_millis(50)).await;
		let conn = TcpStream::connect(addr).await;
		assert!(conn.is_err(), "connecting to dropped engine should fail");
	})
	.await
	.expect("test must terminate within bounded deadline");
}
