import { EDIT_MODES } from "../../utils/edit-mode";
import { DEFAULT_BASH_INTERCEPTOR_RULES } from "../bash-interceptor-rules";
import { EMPTY_STRING_ARRAY, EMPTY_STRING_RECORD } from "./shared";

/** Editing domain slice of SETTINGS_SCHEMA — composed in ../settings-schema.ts. */
export const EDITING_SETTINGS = {
	// ────────────────────────────────────────────────────────────────────────
	// Editing
	// ────────────────────────────────────────────────────────────────────────

	// Edit tool
	"edit.mode": {
		type: "enum",
		values: EDIT_MODES,
		default: "hashline",
		ui: {
			tab: "files",
			group: "Editing",
			label: "Edit Mode",
			description: "Select the edit tool variant (replace, patch, hashline, or apply_patch)",
		},
	},

	// Per-model override of `edit.mode`, keyed by a substring of the model id
	// (`{ "kimi": "replace" }`), read by `Settings.getEditVariantForModel` and
	// outranking `edit.mode` for any model whose id contains the pattern.
	//
	// Declared here and not only read: it is an operator-facing knob that
	// production consults on every edit and that docs/environment-variables.md
	// tells operators outranks `edit.mode`, yet it was absent from the schema,
	// so it had no type, no validated shape, no default, and no row in the
	// generated reference. No `ui` block, because a pattern-to-mode table is not
	// something the settings selector can edit; it lives in the
	// configuration-file section of docs/settings-reference.md.
	"edit.modelVariants": { type: "record", default: EMPTY_STRING_RECORD },

	"edit.fuzzyMatch": {
		type: "boolean",
		default: true,
		ui: {
			tab: "files",
			group: "Editing",
			label: "Fuzzy Match",
			description: "Accept high-confidence fuzzy matches for whitespace differences",
		},
	},

	"edit.fuzzyThreshold": {
		type: "number",
		default: 0.95,
		ui: {
			tab: "files",
			group: "Editing",
			label: "Fuzzy Match Threshold",
			description: "Similarity threshold (0-1) for accepting fuzzy matches",
			options: [
				{ value: "0.85", label: "0.85", description: "Lenient" },
				{ value: "0.90", label: "0.90", description: "Moderate" },
				{ value: "0.95", label: "0.95", description: "Default" },
				{ value: "0.98", label: "0.98", description: "Strict" },
			],
		},
	},

	"edit.streamingAbort": {
		type: "boolean",
		default: false,
		ui: {
			tab: "files",
			group: "Editing",
			label: "Abort on Failed Preview",
			description: "Abort streaming edit tool calls when patch preview fails",
		},
	},

	"edit.blockAutoGenerated": {
		type: "boolean",
		default: true,
		ui: {
			tab: "files",
			group: "Editing",
			label: "Block Auto-Generated Files",
			description: "Prevent editing of files that appear to be auto-generated (protoc, sqlc, swagger, etc.)",
		},
	},

	readLineNumbers: {
		type: "boolean",
		default: false,
		ui: {
			tab: "files",
			group: "Reading",
			label: "Line Numbers",
			description: "Prepend line numbers to read tool output by default",
		},
	},

	"read.defaultLimit": {
		type: "number",
		default: 300,
		ui: {
			tab: "files",
			group: "Reading",
			label: "Default Read Limit",
			description: "Default number of lines returned when agent calls read without a limit",
			options: [
				{ value: "200", label: "200 lines" },
				{ value: "300", label: "300 lines" },
				{ value: "500", label: "500 lines" },
				{ value: "1000", label: "1000 lines" },
				{ value: "5000", label: "5000 lines" },
			],
		},
	},

	"read.summarize.enabled": {
		type: "boolean",
		default: true,
		ui: {
			tab: "files",
			group: "Read Summaries",
			label: "Enable Read Summaries",
			description: "Return structural code summaries when read is called without an explicit selector",
		},
	},

	"read.summarize.prose": {
		type: "boolean",
		default: false,
		ui: {
			tab: "files",
			group: "Read Summaries",
			label: "Prose Summaries",
			description: "Return structural summaries for Markdown and plain text reads",
		},
	},

	"read.summarize.minBodyLines": {
		type: "number",
		default: 4,
		ui: {
			min: 0, // a line count cannot be negative
			tab: "files",
			group: "Read Summaries",
			label: "Read Summary Body Lines",
			description: "Minimum multiline body or literal length before read summaries collapse it",
		},
	},

	"read.summarize.minCommentLines": {
		type: "number",
		default: 6,
		ui: {
			min: 0, // a line count cannot be negative
			tab: "files",
			group: "Read Summaries",
			label: "Read Summary Comment Lines",
			description: "Minimum multiline block comment length before read summaries collapse it",
		},
	},

	"read.summarize.minTotalLines": {
		type: "number",
		default: 100,
		ui: {
			min: 0, // a line count cannot be negative
			tab: "files",
			group: "Read Summaries",
			label: "Read Summary Minimum File Length",
			description: "Files with fewer total lines are read verbatim instead of structurally summarized",
		},
	},

	"read.summarize.unfoldUntil": {
		type: "number",
		default: 50,
		ui: {
			min: 0, // a line count cannot be negative
			tab: "files",
			group: "Read Summaries",
			label: "Read Summary Unfold Target",
			description:
				"BFS-unfold elidable spans until the summary is at least this many visible lines. 0 keeps only the outermost elisions.",
		},
	},

	"read.summarize.unfoldLimit": {
		type: "number",
		default: 100,
		ui: {
			min: 0, // a line count cannot be negative
			tab: "files",
			group: "Read Summaries",
			label: "Read Summary Unfold Ceiling",
			description:
				"Hard ceiling on summary size while BFS-unfolding. An unfold whose revealed lines would exceed this is skipped (that span stays folded) and unfolding continues with the remaining spans.",
		},
	},

	"read.toolResultPreview": {
		type: "boolean",
		default: false,
		ui: {
			tab: "files",
			group: "Reading",
			label: "Inline Read Previews",
			description: "Render read tool results inline in the transcript instead of summary rows",
		},
	},

	// LSP
	"lsp.enabled": {
		type: "boolean",
		// Off: it starts a language server per project, and its two policy statements plus
		// the tool description are among the larger things the prompt carries. Both drop
		// out with the tool, so a session that does no symbol work does not pay for it.
		default: false,
		ui: {
			tab: "files",
			group: "LSP",
			label: "Enable LSP",
			description: "Enable the lsp tool for code intelligence (definitions, references, diagnostics, rename)",
		},
	},

	// The five knobs below only mean something while a language server runs, so
	// each is conditioned on the master above. `lsp.enabled` ships off, and the
	// five rendered anyway: a Files tab offering "Format on Write" and three
	// diagnostics rules to a session with no server at all.
	"lsp.lazy": {
		type: "boolean",
		default: true,
		ui: {
			tab: "files",
			group: "LSP",
			label: "Lazy LSP Startup",
			condition: "lspEnabled",
			description:
				"Start language servers on first use (lsp tool or editing a matching file type) instead of at session startup",
		},
	},

	"lsp.formatOnWrite": {
		type: "boolean",
		default: false,
		ui: {
			tab: "files",
			group: "LSP",
			label: "Format on Write",
			condition: "lspEnabled",
			description: "Automatically format code files using LSP after writing",
		},
	},

	"lsp.diagnosticsOnWrite": {
		type: "boolean",
		default: true,
		ui: {
			tab: "files",
			group: "LSP",
			label: "Diagnostics on Write",
			condition: "lspEnabled",
			description: "Return LSP diagnostics after writing code files",
		},
	},

	"lsp.diagnosticsOnEdit": {
		type: "boolean",
		default: false,
		ui: {
			tab: "files",
			group: "LSP",
			label: "Diagnostics on Edit",
			condition: "lspEnabled",
			description: "Return LSP diagnostics after editing code files",
		},
	},

	"lsp.diagnosticsDeduplicate": {
		type: "boolean",
		default: true,
		ui: {
			tab: "files",
			group: "LSP",
			label: "Deduplicate Diagnostics",
			condition: "lspEnabled",
			description: "Suppress post-edit LSP diagnostics already shown for a file; only surface new or changed ones",
		},
	},

	"bash.enabled": {
		type: "boolean",
		default: true,
		ui: {
			tab: "shell",
			group: "Bash",
			label: "Enable Bash",
			description: "Enable the bash tool for shell command execution",
		},
	},

	"bash.stallDetection.enabled": {
		type: "boolean",
		default: false,
		ui: {
			tab: "shell",
			group: "Bash",
			label: "Bash Stall Detection",
			description:
				"Watch for a bash command that stops producing output; background it and tell the model it may be stuck so it can cancel a truly hung command. Recommends, never force-kills.",
		},
	},

	// Bash interceptor
	"bashInterceptor.enabled": {
		type: "boolean",
		default: false,
		ui: {
			tab: "shell",
			group: "Bash",
			label: "Bash Interceptor",
			description: "Block shell commands that have dedicated tools",
		},
	},
	"bashInterceptor.patterns": { type: "array", default: DEFAULT_BASH_INTERCEPTOR_RULES },

	// Shell output minimizer
	"shellMinimizer.enabled": {
		type: "boolean",
		default: true,
		ui: {
			tab: "shell",
			group: "Bash",
			label: "Shell Minimizer",
			description: "Compress verbose shell output (git, npm, cargo, etc.) before returning it to the agent",
		},
	},
	"shellMinimizer.settingsPath": {
		type: "string",
		default: undefined,
	},
	"shellMinimizer.only": { type: "array", default: EMPTY_STRING_ARRAY },
	"shellMinimizer.except": { type: "array", default: EMPTY_STRING_ARRAY },
	"shellMinimizer.maxCaptureBytes": {
		type: "number",
		default: 4 * 1024 * 1024,
	},
	"shellMinimizer.sourceOutlineLevel": {
		type: "enum",
		values: ["default", "aggressive"] as const,
		default: "default",
		ui: {
			tab: "shell",
			group: "Bash",
			label: "Shell Minimizer Source Outline",
			description: "Source outline mode for cat/read of source files: default or aggressive",
		},
	},
	"shellMinimizer.legacyFilters": {
		type: "boolean",
		default: undefined,
	},

	// Eval (per-backend toggles; add more as new backends ship, e.g. eval.ts)
	"eval.py": {
		type: "boolean",
		default: true,
		ui: {
			tab: "shell",
			group: "Eval & Runtimes",
			label: "Python Eval Backend",
			description: "Allow the eval tool to dispatch Python cells to the IPython kernel",
		},
	},

	"eval.js": {
		type: "boolean",
		default: true,
		ui: {
			tab: "shell",
			group: "Eval & Runtimes",
			label: "JavaScript Eval Backend",
			description: "Allow the eval tool to dispatch JavaScript cells to the in-process runtime",
		},
	},

	"eval.rb": {
		type: "boolean",
		default: false,
		ui: {
			tab: "shell",
			group: "Eval & Runtimes",
			label: "Ruby Eval Backend",
			description: "Allow the eval tool to dispatch Ruby cells to the persistent Ruby kernel",
		},
	},

	"eval.jl": {
		type: "boolean",
		default: false,
		ui: {
			tab: "shell",
			group: "Eval & Runtimes",
			label: "Julia Eval Backend",
			description: "Allow the eval tool to dispatch Julia cells to the persistent Julia kernel",
		},
	},

	// Runtime knobs (consumed by eval backends and the /python slash command)
	"ruby.kernelMode": {
		type: "enum",
		values: ["session", "per-call"] as const,
		default: "session",
		ui: {
			tab: "shell",
			group: "Eval & Runtimes",
			label: "Ruby Kernel Mode",
			description: "Keep the Ruby kernel alive across eval calls or start fresh each time",
		},
	},

	"julia.kernelMode": {
		type: "enum",
		values: ["session", "per-call"] as const,
		default: "session",
		ui: {
			tab: "shell",
			group: "Eval & Runtimes",
			label: "Julia Kernel Mode",
			description: "Keep the Julia kernel alive across eval calls or start fresh each time",
		},
	},

	"python.kernelMode": {
		type: "enum",
		values: ["session", "per-call"] as const,
		default: "session",
		ui: {
			tab: "shell",
			group: "Eval & Runtimes",
			label: "Python Kernel Mode",
			description: "Keep the IPython kernel alive across eval calls or start fresh each time",
		},
	},
	"python.interpreter": {
		type: "string",
		default: "",
		ui: {
			tab: "shell",
			group: "Eval & Runtimes",
			label: "Python Interpreter",
			description:
				"Optional path to an exact Python executable. When set, automatic Python runtime discovery is skipped.",
		},
	},
	"ruby.interpreter": {
		type: "string",
		default: "",
		ui: {
			tab: "shell",
			group: "Eval & Runtimes",
			label: "Ruby Interpreter",
			description:
				"Optional path to an exact Ruby executable. When set, automatic Ruby runtime discovery is skipped.",
		},
	},
	"julia.interpreter": {
		type: "string",
		default: "",
		ui: {
			tab: "shell",
			group: "Eval & Runtimes",
			label: "Julia Interpreter",
			description:
				"Optional path to an exact Julia executable. When set, automatic Julia runtime discovery is skipped.",
		},
	},
} as const;
