/**
 * The generated corpus the grep benchmark searches.
 *
 * The benchmark used to search this repository and the local Cargo registry, so a
 * number measured today could not be compared with one measured after the next
 * commit, on another machine, or by anyone whose registry held different crates.
 * This module generates the corpus from a version and a seed instead: the same pair
 * produces byte-identical files with identical path lengths, so two runs measure the
 * same work and a published ratio can name what it measured.
 *
 * Layout, for a 10,000-file corpus:
 *
 *   src/dNN/sNN/fNNNNN.ts   every corpus file, one constant path length
 *   .hidden/hNN.ts          hidden control, found only with hidden files enabled
 *   ignored/iNN.ts          gitignored control, found only with ignore rules off
 *   node_modules/pkg/nNN.ts pruned control, which the addon skips and rg does not
 *   .gitignore              `ignored/`
 *   manifest.json           what was generated, so a matching corpus is reused
 *
 * Nothing here imports a workspace package. `@veyyon/natives` deliberately carries
 * no dependency on `@veyyon/utils` (it was removed in 14.0.0, and utils depends on
 * this package), so the statistics the runner needs live in `grep-parity.ts`.
 */

import * as fs from "node:fs/promises";
import * as os from "node:os";
import * as path from "node:path";

/**
 * Bump when a change alters the generated bytes. A number measured against one
 * version is not comparable with a number measured against another, and the
 * manifest carries the version so a stale corpus is regenerated rather than reused.
 */
export const CORPUS_VERSION = 1;

/** The default seed. Any other seed produces a different, equally reproducible corpus. */
export const DEFAULT_SEED = 0x5eed1;

/** Files per corpus, unless a caller (a test, usually) asks for a smaller one. */
export const DEFAULT_FILE_COUNT = 10_000;

/** One in `MATCH_EVERY` corpus files carries matching lines: 5%. */
export const MATCH_EVERY = 20;

/** Matching lines in a matching file cycle 1..4, so per-file counts are not uniform. */
export const MAX_MATCHES_PER_FILE = 4;

/** Bytes per corpus file, before the closing line. 10,000 of these is ~40MiB. */
export const TARGET_FILE_BYTES = 4096;

/** Control files per control directory. */
export const CONTROL_FILES = 5;

/**
 * The pattern both engines search for. An import-like regex rather than a bare
 * literal, so the run measures a regex search and not just a memchr prefix scan.
 * The digit classes are what stop it from being literal.
 */
export const CORPUS_PATTERN = 'import \\{ [a-z]+[0-9]{4} \\} from "\\.\\./mod-[0-9]{2}/[a-z]+";';

/** Glob applied on both arms. Every generated file ends in `.ts`, controls included. */
export const CORPUS_GLOB = "*.ts";

/** Directory name of the gitignored control, named in the corpus `.gitignore`. */
export const IGNORED_DIR = "ignored";

/** Directory name of the hidden control. */
export const HIDDEN_DIR = ".hidden";

/** The addon prunes `node_modules` unless the glob names it; rg has to be told to. */
export const NODE_MODULES_DIR = "node_modules";

const FILLER_WORDS = [
	"alpha",
	"bravo",
	"cinder",
	"delta",
	"ember",
	"flint",
	"gamma",
	"harbor",
	"ingot",
	"jetty",
	"kelvin",
	"lumen",
	"morrow",
	"nimbus",
	"onyx",
	"pylon",
	"quartz",
	"rivet",
	"sable",
	"tundra",
] as const;

/** What `generateCorpus` produced, and what the runner reports as provenance. */
export interface CorpusFacts {
	readonly root: string;
	readonly version: number;
	readonly seed: number;
	/** Corpus files under `src/`, excluding every control. */
	readonly files: number;
	/** Bytes across every generated file, controls included. */
	readonly bytes: number;
	/** Length of every `src/` relative path. Constant by construction. */
	readonly pathLength: number;
	/** Files under `src/` that carry at least one matching line. */
	readonly matchingFiles: number;
	/** Matching lines under `src/`. */
	readonly srcMatches: number;
	/** Matching lines in each control directory. */
	readonly hiddenMatches: number;
	readonly ignoredMatches: number;
	readonly nodeModulesMatches: number;
	/** True when the corpus on disk was reused rather than written. */
	readonly reused: boolean;
}

/** What a caller asks `generateCorpus` for. */
export interface CorpusRequest {
	readonly root?: string;
	readonly seed?: number;
	readonly files?: number;
	/** Write the corpus even when a matching manifest is already on disk. */
	readonly regenerate?: boolean;
}

/**
 * A small deterministic generator (mulberry32). `node:crypto` would give better
 * bits and worse reproducibility across runtimes; the corpus needs the second.
 */
export function mulberry32(seed: number): () => number {
	let state = seed >>> 0;
	return () => {
		state = (state + 0x6d2b79f5) >>> 0;
		let value = state;
		value = Math.imul(value ^ (value >>> 15), value | 1);
		value ^= value + Math.imul(value ^ (value >>> 7), value | 61);
		return ((value ^ (value >>> 14)) >>> 0) / 4294967296;
	};
}

function pad(value: number, width: number): string {
	return String(value).padStart(width, "0");
}

/**
 * The corpus directory for a version and seed, under the user's cache directory.
 *
 * Not inside the repository: a corpus there is reached through the repository's own
 * `.gitignore`, which would silently empty the arm that searches with ignore rules
 * on. Not `/tmp` either, which is a small capped tmpfs on the machines this runs on.
 */
export function defaultCorpusDir(seed: number = DEFAULT_SEED, version: number = CORPUS_VERSION): string {
	const cacheHome = process.env.XDG_CACHE_HOME || path.join(os.homedir(), ".cache");
	return path.join(cacheHome, "veyyon", "grep-bench", `v${version}-${pad(seed, 8)}`);
}

/** Relative path of corpus file `index`. Every one of these is the same length. */
export function corpusRelativePath(index: number): string {
	const outer = pad(Math.floor(index / 1000) % 100, 2);
	const inner = pad(Math.floor(index / 100) % 10, 2);
	return `src/d${outer}/s${inner}/f${pad(index, 5)}.ts`;
}

/** Whether corpus file `index` carries matching lines. */
export function isMatchingIndex(index: number): boolean {
	return index % MATCH_EVERY === 0;
}

/** How many matching lines corpus file `index` carries. */
export function matchesForIndex(index: number): number {
	if (!isMatchingIndex(index)) return 0;
	return 1 + ((index / MATCH_EVERY) % MAX_MATCHES_PER_FILE);
}

function matchingLine(rand: () => number, ordinal: number): string {
	const symbol = FILLER_WORDS[Math.floor(rand() * FILLER_WORDS.length)] ?? "alpha";
	const module = FILLER_WORDS[Math.floor(rand() * FILLER_WORDS.length)] ?? "bravo";
	return `import { ${symbol}${pad(ordinal % 10_000, 4)} } from "../mod-${pad(ordinal % 100, 2)}/${module}";`;
}

function fillerLine(rand: () => number, ordinal: number): string {
	const name = FILLER_WORDS[Math.floor(rand() * FILLER_WORDS.length)] ?? "alpha";
	const other = FILLER_WORDS[Math.floor(rand() * FILLER_WORDS.length)] ?? "bravo";
	return `const ${name}${pad(ordinal, 4)} = compute(${ordinal}, "${other}", ${Math.floor(rand() * 4096)});`;
}

/**
 * The bytes of one generated file. Pure in (`index`, `seed`, `matches`), which is
 * what makes two corpora with the same version and seed byte-identical.
 */
export function corpusFileContents(index: number, seed: number, matches: number): string {
	const rand = mulberry32((seed ^ Math.imul(index + 1, 0x9e3779b1)) >>> 0);
	const filler: string[] = [];
	let bytes = 0;
	const header = `// f${pad(index, 5)} corpus v${CORPUS_VERSION} seed ${pad(seed, 8)} -- generated, do not edit`;
	bytes += header.length + 1;
	for (let ordinal = 0; bytes < TARGET_FILE_BYTES; ordinal++) {
		const line = fillerLine(rand, ordinal);
		filler.push(line);
		bytes += line.length + 1;
	}
	const lines = [header, ...filler];
	// Spread the matching lines through the body so a match is never at a fixed offset.
	for (let ordinal = 0; ordinal < matches; ordinal++) {
		const at = 1 + Math.floor(((ordinal + 1) * filler.length) / (matches + 1));
		lines.splice(at + ordinal, 0, matchingLine(rand, index + ordinal));
	}
	lines.push(`export const tag${pad(index, 5)} = ${matches};`);
	return `${lines.join("\n")}\n`;
}

interface Manifest {
	version: number;
	seed: number;
	files: number;
	bytes: number;
	pathLength: number;
	matchingFiles: number;
	srcMatches: number;
	hiddenMatches: number;
	ignoredMatches: number;
	nodeModulesMatches: number;
}

function controlContents(prefix: string, ordinal: number, seed: number): string {
	const rand = mulberry32((seed ^ Math.imul(ordinal + 1, 0x85ebca6b)) >>> 0);
	const lines = [
		`// ${prefix}${pad(ordinal, 2)} control file, corpus v${CORPUS_VERSION}`,
		matchingLine(rand, ordinal),
		fillerLine(rand, ordinal),
	];
	return `${lines.join("\n")}\n`;
}

async function readManifest(root: string): Promise<Manifest | null> {
	try {
		const parsed: unknown = JSON.parse(await fs.readFile(path.join(root, "manifest.json"), "utf8"));
		if (parsed && typeof parsed === "object") return parsed as Manifest;
		return null;
	} catch {
		return null;
	}
}

function factsFrom(root: string, manifest: Manifest, reused: boolean): CorpusFacts {
	return {
		root,
		version: manifest.version,
		seed: manifest.seed,
		files: manifest.files,
		bytes: manifest.bytes,
		pathLength: manifest.pathLength,
		matchingFiles: manifest.matchingFiles,
		srcMatches: manifest.srcMatches,
		hiddenMatches: manifest.hiddenMatches,
		ignoredMatches: manifest.ignoredMatches,
		nodeModulesMatches: manifest.nodeModulesMatches,
		reused,
	};
}

/**
 * Write the corpus, or reuse the one on disk when its manifest already describes
 * exactly this version, seed and file count.
 */
export async function generateCorpus(request: CorpusRequest = {}): Promise<CorpusFacts> {
	const seed = request.seed ?? DEFAULT_SEED;
	const files = request.files ?? DEFAULT_FILE_COUNT;
	const root = request.root ?? defaultCorpusDir(seed);

	const existing = await readManifest(root);
	if (
		!request.regenerate &&
		existing &&
		existing.version === CORPUS_VERSION &&
		existing.seed === seed &&
		existing.files === files
	) {
		return factsFrom(root, existing, true);
	}

	await fs.rm(root, { recursive: true, force: true });
	let bytes = 0;
	let matchingFiles = 0;
	let srcMatches = 0;
	let lastDir = "";
	for (let index = 0; index < files; index++) {
		const relative = corpusRelativePath(index);
		const absolute = path.join(root, relative);
		const dir = path.dirname(absolute);
		if (dir !== lastDir) {
			await fs.mkdir(dir, { recursive: true });
			lastDir = dir;
		}
		const matches = matchesForIndex(index);
		if (matches > 0) {
			matchingFiles++;
			srcMatches += matches;
		}
		const contents = corpusFileContents(index, seed, matches);
		bytes += Buffer.byteLength(contents);
		await fs.writeFile(absolute, contents);
	}

	const controls: Array<{ dir: string; prefix: string }> = [
		{ dir: HIDDEN_DIR, prefix: "h" },
		{ dir: IGNORED_DIR, prefix: "i" },
		{ dir: path.join(NODE_MODULES_DIR, "pkg"), prefix: "n" },
	];
	for (const control of controls) {
		await fs.mkdir(path.join(root, control.dir), { recursive: true });
		for (let ordinal = 0; ordinal < CONTROL_FILES; ordinal++) {
			const contents = controlContents(control.prefix, ordinal, seed);
			bytes += Buffer.byteLength(contents);
			await fs.writeFile(path.join(root, control.dir, `${control.prefix}${pad(ordinal, 2)}.ts`), contents);
		}
	}
	const gitignore = `${IGNORED_DIR}/\n`;
	bytes += Buffer.byteLength(gitignore);
	await fs.writeFile(path.join(root, ".gitignore"), gitignore);

	const manifest: Manifest = {
		version: CORPUS_VERSION,
		seed,
		files,
		bytes,
		pathLength: corpusRelativePath(0).length,
		matchingFiles,
		srcMatches,
		hiddenMatches: CONTROL_FILES,
		ignoredMatches: CONTROL_FILES,
		nodeModulesMatches: CONTROL_FILES,
	};
	await fs.writeFile(path.join(root, "manifest.json"), `${JSON.stringify(manifest, null, 2)}\n`);
	return factsFrom(root, manifest, false);
}
