[package]
name = "veyyon-iso"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true

[lints]
workspace = true

[dependencies]
async-trait.workspace = true
veyyon-diff-kernel.workspace = true
tokio.workspace = true

[target.'cfg(unix)'.dependencies]
libc.workspace = true

[target.'cfg(target_os = "linux")'.dependencies]
parking_lot.workspace = true

[target.'cfg(windows)'.dependencies]
parking_lot.workspace = true
windows-sys.workspace = true

[dev-dependencies]
veyyon-test-scratch.workspace = true
