//! Usage and costs settings page body rendering (§5.9).

use veyyon_desktop_kit::{Badge, Button, ButtonSize, TintRole, TokenSet};
use veyyon_desktop_model::SurfaceId;
use veyyon_desktop_tokens::SettingsSurfaceTokens;
use veyyon_gpui::{ClickEvent, Context, Div, ParentElement, Styled, div};

use crate::{
	Intent, ShellView,
	settings::{
		SettingsState,
		row::{empty_state_row, setting_row},
	},
};

fn format_number(n: u64) -> String {
	let s = n.to_string();
	let mut result = String::new();
	let len = s.len();
	for (i, c) in s.chars().enumerate() {
		if i > 0 && (len - i).is_multiple_of(3) {
			result.push(',');
		}
		result.push(c);
	}
	result
}

/// Renders the Usage metrics and financial accounting page rows.
pub fn render_usage_page(
	state: &SettingsState,
	geometry: &SettingsSurfaceTokens,
	tokens: &TokenSet,
	cx: &Context<ShellView>,
) -> Div {
	let mut container = div()
		.flex()
		.flex_col()
		.gap(veyyon_gpui::px(geometry.row_gap));

	let Some(totals) = &state.usage else {
		return container.child(empty_state_row(
			"No usage data recorded for active session.",
			geometry,
			tokens,
		));
	};

	let shell_state = cx.entity().read(cx).state();
	let av = shell_state
		.controls
		.availability(&SurfaceId::UsageRefreshButton);

	// Refresh action row
	let refresh_btn = Button::new("Refresh")
		.id("usage-refresh-btn")
		.size(ButtonSize::Small)
		.on_click(cx.listener(|view, _e: &ClickEvent, _w, cx| {
			view.dispatch(Intent::RefreshUsage);
			cx.notify();
		}));
	container = container.child(setting_row(
		"Usage Metrics",
		Some("Accumulated token consumption and session accounting"),
		refresh_btn,
		&av,
		geometry,
		tokens,
	));

	// Cost total
	let cost_str = totals
		.cost_microusd
		.map_or_else(|| "$0.00".to_string(), |u| format!("${:.4}", u as f64 / 1_000_000.0));
	container = container.child(setting_row(
		"Session Cost Total",
		Some("Accumulated monetary expenditure for active session"),
		Badge::new(cost_str, TintRole::Done),
		&av,
		geometry,
		tokens,
	));

	// Input tokens
	container = container.child(setting_row(
		"Input Tokens",
		Some("Prompt and context tokens ingested by models"),
		Badge::new(format_number(totals.input_tokens), TintRole::Plan),
		&av,
		geometry,
		tokens,
	));

	// Output tokens
	container = container.child(setting_row(
		"Output Tokens",
		Some("Completion tokens generated by models"),
		Badge::new(format_number(totals.output_tokens), TintRole::Plan),
		&av,
		geometry,
		tokens,
	));

	// Cache read tokens
	container = container.child(setting_row(
		"Cache Read Tokens",
		Some("Tokens served from prompt prefix cache"),
		Badge::new(format_number(totals.cache_read_tokens), TintRole::Plan),
		&av,
		geometry,
		tokens,
	));

	// Cache write tokens
	container = container.child(setting_row(
		"Cache Write Tokens",
		Some("Tokens written to prompt prefix cache"),
		Badge::new(format_number(totals.cache_write_tokens), TintRole::Plan),
		&av,
		geometry,
		tokens,
	));

	// Orchestration tokens
	container = container.child(setting_row(
		"Orchestration Tokens",
		Some("Tokens consumed by subagent task routing"),
		Badge::new(format_number(totals.orchestration_tokens), TintRole::Plan),
		&av,
		geometry,
		tokens,
	));

	// Premium requests
	container = container.child(setting_row(
		"Premium Requests",
		Some("Number of high-tier model requests dispatched"),
		Badge::new(format_number(totals.premium_requests as u64), TintRole::Plan),
		&av,
		geometry,
		tokens,
	));

	container
}
