#!/usr/bin/env bun
/**
 * Bundle `@veyyon/tool-render` + the local `<vey-tool-view>` web component
 * into a single self-contained script (React included, CSS inlined) for
 * embedding in coding-agent HTML session exports.
 *
 * Output: packages/coding-agent/src/export/html/tool-views.generated.js
 * Run via `bun run gen:tool-views` after changing packages/tool-render or src/tool-render/.
 *
 * The second line of the output is an input stamp: the SHA-256 of every file the bundler read,
 * plus this script, and the repository-relative list of those files. `toolViewsStaleness` re-hashes
 * the listed files and compares, so a bundle built from older sources is detected and rebuilt
 * instead of being served with globals the current export viewer calls and the stale bundle lacks.
 */
import { createHash } from "node:crypto";
import * as fs from "node:fs/promises";
import * as path from "node:path";

const root = path.join(import.meta.dirname, "..");
const repoRoot = path.join(root, "../..");

/** The gitignored bundle `gen:tool-views` writes. */
export const TOOL_VIEWS_OUT_FILE = path.join(repoRoot, "packages/coding-agent/src/export/html/tool-views.generated.js");

const BANNER = "// Auto-generated by clients/web/scripts/build-tool-views.ts - DO NOT EDIT\n";
const STAMP_PREFIX = "// tool-views inputs ";

/** A repository-relative path with `/` separators, so a stamp reads the same on every platform. */
function repoRelative(file: string): string {
	return path.relative(repoRoot, file).split(path.sep).join("/");
}

function isMissingFile(error: unknown): boolean {
	return error instanceof Error && "code" in error && (error.code === "ENOENT" || error.code === "ENOTDIR");
}

/**
 * SHA-256 over each input's path and bytes, in the order given. `null` when an input no longer
 * exists: a bundle that read a file which is gone cannot be current.
 */
async function hashInputs(inputs: readonly string[]): Promise<string | null> {
	let contents: Array<readonly [string, Buffer]>;
	try {
		contents = await Promise.all(
			inputs.map(async input => [input, await fs.readFile(path.join(repoRoot, input))] as const),
		);
	} catch (error) {
		if (isMissingFile(error)) return null;
		throw error;
	}
	const hash = createHash("sha256");
	for (const [input, bytes] of contents) {
		hash.update(`${input}\0${bytes.length}\0`);
		hash.update(bytes);
	}
	return hash.digest("hex");
}

/** The stamp line a generated bundle carries, parsed. `null` when the bundle has none. */
function readStamp(script: string): { hash: string; inputs: string[] } | null {
	const start = script.indexOf("\n") + 1;
	if (start === 0 || !script.startsWith(STAMP_PREFIX, start)) return null;
	const end = script.indexOf("\n", start);
	const line = script.slice(start + STAMP_PREFIX.length, end < 0 ? undefined : end);
	const space = line.indexOf(" ");
	if (space < 0) return null;
	let inputs: unknown;
	try {
		inputs = JSON.parse(line.slice(space + 1));
	} catch {
		return null;
	}
	if (!Array.isArray(inputs) || inputs.length === 0 || !inputs.every(input => typeof input === "string")) return null;
	return { hash: line.slice(0, space), inputs };
}

/** The generated script text, byte-identical to what `gen:tool-views` writes to `TOOL_VIEWS_OUT_FILE`. */
export async function buildToolViewsScript(): Promise<string> {
	const result = await Bun.build({
		entrypoints: [path.join(root, "src/tool-render/standalone.tsx")],
		target: "browser",
		format: "iife",
		minify: true,
		metafile: true,
		external: ["bun", "bun:ffi"],
		define: { "process.env.NODE_ENV": JSON.stringify("production") },
	});

	if (!result.success) {
		throw new Error(`tool-views bundle failed:\n${result.logs.map(String).join("\n")}`);
	}
	if (!result.metafile) throw new Error("tool-views bundle produced no metafile");

	let js = "";
	let css = "";
	for (const artifact of result.outputs) {
		if (artifact.path.endsWith(".css")) css += await artifact.text();
		else if (artifact.path.endsWith(".js")) js += await artifact.text();
	}
	if (!js) throw new Error("tool-views bundle produced no JS output");

	// Metafile keys are relative to the working directory the build ran in.
	const inputs = [
		...new Set([
			...Object.keys(result.metafile.inputs).map(input => repoRelative(path.resolve(input))),
			repoRelative(import.meta.filename),
		]),
	].sort();
	const hash = await hashInputs(inputs);
	if (hash === null) throw new Error("tool-views bundle read an input that no longer exists");

	// The bundle is inlined into a `<script>` tag by coding-agent's
	// `src/export/html` `getTemplate()`; a literal `</script` inside a JS string (react-dom
	// emits one) would terminate that tag early. `<\/script` is byte-identical
	// to the parser inside string literals, so escape unconditionally.
	const escapeInlineScript = (s: string): string => s.replaceAll("</script", "<\\/script");

	const styleInject = css
		? `(()=>{var s=document.createElement("style");s.dataset.ompToolViews="";s.textContent=${JSON.stringify(css.trim())};(document.head||document.documentElement).appendChild(s);})();\n`
		: "";
	const stamp = `${STAMP_PREFIX}${hash} ${JSON.stringify(inputs)}\n`;
	return BANNER + stamp + escapeInlineScript(styleInject + js);
}

/**
 * Why the bundle at `outFile` must be rebuilt, or `null` when it matches the sources it lists.
 *
 * Costs one read of the bundle and one of each listed input; nothing is built.
 */
export async function toolViewsStaleness(outFile: string = TOOL_VIEWS_OUT_FILE): Promise<string | null> {
	let script: string;
	try {
		script = await fs.readFile(outFile, "utf8");
	} catch (error) {
		if (isMissingFile(error)) return "missing";
		throw error;
	}
	const stamp = readStamp(script);
	if (!stamp) return "no input stamp";
	const hash = await hashInputs(stamp.inputs);
	if (hash === null) return "an input was removed";
	return hash === stamp.hash ? null : "sources changed since it was built";
}

/**
 * Build the bundle and replace `outFile` in one rename, so a concurrent reader sees the old bundle
 * or the new one and never a partial write.
 */
export async function writeToolViewsBundle(outFile: string = TOOL_VIEWS_OUT_FILE): Promise<number> {
	const script = await buildToolViewsScript();
	const temp = `${outFile}.${process.pid}.${Date.now()}.tmp`;
	try {
		await fs.writeFile(temp, script);
		await fs.rename(temp, outFile);
	} catch (error) {
		await fs.rm(temp, { force: true });
		throw error;
	}
	return script.length;
}

if (import.meta.main) {
	try {
		const bytes = await writeToolViewsBundle();
		console.log(`Generated ${path.relative(process.cwd(), TOOL_VIEWS_OUT_FILE)} (${(bytes / 1024).toFixed(1)} KiB)`);
	} catch (err) {
		console.error(err instanceof Error ? err.message : String(err));
		process.exit(1);
	}
}
