//! Exhaustive actions a surface may dispatch.
//!
//! [`UiCommand::class`] is the ownership boundary: frontend actions may change
//! only `FrontendState`; host actions create a correlated request and pending
//! state; shell actions return a typed shell effect.

mod class;

use crate::{model::*, navigation::*};

#[derive(Debug, Clone, Copy, PartialEq, Eq, serde::Serialize, serde::Deserialize)]
pub enum CommandClass {
	Frontend,
	Host,
	Shell,
}

#[rustfmt::skip]
#[derive(Debug, Clone, PartialEq, Eq, serde::Serialize, serde::Deserialize)]
pub enum UiCommand {
	Navigate(Route),
	/// Move one page through the settings nav, stopping at either end.
	///
	/// Relative rather than a `Navigate` to a named page, because a keystroke
	/// cannot name the page that comes after whichever one is open.
	StepSettingsPage { down: bool },
	SetBottomTab(BottomTab),
	SetInspectorTab(InspectorTab),
	ToggleSidebar,
	ToggleInspector,
	ToggleBottomDock,
	ResizeSidebar { width_milli_px: u32 },
	ResizeInspector { width_milli_px: u32 },
	ResizeBottomDock { height_milli_px: u32 },
	ConstrainPanels { width_milli_px: u32, height_milli_px: u32 },
	OpenOverlay(Overlay),
	CloseTopOverlay,
	CloseAllOverlays,
	SetPaletteQuery(String),
	MovePaletteCursor { down: bool },
	AcceptPalette,
	SetSessionFilter(String),
	PinSession(SessionId),
	UnpinSession(SessionId),
	CycleSession { forward: bool },
	SetFileFilter(String),
	SetAgentFilter(String),
	SetSettingsFilter(String),
	SetChangesFilter(String),
	SetChangesTreeMode(ChangesTreeMode),
	ToggleChangeFolder(String),
	ToggleChangeFile(FileId),
	SetReviewRange { path: String, range: Option<LineRange> },
	AddReviewComment { session: SessionId, path: String, range: LineRange, text: String },
	SetChangeBase(Option<String>),
	RevealFile(FileId),
	SetProblemFilter(String),
	ToggleProblemLevel(DiagnosticLevel),
	SetOutputPaused(bool),
	SetOutputWrap(bool),
	ToggleOutputLevel(OutputLevel),
	SetModelQuery(String),
	SetProviderQuery(String),
	SetMcpQuery(String),
	SetExtensionQuery(String),
	SelectSession(SessionId),
	SelectEntry(EntryId),
	SelectFile(FileId),
	SelectAgent(AgentId),
	ToggleFileCursor,
	OpenFileCursor,
	SelectTerminal(TerminalId),
	SelectWorkspace(WorkspaceId),
	SetFileSearchMode(FileSearchMode),
	MoveFileCursor { forward: bool },
	SetFileRange(Option<LineRange>),
	SelectDiagnostic(NoticeId),
	SelectHunk { file: FileId, hunk: usize },
	SetTerminalPresentation(TerminalPresentation),
	SetTerminalSearch { terminal: TerminalId, query: String },
	SetTerminalFollowTail { terminal: TerminalId, follow: bool },
	SplitTerminal { terminal: TerminalId, with: TerminalId, axis: SplitAxis },
	SetTerminalSplitRatio { ratio_milli: u16 },
	SetPlanReviewTab(PlanReviewTab),
	ToggleToolDisclosure(ToolId),
	ToggleEntryDisclosure(EntryId),
	ToggleAgentExpanded(AgentId),
	ToggleFileExpanded(FileId),
	EditDraft { session: SessionId, text: String },
	SetDraftCaret { session: SessionId, byte: usize },
	SetDraftSelection { session: SessionId, anchor: usize, head: usize },
	AddAttachment { session: SessionId, kind: AttachmentKind },
	RemoveAttachment { session: SessionId, attachment: AttachmentId },
	ChooseFiles { session: SessionId },
	ChooseImages { session: SessionId },
	ReattachAttachment { session: SessionId, attachment: AttachmentId },
	RetryAttachment { session: SessionId, attachment: AttachmentId },
	EditAgentChatDraft { agent: AgentId, text: String },
	SetModelFavorite { provider: ProviderId, model: ModelId, favorite: bool },
	PreviewTheme(String),
	CancelThemePreview,
	SetDarkAppearance(bool),
	SetFontSize { milli_px: u16 },
	SetReducedMotion(bool),
	SetDiffLayout(DiffLayout),
	SetDiffWrap(bool),
	SetDiffWhitespace(bool),
	SetGroupSessionsByWorkspace(bool),
	QuitWindow,
	CopyText(String),
	FocusComposer,
	FocusPalette,
	FocusTerminal(TerminalId),
	CopyEntry(EntryId),
	OpenImage { entry: EntryId, index: usize },
	JumpToLatest,
	JumpToOldest,
	RevealSelectedFile,
	CopyTerminalSelection { terminal: TerminalId, text: String },
	PasteTerminal(TerminalId),
	AddTerminalSelection { session: SessionId, terminal: TerminalId, text: String },
	CopyDiagnostic(NoticeId),
	OpenDiagnostic(NoticeId),
	CopyOutput,
	Attach { endpoint: Option<String> },
	Detach,
	RetryConnection,
	RequestShutdown,
	LoadSessions,
	LoadTranscript { session: SessionId, before: Option<EntryId> },
	RetryTranscript { session: SessionId },
	CreateSession { workspace: Option<WorkspaceId>, parent: Option<SessionId> },
	OpenSession(SessionId),
	RenameSession { session: SessionId, name: String },
	DeleteSession(SessionId),
	BranchSession { session: SessionId, entry: EntryId },
	ExportSession { session: SessionId, output_path: Option<String> },
	CompactSession { session: SessionId, instructions: Option<String> },
	HandoffSession { session: SessionId, instructions: Option<String> },
	SubmitPrompt { session: SessionId },
	Steer { session: SessionId },
	FollowUp { session: SessionId },
	AbortTurn { session: SessionId },
	SetQueueMode {
		session:   SessionId,
		steering:  QueueDelivery,
		follow_up: QueueDelivery,
		interrupt: InterruptMode,
	},
	CancelTool(ToolId),
	SelectInteractionOption { interaction: InteractionId, index: usize },
	ToggleInteractionOption { interaction: InteractionId, index: usize },
	EditInteractionText { interaction: InteractionId, text: String },
	EditInteractionNote { interaction: InteractionId, note: String },
	SubmitInteraction { interaction: InteractionId, response: InteractionResponse },
	CancelInteraction { interaction: InteractionId, timed_out: bool },
	LoadFileTree { workspace: WorkspaceId, parent: Option<FileId> },
	ReadFile { file: FileId, range: Option<LineRange> },
	SearchFiles { workspace: WorkspaceId, query: String, mode: FileSearchMode },
	OpenExternal(String),
	RefreshChanges(ChangeScope),
	SelectChangeScope(ChangeScope),
	CreateTerminal { cwd: Option<String> },
	AttachTerminal(TerminalId),
	WriteTerminal { terminal: TerminalId, bytes: Vec<u8> },
	ResizeTerminal { terminal: TerminalId, cols: u16, rows: u16 },
	RestartTerminal(TerminalId),
	ClearTerminal(TerminalId),
	CloseTerminal(TerminalId),
	StartProcess { spec: Value },
	WaitProcess(ProcessId),
	DescribeProcess(ProcessId),
	RefreshProcesses,
	FetchProcessLogs { process: ProcessId, from_byte: Option<u64> },
	SendProcessInput { process: ProcessId, text: String },
	SignalProcess { process: ProcessId, signal: String },
	StopProcess(ProcessId),
	RestartProcess(ProcessId),
	RefreshModels,
	SelectModel { provider: ProviderId, model: ModelId },
	SetThinkingLevel(String),
	RefreshProviders,
	StartProviderAuth(ProviderId),
	RefreshAuth,
	SubmitAuthSecret { provider: ProviderId, secret: String },
	OpenAuthUrl { provider: ProviderId, url: String },
	CancelAuthFlow { provider: ProviderId },
	RetryAuthFlow { provider: ProviderId },
	RefreshMcp,
	ConnectMcp(McpServerId),
	DisconnectMcp(McpServerId),
	SetMcpEnabled { server: McpServerId, enabled: bool },
	CallMcpTool { server: McpServerId, tool: String, arguments: Value },
	ReadMcpResource { server: McpServerId, uri: String },
	GetMcpPrompt { server: McpServerId, name: String, arguments: Vec<(String, String)> },
	RefreshExtensions,
	InvokeExtensionAction { extension: ExtensionId, action: String, input: Value },
	SetExtensionEnabled { extension: ExtensionId, enabled: bool },
	SetToolEnabled { tool: String, enabled: bool },
	RefreshAgents,
	FetchAgentTranscript { agent: AgentId, from_byte: u64 },
	ChatAgent { agent: AgentId, message: String },
	KillAgent(AgentId),
	ReviveAgent(AgentId),
	SpawnTask { agent: AgentId, prompt: String },
	CancelTask(TaskId),
	LoadSettings,
	EditSetting { path: SettingPath, value: Value },
	SetSetting { path: SettingPath, value: Value },
	ResetSetting(SettingPath),
	LoadThemes,
	SetTheme(String),
	LoadKeybindings,
	SetKeybinding { command: String, chord: Option<String> },
	RefreshDiagnostics,
	RetryDiagnosticSource(String),
	NextDiagnostic { forward: bool },
	DismissNotice(NoticeId),
	ClearOutput,
	GetUsage,
	GetContextBreakdown,
}
