"""Render the agent's provider routing from veybot's own configuration.

The agent (veyyon) reads its provider routing from `~/.veyyon/agent/models.yml`.
veybot used to require the operator to hand-write that file on the host and
bind-mount it in, which made it a SECOND configuration surface living outside
`.env`: undeclared, unvalidated, absent on a fresh machine (so `docker compose
up` failed on a missing mount source), and easy to leave disagreeing with
`VEYBOT_MODEL` after a model change.

It is generated here instead, from four keys in the one config file. The
apiKey field is written as the NAME of the environment variable rather than the
secret itself, which veyyon resolves from the process environment. The key
therefore never lands on disk: it stays in the env the agent subprocess already
needs it in.
"""

from __future__ import annotations

import logging
from pathlib import Path
from typing import Any

import yaml

from veybot.config import Settings

log = logging.getLogger(__name__)

LLM_API_KEY_ENV = "VEYBOT_LLM_API_KEY"
"""Env var veyyon resolves the gateway credential from.

Written into the generated `models.yml` verbatim. `model-registry.ts` resolves
an `apiKey` value by checking the environment first and treating the string as
a literal only if no such variable exists, so a name is the safe spelling.
"""


def _bare_model_id(model: str, provider: str) -> str:
    """Drop a leading `<provider>/` from a pool entry.

    Only OUR provider's prefix is stripped. A pool entry naming a different
    provider (`anthropic/...`) is left alone: it is addressed to a provider
    veybot does not generate, and rewriting it would silently re-point the
    request at the gateway.
    """
    model = model.strip()
    head, sep, tail = model.partition("/")
    if sep and head == provider and tail:
        return tail
    return model


def render_models_config(settings: Settings) -> dict[str, Any] | None:
    """Build the `models.yml` document, or None when veybot does not manage routing.

    Returning None is a real answer, not a failure: a native run on a developer
    machine uses the operator's own veyyon profile, which already has providers
    configured. veybot only takes ownership of the file when
    `VEYBOT_LLM_BASE_URL` says there is a gateway to point at.
    """
    base_url = settings.llm_base_url.strip()
    if not base_url:
        return None
    provider = settings.llm_provider_id.strip()
    # Every id in the pool is offered, so a comma-separated VEYBOT_MODEL still
    # resolves after a pragma override picks a sibling. `VEYBOT_MODEL` accepts
    # the `<provider>/<model>` spelling, but a provider block keys its entries
    # by the BARE model id, so the prefix is stripped here: leaving it in
    # published `veybot-gateway/veybot-gateway/<model>` and failed to resolve.
    models = [
        {"id": bare, "name": bare} for bare in dict.fromkeys(_bare_model_id(m, provider) for m in settings.model_pool)
    ]
    return {
        "providers": {
            provider: {
                "baseUrl": base_url,
                "api": settings.llm_api.strip(),
                "apiKey": LLM_API_KEY_ENV,
                "models": models,
            }
        }
    }


def render_models_yaml(settings: Settings) -> str | None:
    """Serialize `render_models_config`, or None when routing is unmanaged."""
    document = render_models_config(settings)
    if document is None:
        return None
    header = (
        "# Generated by veybot from .env; edits are overwritten on every start.\n"
        f"# Change VEYBOT_LLM_BASE_URL / VEYBOT_LLM_API / VEYBOT_LLM_PROVIDER_ID /\n"
        f"# VEYBOT_MODEL instead. The credential is read from ${LLM_API_KEY_ENV}\n"
        "# in the process environment and is deliberately not written here.\n"
    )
    return header + yaml.safe_dump(document, sort_keys=False, default_flow_style=False)


def write_agent_models_config(settings: Settings, agent_home: Path) -> Path | None:
    """Write the generated routing into `<agent_home>/.veyyon/agent/models.yml`.

    Returns the path written, or None when veybot does not manage routing.
    Written world-readable and owned by the caller: the agent runs as a slot
    user, so it has to be able to read this. That is safe precisely because the
    credential is a variable name here rather than the secret.
    """
    content = render_models_yaml(settings)
    if content is None:
        return None
    target = agent_home / ".veyyon" / "agent" / "models.yml"
    try:
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(content, encoding="utf-8")
        target.chmod(0o644)
    except OSError as exc:
        # Loud, and not swallowed into a silent misroute: without this file the
        # agent falls back to whatever routing it can find, which is how a run
        # ends up silently talking to the wrong provider.
        log.error("failed to write agent models config", extra={"path": str(target), "err": str(exc)})
        raise
    log.info(
        "agent models config written",
        extra={"path": str(target), "provider": settings.llm_provider_id, "models": list(settings.model_pool)},
    )
    return target
