/**
 * WHY THIS SUITE EXISTS (GATEWAY-WINDOWS-COME-FROM-THE-MODEL).
 *
 * A gateway that proxies other vendors' models — Cursor, Devin, Antigravity — reports its limits badly or not
 * at all, and every one of the three used to answer the blind Claude-class assumption for every model it served.
 * So a gateway-hosted `grok-4.5`, a 500k model, was described as a 200k one, and a Gemini row as a fifth of its
 * real window. That number is not cosmetic: auto-compaction, the context panel, context promotion and the
 * overflow check all read it, so the agent compacted at two fifths of the window it had, and an operator with a
 * 256k threshold was told their threshold was larger than the model's context window.
 *
 * The class is "a gateway describes a proxied model with a window the catalog contradicts", not "grok-4.5 on
 * Cursor is wrong". So the suite works at the choke point every gateway now goes through, and then drives the
 * REAL discovery function of each of the three so a gateway that stops going through it fails here. The last
 * case is the fail-by-default half: it derives the set of gateway modules from the source tree at run time, so a
 * NEW gateway reaching for the raw assumption is red without anyone remembering to add it.
 *
 * WHAT THIS DOES NOT CATCH. Bundled rows already shipped in `models.json` for these providers were generated by
 * a discovery run that predates the resolver, so a stale window can still sit in the bundled data until the next
 * `bun run gen:models`. At runtime discovery outranks the bundled row for these providers, which is why the
 * operator sees the fix before the regen.
 */

import { afterAll, beforeAll, describe, expect, it } from "bun:test";
import * as http2 from "node:http2";
import * as path from "node:path";
import { create, toBinary } from "@bufbuild/protobuf";
import { moduleSpecifiersIn } from "@veyyon/utils/module-reach";
// Import from source, not the package specifier: the workspace `node_modules` copy resolves to the primary
// checkout, not this worktree.
import { fetchAntigravityDiscoveryModels } from "../src/discovery/antigravity";
import { fetchCursorUsableModels } from "../src/discovery/cursor";
import { GetUsableModelsResponseSchema, ModelDetailsSchema } from "../src/discovery/cursor-gen/agent_pb";
import {
	AGENT_GATEWAY_DEFAULT_CONTEXT_WINDOW,
	AGENT_GATEWAY_DEFAULT_MAX_TOKENS,
} from "../src/discovery/default-limits";
import { fetchDevinModels } from "../src/discovery/devin";
import { GetCliModelConfigsResponseSchema } from "../src/discovery/devin-gen/exa/api_server_pb/api_server_pb";
import { ClientModelConfigSchema } from "../src/discovery/devin-gen/exa/codeium_common_pb/codeium_common_pb";
import { gatewayContextWindow, gatewayMaxTokens, gatewayModelReference } from "../src/discovery/gateway-limits";
import { getBundledModel } from "../src/models";

/**
 * The corpus is read out of the bundled catalog rather than written down: these are the numbers the catalog
 * itself publishes for these models, so the assertions cannot drift from the data they are about. A missing row
 * throws here rather than turning every case below into a comparison against `undefined`.
 */
function catalogWindow(provider: string, id: string): number {
	const contextWindow = getBundledModel(provider, id)?.contextWindow;
	if (typeof contextWindow !== "number") {
		throw new Error(`the bundled catalog publishes no context window for ${provider}/${id}`);
	}
	return contextWindow;
}

const GROK_45_WINDOW = catalogWindow("xai", "grok-4.5");
const GEMINI_3_PRO_WINDOW = catalogWindow("google", "gemini-3-pro-preview");

describe("a gateway model's window comes from the model, not from the gateway", () => {
	/** The corpus itself: without these two rows the cases below would be asserting nothing. */
	it("reads two known windows out of the bundled catalog", () => {
		expect(GROK_45_WINDOW).toBeGreaterThan(AGENT_GATEWAY_DEFAULT_CONTEXT_WINDOW);
		expect(GEMINI_3_PRO_WINDOW).toBeGreaterThan(AGENT_GATEWAY_DEFAULT_CONTEXT_WINDOW);
	});

	/** What the gateway reported is still the first answer: it is the only party that knows about the proxy. */
	it("keeps a reported window over everything else", () => {
		expect(gatewayContextWindow("grok-4.5", 131_072)).toBe(131_072);
	});

	/**
	 * A reported zero is "not told" rather than a real limit. A zero window would make auto-compaction fire
	 * before any turn began.
	 */
	it("treats a reported zero, a negative and a NaN as not told", () => {
		for (const reported of [0, -1, Number.NaN, Number.POSITIVE_INFINITY]) {
			expect(gatewayContextWindow("grok-4.5", reported)).toBe(GROK_45_WINDOW);
		}
	});

	/** The headline: an unreported window resolves to what the catalog knows about that model. */
	it("answers with the catalog's window when the gateway reports none", () => {
		expect(gatewayContextWindow("grok-4.5")).toBe(GROK_45_WINDOW);
		expect(gatewayContextWindow("gemini-3-pro")).toBe(GEMINI_3_PRO_WINDOW);
	});

	/**
	 * An effort-tiered id is the base model at a fixed effort. The tier changes how the model thinks, never how
	 * much context it has, and these ids are exactly what Cursor serves (`grok-4.5-medium` is the row from the
	 * report that came back as 200k).
	 */
	it("resolves an effort-tiered id through its base model", () => {
		for (const id of ["grok-4.5-medium", "grok-4.5-high", "grok-4.5-low"]) {
			expect(gatewayContextWindow(id), id).toBe(GROK_45_WINDOW);
		}
	});

	/** A model the catalog has never heard of has no evidence either way, so the floor stands. */
	it("falls to the gateway assumption only for an unidentifiable id", () => {
		expect(gatewayModelReference("totally-unknown-model-xyz")).toBeUndefined();
		expect(gatewayContextWindow("totally-unknown-model-xyz")).toBe(AGENT_GATEWAY_DEFAULT_CONTEXT_WINDOW);
	});

	/**
	 * The output cap is not symmetric with the window on purpose. A vendor's own cap is not a promise about the
	 * proxy, and a request asking for more output than the gateway will produce is refused outright by some of
	 * them rather than clamped, so a catalog-derived cap never exceeds the gateway assumption. A cap the gateway
	 * itself reported IS a statement about the proxy and is taken as given.
	 */
	it("never lifts the output cap above the gateway assumption from catalog data", () => {
		for (const id of ["grok-4.5", "gemini-3-pro", "grok-4.5-medium", "totally-unknown-model-xyz"]) {
			expect(gatewayMaxTokens(id), id).toBeLessThanOrEqual(AGENT_GATEWAY_DEFAULT_MAX_TOKENS);
		}
		expect(gatewayMaxTokens("grok-4.5", 96_000)).toBe(96_000);
	});
});

describe("each gateway's real discovery path resolves the window", () => {
	// Cursor talks HTTP/2 directly rather than through an injectable fetch, so it needs a real server.
	let cursorServer: http2.Http2Server | undefined;
	let cursorBaseUrl = "";

	beforeAll(async () => {
		const response = create(GetUsableModelsResponseSchema, {
			models: ["grok-4.5", "grok-4.5-medium", "totally-unknown-model-xyz"].map(modelId =>
				create(ModelDetailsSchema, { modelId }),
			),
		});
		const payload = Buffer.from(toBinary(GetUsableModelsResponseSchema, response));
		const server = http2.createServer();
		server.on("stream", (stream: http2.ServerHttp2Stream, headers: http2.IncomingHttpHeaders) => {
			stream.on("data", () => {});
			stream.on("end", () => {
				if (headers[":path"] !== "/agent.v1.AgentService/GetUsableModels") {
					stream.respond({ ":status": 404 });
					stream.end();
					return;
				}
				stream.respond({ ":status": 200, "content-type": "application/proto" });
				stream.end(payload);
			});
		});
		const { promise, resolve } = Promise.withResolvers<void>();
		server.listen(0, "127.0.0.1", () => resolve());
		await promise;
		const address = server.address();
		if (!address || typeof address === "string") throw new Error("http2 fixture server bound no tcp port");
		cursorServer = server;
		cursorBaseUrl = `http://127.0.0.1:${address.port}`;
	});

	afterAll(() => {
		cursorServer?.close();
	});

	/**
	 * Cursor reports NO limits at all, and it is the provider from the report: `grok-4.5-medium` came back as a
	 * 200k model. Both the plain and the effort-tiered id have to land on the real window, and an unidentifiable
	 * id still has to land on the floor — a resolver that answered the floor for everything would pass half of
	 * this test.
	 */
	it("gives a Cursor-proxied grok-4.5 its real window, tier included", async () => {
		const models = await fetchCursorUsableModels({ apiKey: "test-key", baseUrl: cursorBaseUrl });
		const byId = new Map((models ?? []).map(model => [model.id, model]));
		expect(byId.get("grok-4.5")?.contextWindow).toBe(GROK_45_WINDOW);
		expect(byId.get("grok-4.5-medium")?.contextWindow).toBe(GROK_45_WINDOW);
		expect(byId.get("totally-unknown-model-xyz")?.contextWindow).toBe(AGENT_GATEWAY_DEFAULT_CONTEXT_WINDOW);
	});

	/**
	 * Antigravity's limit fields are frequently absent, so the same rule applies per row: a silent row resolves
	 * from the catalog, a row that reports keeps its own number.
	 */
	it("resolves a silent Antigravity row and leaves a reported one alone", async () => {
		const models = await fetchAntigravityDiscoveryModels({
			token: "test-token",
			endpoint: "https://antigravity.example",
			fetcher: (async () =>
				new Response(
					JSON.stringify({
						models: {
							"grok-4.5": { displayName: "Grok 4.5" },
							"gemini-3-pro": { displayName: "Gemini 3 Pro", maxTokens: 131_072 },
							"totally-unknown-model-xyz": { displayName: "Unknown" },
						},
					}),
					{ status: 200, headers: { "Content-Type": "application/json" } },
				)) as unknown as typeof globalThis.fetch,
		});
		const byId = new Map((models ?? []).map(model => [model.id, model]));
		expect(byId.get("grok-4.5")?.contextWindow).toBe(GROK_45_WINDOW);
		expect(byId.get("gemini-3-pro")?.contextWindow).toBe(131_072);
		expect(byId.get("totally-unknown-model-xyz")?.contextWindow).toBe(AGENT_GATEWAY_DEFAULT_CONTEXT_WINDOW);
	});

	/**
	 * Devin reports one number that has to serve as both, so a zero there means it said nothing at all. The
	 * output cap stays at or below the gateway assumption even when the window is half a megabyte: asking a
	 * gateway for that much output is refused outright by some of them.
	 */
	it("resolves a Devin row that reports no tokens, and keeps its output cap sane", async () => {
		const response = create(GetCliModelConfigsResponseSchema, {
			clientModelConfigs: [
				create(ClientModelConfigSchema, { modelUid: "grok-4.5", label: "Grok 4.5", maxTokens: 0 }),
				create(ClientModelConfigSchema, { modelUid: "swe-1-6", label: "SWE 1.6", maxTokens: 131_072 }),
			],
		});
		const payload = toBinary(GetCliModelConfigsResponseSchema, response);
		const models = await fetchDevinModels({
			apiKey: "test-token",
			baseUrl: "https://devin.example",
			fetch: (async () =>
				new Response(payload, {
					status: 200,
					headers: { "Content-Type": "application/proto" },
				})) as unknown as typeof globalThis.fetch,
		});
		const byId = new Map((models ?? []).map(model => [model.id, model]));
		expect(byId.get("grok-4.5")?.contextWindow).toBe(GROK_45_WINDOW);
		expect(byId.get("grok-4.5")?.maxTokens).toBeLessThanOrEqual(AGENT_GATEWAY_DEFAULT_MAX_TOKENS);
		expect(byId.get("swe-1-6")?.contextWindow).toBe(131_072);
	});
});

describe("every gateway module goes through the resolver", () => {
	const DISCOVERY = path.resolve(import.meta.dir, "../src/discovery");

	/**
	 * The fail-by-default half. The set of gateway modules is derived from the tree at run time — any module
	 * under `src/discovery/` that reaches the shared assumption at all — so a NEW gateway that imports
	 * `./default-limits` directly and answers 200k for every model it proxies turns this red without anyone
	 * having to remember this file exists. `gateway-limits.ts` is the one module allowed to read the pair; it is
	 * the resolver.
	 */
	it("lets nothing but the resolver read the raw assumption", async () => {
		const offenders: string[] = [];
		let reachedTheResolver = 0;
		for (const file of [...new Bun.Glob("**/*.ts").scanSync(DISCOVERY)].sort()) {
			if (file === "default-limits.ts" || file === "gateway-limits.ts") continue;
			const specifiers = moduleSpecifiersIn(await Bun.file(path.join(DISCOVERY, file)).text());
			if (specifiers.includes("./default-limits")) offenders.push(file);
			if (specifiers.includes("./gateway-limits")) reachedTheResolver++;
		}

		expect(offenders).toEqual([]);
		// Non-vacuity: the three known gateways route through it, so a broken glob cannot satisfy the ratchet by
		// reading nothing.
		expect(reachedTheResolver).toBeGreaterThanOrEqual(3);
	});
});
