// AUTOGENERATED -- managed by scripts/embed-mupdf-wasm.ts. Do not edit by hand.
//
// Compiled single-file binaries cannot let mupdf resolve its `mupdf-wasm.wasm`
// sibling from the read-only bunfs, and mupdf's top-level await is incompatible
// with bytecode compilation, so the binary build (scripts/build-binary.ts and
// scripts/ci-release-build-binaries.ts) regenerates this module to embed the
// wasm bytes plus mupdf's JS modules via `with { type: "file" }`. Source
// checkouts, `bun test`, and the npm `dist/cli.js` bundle keep mupdf external
// and load everything from node_modules, so this placeholder returns undefined
// and the build resets back to it afterward.

/** Embedded mupdf JS module assets, materialized to a cache dir at runtime. */
export interface EmbeddedMupdfModuleFiles {
	/** mupdf package version the assets were embedded from (cache key). */
	version: string;
	/** Embedded-asset path of `mupdf/dist/mupdf.js`. */
	mupdfJs: string;
	/** Embedded-asset path of `mupdf/dist/mupdf-wasm.js`. */
	mupdfWasmJs: string;
}

export function loadEmbeddedMupdfWasm(): Uint8Array | undefined {
	return undefined;
}

export function loadEmbeddedMupdfModuleFiles(): EmbeddedMupdfModuleFiles | undefined {
	return undefined;
}
