// AUTOGENERATED -- managed by scripts/embed-mupdf-wasm.ts. Do not edit or commit.
import { readFileSync } from "node:fs";
import mupdfJsPath from "./mupdf-embedded.js" with { type: "file" };
import mupdfWasmJsPath from "./mupdf-wasm-embedded.js" with { type: "file" };
import wasmPath from "./mupdf-wasm.wasm" with { type: "file" };

export interface EmbeddedMupdfModuleFiles {
	version: string;
	mupdfJs: string;
	mupdfWasmJs: string;
}

export function loadEmbeddedMupdfWasm(): Uint8Array | undefined {
	return readFileSync(wasmPath);
}

export function loadEmbeddedMupdfModuleFiles(): EmbeddedMupdfModuleFiles | undefined {
	return { version: "1.28.0", mupdfJs: mupdfJsPath, mupdfWasmJs: mupdfWasmJsPath };
}
