// AUTOGENERATED -- managed by scripts/embed-mupdf-wasm.ts. Do not edit by hand. Compiled single-file binaries cannot let mupdf resolve its `mupdf-wasm.wasm`

/** Embedded mupdf JS module assets, materialized to a cache dir at runtime. */
export interface EmbeddedMupdfModuleFiles {
	/** mupdf package version the assets were embedded from (cache key). */
	version: string;
	/** Embedded-asset path of `mupdf/dist/mupdf.js`. */
	mupdfJs: string;
	/** Embedded-asset path of `mupdf/dist/mupdf-wasm.js`. */
	mupdfWasmJs: string;
}

export function loadEmbeddedMupdfWasm(): Uint8Array | undefined {
	return undefined;
}

export function loadEmbeddedMupdfModuleFiles(): EmbeddedMupdfModuleFiles | undefined {
	return undefined;
}
