import { lazyNativeClass, lazyNativeFn } from "./loader-state.js";

/**
 * Native addon entrypoint.
 *
 * Hand-written surface area: the two lazy-accessor imports. Everything else in
 * this file (the surface-area `export const` block between MARKER_START
 * and MARKER_END) is rewritten by `packages/natives/scripts/gen-enums.ts`
 * after `napi build` regenerates `index.d.ts`.
 *
 * The addon loads LAZILY: each class/function export is a thin accessor
 * (`lazyNativeClass` / `lazyNativeFn`) that calls `loadNative()` only on first
 * use, never at import. So importing this module for its types, its enum
 * values, or a bare symbol reference needs no built `.node` — pure
 * registry/schema/doc-truth imports whose graph merely mentions
 * `@veyyon/natives` stay native-free (DOCS-NATIVES-1). The first real call/`new`
 * still loads-or-throws loudly (deferral, not a silent fallback — Law 10).
 *
 * Loader logic lives in `./loader-state.js` so the pure helpers stay
 * unit-testable without triggering AVX2 detection or filesystem probes on
 * import. Types are auto-generated by napi-rs in `./index.d.ts`.
 */

// --- generated native exports (do not edit) ---
// classes
export const MacAppearanceObserver = lazyNativeClass("MacAppearanceObserver");
export const MacOSPowerAssertion = lazyNativeClass("MacOSPowerAssertion");
export const Process = lazyNativeClass("Process");
export const PtySession = lazyNativeClass("PtySession");
export const Shell = lazyNativeClass("Shell");

// functions
export const __veyyonInstallTokioRuntime = lazyNativeFn("__veyyonInstallTokioRuntime");
export const __veyyonNativesV1_0_17 = lazyNativeFn("__veyyonNativesV1_0_17");
export const astEdit = lazyNativeFn("astEdit");
export const astGrep = lazyNativeFn("astGrep");
export const astMatch = lazyNativeFn("astMatch");
export const blockRangeAt = lazyNativeFn("blockRangeAt");
export const copyToClipboard = lazyNativeFn("copyToClipboard");
export const countTokens = lazyNativeFn("countTokens");
export const detectMacOSAppearance = lazyNativeFn("detectMacOSAppearance");
export const enclosingBlockBoundaries = lazyNativeFn("enclosingBlockBoundaries");
export const encodeSixel = lazyNativeFn("encodeSixel");
export const executeShell = lazyNativeFn("executeShell");
export const extractSegments = lazyNativeFn("extractSegments");
export const fuzzyFind = lazyNativeFn("fuzzyFind");
export const getSupportedLanguages = lazyNativeFn("getSupportedLanguages");
export const getWorkProfile = lazyNativeFn("getWorkProfile");
export const glob = lazyNativeFn("glob");
export const grep = lazyNativeFn("grep");
export const hasMatch = lazyNativeFn("hasMatch");
export const highlightCode = lazyNativeFn("highlightCode");
export const htmlToMarkdown = lazyNativeFn("htmlToMarkdown");
export const invalidateFsScanCache = lazyNativeFn("invalidateFsScanCache");
export const isoBackend = lazyNativeFn("isoBackend");
export const isoDiff = lazyNativeFn("isoDiff");
export const isoIsUnavailableError = lazyNativeFn("isoIsUnavailableError");
export const isoProbe = lazyNativeFn("isoProbe");
export const isoResolve = lazyNativeFn("isoResolve");
export const isoStart = lazyNativeFn("isoStart");
export const isoStop = lazyNativeFn("isoStop");
export const listWorkspace = lazyNativeFn("listWorkspace");
export const matchesKey = lazyNativeFn("matchesKey");
export const matchesKittySequence = lazyNativeFn("matchesKittySequence");
export const matchesLegacySequence = lazyNativeFn("matchesLegacySequence");
export const parseKey = lazyNativeFn("parseKey");
export const parseKittySequence = lazyNativeFn("parseKittySequence");
export const readImageFromClipboard = lazyNativeFn("readImageFromClipboard");
export const search = lazyNativeFn("search");
export const setHangulCompatJamoWidthOverride = lazyNativeFn("setHangulCompatJamoWidthOverride");
export const sliceWithWidth = lazyNativeFn("sliceWithWidth");
export const summarizeCode = lazyNativeFn("summarizeCode");
export const supportsLanguage = lazyNativeFn("supportsLanguage");
export const truncateToWidth = lazyNativeFn("truncateToWidth");
export const visibleWidth = lazyNativeFn("visibleWidth");
export const wrapTextWithAnsi = lazyNativeFn("wrapTextWithAnsi");

// string/numeric enums (napi-rs string_enum produces TS-only const enum)
export const AstMatchStrictness = {
	Cst: "cst",
	Smart: "smart",
	Ast: "ast",
	Relaxed: "relaxed",
	Signature: "signature",
	Template: "template",
};
export const Ellipsis = {
	Unicode: 0,
	Ascii: 1,
	Omit: 2,
};
export const Encoding = {
	O200kBase: "O200kBase",
	Cl100kBase: "Cl100kBase",
};
export const FileType = {
	File: 1,
	Dir: 2,
	Symlink: 3,
};
export const GrepOutputMode = {
	Content: "content",
	Count: "count",
	FilesWithMatches: "filesWithMatches",
};
export const IsoBackendKind = {
	Apfs: 0,
	Btrfs: 1,
	Zfs: 2,
	LinuxReflink: 3,
	Overlayfs: 4,
	WindowsBlockClone: 5,
	Projfs: 6,
	Rcopy: 7,
};
export const IsoChangeKind = {
	Added: 0,
	Modified: 1,
	Removed: 2,
};
export const KeyEventType = {
	Press: 1,
	Repeat: 2,
	Release: 3,
};
export const MacOSAppearance = {
	Dark: "dark",
	Light: "light",
};
export const ProcessStatus = {
	Running: "running",
	Exited: "exited",
};
// --- end generated native exports ---
