/**
 * The ONE owner of / menu grouping: every builtin command's category, keyed by
 * name. The unfiltered / menu renders these as group headers (SelectItem.group
 * via SlashCommand.category); header order follows the first appearance of
 * each category in registry order. A builtin missing here fails the
 * registry-coherence test, so new commands must be categorized at birth.
 */
export const BUILTIN_SLASH_COMMAND_CATEGORIES: Readonly<Record<string, string>> = {
	settings: "setup",
	secret: "setup",
	statusline: "setup",
	welcome: "setup",
	lsp: "setup",
	setup: "setup",
	providers: "setup",
	account: "setup",
	login: "setup",
	logout: "setup",
	profile: "setup",
	mcp: "setup",
	ssh: "setup",
	extensions: "setup",
	plugins: "setup",
	"reload-plugins": "setup",
	trust: "setup",
	plan: "modes",
	"plan-review": "modes",
	vibe: "modes",
	goal: "modes",
	"guided-goal": "modes",
	loop: "modes",
	queue: "modes",
	prewalk: "modes",
	fast: "modes",
	permissions: "modes",
	yolo: "modes",
	"cpu-limit": "modes",
	pause: "modes",
	model: "model",
	switch: "model",
	effort: "model",
	force: "model",
	retry: "model",
	// Beside /btw and /tan: all three act on what the conversation just said, not on the model.
	rephrase: "context",
	// Beside the model roles: the advisor IS a model role, and its knobs sit under the Model tab.
	advisor: "model",
	share: "share",
	collab: "share",
	join: "share",
	leave: "share",
	export: "share",
	dump: "share",
	copy: "share",
	browser: "workspace",
	cwd: "workspace",
	tools: "workspace",
	agents: "workspace",
	jobs: "workspace",
	usage: "workspace",
	// Beside `/usage`: both answer "what has this cost", one inline and one in a browser.
	stats: "workspace",
	todo: "context",
	context: "context",
	memory: "context",
	compact: "context",
	shake: "context",
	handoff: "context",
	btw: "context",
	tan: "context",
	session: "session",
	new: "session",
	fresh: "session",
	drop: "session",
	resume: "session",
	rename: "session",
	move: "session",
	branch: "session",
	fork: "session",
	tree: "session",
	room: "session",
	exit: "session",
	quit: "session",
	changelog: "info",
	hotkeys: "info",
	debug: "info",
	omfg: "info",
};
