/**
 * The marker a generated document carries on its first line, and the readers a sweep
 * uses to recognize one.
 *
 * A generated page used to state its provenance three paragraphs in, as prose. A
 * mechanical docs sweep edited it twice in one session, and both edits were recovered
 * only because someone remembered the rule. A marker on the FIRST line is what a script
 * reads before it writes: an HTML comment, so mdBook renders nothing for a reader.
 */

/** Everything before the generator path in the marker. */
const MARKER_OPEN = "<!-- generated by ";
/** Everything after it. */
const MARKER_CLOSE = " -- do not edit by hand -->";

/** The exact first line for a document rendered by `generator`, e.g. `scripts/gen-x.ts`. */
export function generatedDocMarker(generator: string): string {
	return `${MARKER_OPEN}${generator}${MARKER_CLOSE}`;
}

/**
 * The generator named by `text`'s first line, or null when the document is authored by
 * hand. A sweep asks this instead of carrying a list of paths, which is the list that
 * goes stale the day a second generator ships.
 */
export function generatedDocGenerator(text: string): string | null {
	const firstLine = text.slice(0, text.indexOf("\n") === -1 ? text.length : text.indexOf("\n"));
	if (!firstLine.startsWith(MARKER_OPEN) || !firstLine.endsWith(MARKER_CLOSE)) return null;
	const generator = firstLine.slice(MARKER_OPEN.length, firstLine.length - MARKER_CLOSE.length).trim();
	return generator.length > 0 ? generator : null;
}

/**
 * `body` with the marker as its first line. Prepending here rather than in each
 * generator's template is what makes the marker unforgettable: a generator that renders
 * a document through this function cannot ship one without it.
 */
export function withGeneratedDocMarker(generator: string, body: string): string {
	const existing = generatedDocGenerator(body);
	if (existing !== null) {
		throw new Error(`body already carries a generated marker naming ${existing}`);
	}
	return `${generatedDocMarker(generator)}\n${body}`;
}
