import { SUB_CELL_BAR_RAMP, type SubCellBarRamp } from "@veyyon/tui/sub-cell-bar";

export type SymbolPreset = "unicode" | "nerd" | "ascii";

export type SymbolKey =
	| "status.success"
	| "status.error"
	| "status.warning"
	| "status.info"
	| "status.pending"
	| "status.disabled"
	| "status.enabled"
	| "status.running"
	| "status.connecting"
	| "status.active"
	| "status.shadowed"
	| "status.aborted"
	| "status.done"
	| "nav.cursor"
	| "nav.selected"
	| "nav.expand"
	| "nav.collapse"
	| "nav.back"
	| "nav.prev"
	| "nav.next"
	| "tree.branch"
	| "tree.last"
	| "tree.vertical"
	| "tree.horizontal"
	| "tree.hook"
	| "boxRound.topLeft"
	| "boxRound.topRight"
	| "boxRound.bottomLeft"
	| "boxRound.bottomRight"
	| "boxRound.horizontal"
	| "boxRound.vertical"
	| "boxSharp.topLeft"
	| "boxSharp.topRight"
	| "boxSharp.bottomLeft"
	| "boxSharp.bottomRight"
	| "boxSharp.horizontal"
	| "boxSharp.vertical"
	| "boxSharp.cross"
	| "boxSharp.teeDown"
	| "boxSharp.teeUp"
	| "boxSharp.teeRight"
	| "boxSharp.teeLeft"
	| "sep.powerline"
	| "sep.powerlineThin"
	| "sep.powerlineLeft"
	| "sep.powerlineRight"
	| "sep.powerlineThinLeft"
	| "sep.powerlineThinRight"
	| "sep.block"
	| "sep.space"
	| "sep.asciiLeft"
	| "sep.asciiRight"
	| "sep.dot"
	| "sep.slash"
	| "sep.pipe"
	| "icon.model"
	| "icon.plan"
	| "icon.prewalk"
	| "icon.goal"
	| "icon.pause"
	| "icon.loop"
	| "icon.folder"
	| "icon.worktree"
	| "icon.search"
	| "icon.scratchFolder"
	| "icon.file"
	| "icon.git"
	| "icon.branch"
	| "icon.pr"
	| "icon.tokens"
	| "icon.context"
	| "icon.cost"
	| "icon.time"
	| "icon.pi"
	| "icon.ghost"
	| "icon.agents"
	| "icon.unread"
	| "icon.job"
	| "icon.cache"
	| "icon.cacheMiss"
	| "icon.input"
	| "icon.output"
	| "icon.throughput"
	| "icon.host"
	| "icon.profile"
	| "icon.session"
	| "icon.package"
	| "icon.warning"
	| "icon.rewind"
	| "icon.auto"
	| "icon.fast"
	| "icon.extensionSkill"
	| "icon.extensionTool"
	| "icon.extensionSlashCommand"
	| "icon.extensionMcp"
	| "icon.extensionRule"
	| "icon.extensionHook"
	| "icon.extensionPrompt"
	| "icon.extensionContextFile"
	| "icon.extensionInstruction"
	| "icon.mic"
	| "icon.camera"
	| "thinking.minimal"
	| "thinking.low"
	| "thinking.medium"
	| "thinking.high"
	| "thinking.xhigh"
	| "thinking.max"
	| "thinking.autoPending"
	| "checkbox.checked"
	| "checkbox.unchecked"
	| "checkbox.progress"
	| "radio.selected"
	| "radio.unselected"
	| "format.bullet"
	| "format.dash"
	| "format.bracketLeft"
	| "format.bracketRight"
	| "md.quoteBorder"
	| "md.hrChar"
	| "md.bullet"
	| "md.colorSwatch"
	| "advisor.rail"
	| "block.rail"
	| "lang.default"
	| "lang.typescript"
	| "lang.javascript"
	| "lang.python"
	| "lang.rust"
	| "lang.go"
	| "lang.java"
	| "lang.c"
	| "lang.cpp"
	| "lang.csharp"
	| "lang.ruby"
	| "lang.julia"
	| "lang.php"
	| "lang.swift"
	| "lang.kotlin"
	| "lang.shell"
	| "lang.html"
	| "lang.css"
	| "lang.json"
	| "lang.yaml"
	| "lang.markdown"
	| "lang.sql"
	| "lang.docker"
	| "lang.lua"
	| "lang.text"
	| "lang.env"
	| "lang.toml"
	| "lang.xml"
	| "lang.ini"
	| "lang.conf"
	| "lang.log"
	| "lang.csv"
	| "lang.tsv"
	| "lang.image"
	| "lang.pdf"
	| "lang.archive"
	| "lang.binary"
	| "tab.appearance"
	| "tab.model"
	| "tab.interaction"
	| "tab.resources"
	| "tab.context"
	| "tab.rules"
	| "tab.files"
	| "tab.shell"
	| "tab.tools"
	| "tab.memory"
	| "tab.tasks"
	| "tab.subagents"
	| "tab.providers"
	| "tab.global"
	| "tab.experimental"
	| "tool.write"
	| "tool.edit"
	| "tool.bash"
	| "tool.ssh"
	| "tool.lsp"
	| "tool.gh"
	| "tool.webSearch"
	| "tool.exa"
	| "tool.browser"
	| "tool.eval"
	| "tool.debug"
	| "tool.mcp"
	| "tool.job"
	| "tool.launch"
	| "tool.task"
	| "tool.todo"
	| "tool.memory"
	| "tool.ask"
	| "tool.resolve"
	| "tool.review"
	| "tool.inspectImage"
	| "tool.goal"
	| "tool.irc"
	| "tool.delete"
	| "tool.move";

export type SymbolMap = Record<SymbolKey, string>;

export const UNICODE_SYMBOLS: SymbolMap = {
	"status.success": "✓",
	"status.error": "✗",
	"status.warning": "!",
	"status.info": "i",
	"status.pending": "⋯",
	"status.disabled": "⊗",
	"status.enabled": "▪",
	"status.running": "◐",
	"status.connecting": "◦",
	"status.active": "●",
	"status.shadowed": "▫",
	"status.aborted": "∎",
	"status.done": "▪",
	"nav.cursor": "›",
	"nav.selected": "›",
	"nav.expand": "▸",
	"nav.collapse": "▾",
	"nav.back": "⟵",
	"nav.prev": "◂",
	"nav.next": "▸",
	"tree.branch": "├─",
	"tree.last": "└─",
	"tree.vertical": "│",
	"tree.horizontal": "─",
	"tree.hook": "└",
	"boxRound.topLeft": "╭",
	"boxRound.topRight": "╮",
	"boxRound.bottomLeft": "╰",
	"boxRound.bottomRight": "╯",
	"boxRound.horizontal": "─",
	"boxRound.vertical": "│",
	"boxSharp.topLeft": "┌",
	"boxSharp.topRight": "┐",
	"boxSharp.bottomLeft": "└",
	"boxSharp.bottomRight": "┘",
	"boxSharp.horizontal": "─",
	"boxSharp.vertical": "│",
	"boxSharp.cross": "┼",
	"boxSharp.teeDown": "┬",
	"boxSharp.teeUp": "┴",
	"boxSharp.teeRight": "├",
	"boxSharp.teeLeft": "┤",
	"sep.powerline": "▕",
	"sep.powerlineThin": "┆",
	"sep.powerlineLeft": "▶",
	"sep.powerlineRight": "◀",
	"sep.powerlineThinLeft": ">",
	"sep.powerlineThinRight": "<",
	"sep.block": "▌",
	"sep.space": " ",
	"sep.asciiLeft": ">",
	"sep.asciiRight": "<",
	"sep.dot": " · ",
	"sep.slash": " / ",
	"sep.pipe": " │ ",
	"icon.model": "",
	"icon.plan": "",
	"icon.prewalk": "",
	"icon.goal": "",
	"icon.pause": "‖",
	"icon.loop": "↻",
	"icon.folder": "",
	"icon.worktree": "◫",
	"icon.search": "⌕",
	"icon.scratchFolder": "▫",
	"icon.file": "▤",
	"icon.git": "",
	"icon.branch": "",
	"icon.pr": "",
	"icon.tokens": "",
	"icon.context": "",
	"icon.cost": "",
	"icon.time": "",
	"icon.pi": "",
	"icon.ghost": "",
	"icon.agents": "",
	"icon.unread": "✉",
	"icon.job": "",
	"icon.cache": "",
	"icon.cacheMiss": "⊘",
	"icon.input": "↓",
	"icon.output": "↑",
	"icon.throughput": "",
	"icon.host": "",
	"icon.profile": "",
	"icon.session": "",
	"icon.package": "",
	"icon.warning": "!",
	"icon.rewind": "↶",
	"icon.auto": "∞",
	"icon.fast": "",
	"icon.extensionSkill": "*",
	"icon.extensionTool": "",
	"icon.extensionSlashCommand": "⌘",
	"icon.extensionMcp": "",
	"icon.extensionRule": "",
	"icon.extensionHook": "",
	"icon.extensionPrompt": "¶",
	"icon.extensionContextFile": "",
	"icon.extensionInstruction": "",
	"icon.mic": "",
	"icon.camera": "",
	"thinking.minimal": "min",
	"thinking.low": "low",
	"thinking.medium": "med",
	"thinking.high": "high",
	"thinking.xhigh": "xhigh",
	"thinking.max": "max",
	"thinking.autoPending": "◐",
	"checkbox.checked": "■",
	"checkbox.unchecked": "□",
	"checkbox.progress": "◧",
	"radio.selected": "▣",
	"radio.unselected": "□",
	"format.bullet": "•",
	"format.dash": "—",
	"format.bracketLeft": "⟦",
	"format.bracketRight": "⟧",
	"md.quoteBorder": "▏",
	"md.hrChar": "─",
	"md.bullet": "•",
	"md.colorSwatch": "■",
	"advisor.rail": "▎",
	"block.rail": "▏",
	"lang.default": "",
	"lang.typescript": "",
	"lang.javascript": "",
	"lang.python": "",
	"lang.rust": "",
	"lang.go": "",
	"lang.java": "",
	"lang.c": "",
	"lang.cpp": "",
	"lang.csharp": "",
	"lang.ruby": "",
	"lang.julia": "",
	"lang.php": "",
	"lang.swift": "",
	"lang.kotlin": "",
	"lang.shell": "",
	"lang.html": "",
	"lang.css": "",
	"lang.json": "",
	"lang.yaml": "",
	"lang.markdown": "",
	"lang.sql": "",
	"lang.docker": "",
	"lang.lua": "",
	"lang.text": "",
	"lang.env": "",
	"lang.toml": "",
	"lang.xml": "",
	"lang.ini": "",
	"lang.conf": "",
	"lang.log": "",
	"lang.csv": "",
	"lang.tsv": "",
	"lang.image": "",
	"lang.pdf": "",
	"lang.archive": "",
	"lang.binary": "",
	"tab.appearance": "",
	"tab.model": "",
	"tab.interaction": "",
	"tab.resources": "",
	"tab.context": "",
	"tab.rules": "",
	"tab.files": "",
	"tab.shell": "",
	"tab.tools": "",
	"tab.memory": "",
	"tab.tasks": "",
	"tab.subagents": "",
	"tab.providers": "",
	"tab.global": "",
	"tab.experimental": "",
	"tool.write": "❐",
	"tool.edit": "✎",
	"tool.bash": ">",
	"tool.ssh": "⇄",
	"tool.lsp": "",
	"tool.gh": "◈",
	"tool.webSearch": "⌕",
	"tool.exa": "",
	"tool.browser": "N",
	"tool.eval": "▶",
	"tool.debug": "",
	"tool.mcp": "",
	"tool.job": "",
	"tool.launch": "",
	"tool.task": "⇶",
	"tool.todo": "",
	"tool.memory": "R",
	"tool.ask": "?",
	"tool.resolve": "✓",
	"tool.review": "◉",
	"tool.inspectImage": "",
	"tool.goal": "◎",
	"tool.irc": "",
	"tool.delete": "",
	"tool.move": "",
};

export const NERD_SYMBOLS: SymbolMap = {
	"status.success": "\uf00c",
	"status.error": "\uf00d",
	"status.warning": "\uf12a",
	"status.info": "\uf129",
	"status.pending": "\uf254",
	"status.disabled": "\uf05e",
	"status.enabled": "\uf111",
	"status.running": "\uf110",
	"status.connecting": "\uf10c",
	"status.active": "\uf111",
	"status.shadowed": "\uf10c",
	"status.aborted": "\uf04d",
	"status.done": "•",
	"nav.cursor": "\uf054",
	"nav.selected": "\uf178",
	"nav.expand": "\uf0da",
	"nav.collapse": "\uf0d7",
	"nav.prev": "\uf0d9",
	"nav.next": "\uf0da",
	"nav.back": "\uf060",
	"tree.branch": "├─",
	"tree.last": "└─",
	"tree.vertical": "│",
	"tree.horizontal": "─",
	"tree.hook": "└",
	"boxRound.topLeft": "╭",
	"boxRound.topRight": "╮",
	"boxRound.bottomLeft": "╰",
	"boxRound.bottomRight": "╯",
	"boxRound.horizontal": "─",
	"boxRound.vertical": "│",
	"boxSharp.topLeft": "┌",
	"boxSharp.topRight": "┐",
	"boxSharp.bottomLeft": "└",
	"boxSharp.bottomRight": "┘",
	"boxSharp.horizontal": "─",
	"boxSharp.vertical": "│",
	"boxSharp.cross": "┼",
	"boxSharp.teeDown": "┬",
	"boxSharp.teeUp": "┴",
	"boxSharp.teeRight": "├",
	"boxSharp.teeLeft": "┤",
	"sep.powerline": "\ue0b0",
	"sep.powerlineThin": "\ue0b1",
	"sep.powerlineLeft": "\ue0b0",
	"sep.powerlineRight": "\ue0b2",
	"sep.powerlineThinLeft": "\ue0b1",
	"sep.powerlineThinRight": "\ue0b3",
	"sep.block": "█",
	"sep.space": " ",
	"sep.asciiLeft": ">",
	"sep.asciiRight": "<",
	"sep.dot": " · ",
	"sep.slash": "\ue0bb",
	"sep.pipe": "\ue0b3",
	"icon.model": "\uec19",
	"icon.plan": "\uf2d2",
	"icon.prewalk": "\uf29d",
	"icon.goal": "\uf140",
	"icon.pause": "\uf04c",
	"icon.loop": "\uf021",
	"icon.folder": "\uf115",
	"icon.search": "\uf002",
	"icon.scratchFolder": "\uf014",
	"icon.worktree": "\uf0e8",
	"icon.file": "\uf15b",
	"icon.git": "\uf1d3",
	"icon.branch": "\uf126",
	"icon.pr": "\uea64",
	"icon.tokens": "\ue26b",
	"icon.context": "\ue70f",
	"icon.cost": "\uf155",
	"icon.time": "\uf017",
	"icon.pi": "\ue22c",
	"icon.ghost": "\u{f02a0}",
	"icon.agents": "\uf0c0",
	"icon.unread": "\uf0e0",
	"icon.job": "\uf013",
	"icon.cache": "\uf1c0",
	"icon.cacheMiss": "\uf05e",
	"icon.input": "\uf090",
	"icon.output": "\uf08b",
	"icon.throughput": "\uf0e4",
	"icon.host": "\uf109",
	"icon.profile": "",
	"icon.session": "\uf550",
	"icon.package": "\uf487",
	"icon.warning": "\uf071",
	"icon.rewind": "\uf0e2",
	"icon.auto": "\u{f06e4}",
	"icon.fast": "\uf0e7",
	"icon.extensionSkill": "\uf0eb",
	"icon.extensionTool": "\uf0ad",
	"icon.extensionSlashCommand": "\uf120",
	"icon.extensionMcp": "\uf1e6",
	"icon.extensionRule": "\uf0e3",
	"icon.extensionHook": "\uf0c1",
	"icon.extensionPrompt": "\uf075",
	"icon.extensionContextFile": "\uf0f6",
	"icon.extensionInstruction": "\uf02d",
	"icon.mic": "\uf130",
	"icon.camera": "\uf083",
	"thinking.minimal": "\u{F0A9E} min",
	"thinking.low": "\u{F0A9F} low",
	"thinking.medium": "\u{F0AA1} med",
	"thinking.high": "\u{F0AA3} high",
	"thinking.xhigh": "\u{F0AA5} xhi",
	"thinking.max": "\u{F06D} max",
	"thinking.autoPending": "\u{F074}",
	"checkbox.checked": "\uf14a",
	"checkbox.unchecked": "\uf096",
	"checkbox.progress": "\uf146",
	"radio.selected": "\uf192",
	"radio.unselected": "\uf10c",
	"format.bullet": "\uf111",
	"format.dash": "–",
	"format.bracketLeft": "⟨",
	"format.bracketRight": "⟩",
	"md.quoteBorder": "│",
	"md.hrChar": "─",
	"md.bullet": "\uf111",
	"md.colorSwatch": "■",
	"advisor.rail": "▎",
	"block.rail": "▏",
	"lang.default": "",
	"lang.typescript": "\u{E628}",
	"lang.javascript": "\u{E60C}",
	"lang.python": "\u{E606}",
	"lang.rust": "\u{E7A8}",
	"lang.go": "\u{E627}",
	"lang.java": "\u{E738}",
	"lang.c": "\u{E61E}",
	"lang.cpp": "\u{E61D}",
	"lang.csharp": "\u{E7BC}",
	"lang.ruby": "\u{E791}",
	"lang.julia": "\u{E624}",
	"lang.php": "\u{E608}",
	"lang.swift": "\u{E755}",
	"lang.kotlin": "\u{E634}",
	"lang.shell": "\u{E795}",
	"lang.html": "\u{E736}",
	"lang.css": "\u{E749}",
	"lang.json": "\u{E60B}",
	"lang.yaml": "\u{E615}",
	"lang.markdown": "\u{E609}",
	"lang.sql": "\u{E706}",
	"lang.docker": "\u{E7B0}",
	"lang.lua": "\u{E620}",
	"lang.text": "\u{E612}",
	"lang.env": "\u{E615}",
	"lang.toml": "\u{E615}",
	"lang.xml": "\u{F05C0}",
	"lang.ini": "\u{E615}",
	"lang.conf": "\u{E615}",
	"lang.log": "\u{F0331}",
	"lang.csv": "\u{F021B}",
	"lang.tsv": "\u{F021B}",
	"lang.image": "\u{F021F}",
	"lang.pdf": "\u{F0226}",
	"lang.archive": "\u{F187}",
	"lang.binary": "\u{F019A}",
	"tab.appearance": "󰃣",
	"tab.model": "󰚩",
	"tab.interaction": "󰌌",
	"tab.resources": "\uf0e4",
	"tab.context": "󰘸",
	"tab.rules": "\u{F0A7C}",
	"tab.files": "󰈔",
	"tab.shell": "󰆍",
	"tab.tools": "󰠭",
	"tab.memory": "󰧑",
	"tab.tasks": "󰐱",
	"tab.subagents": "󰡐",
	"tab.providers": "󰖟",
	"tab.global": "\u{F01E7}",
	"tab.experimental": "\u{F0093}",
	"tool.write": "\uEA7F",
	"tool.edit": "\uEA73",
	"tool.bash": "\uEBCA",
	"tool.ssh": "\uEB3A",
	"tool.lsp": "\uEA61",
	"tool.gh": "\uEA84",
	"tool.webSearch": "\uEB01",
	"tool.exa": "\uEB68",
	"tool.browser": "\uEAAE",
	"tool.eval": "\uEBAF",
	"tool.debug": "\uEAD8",
	"tool.mcp": "\uEB2D",
	"tool.job": "\uEBA2",
	"tool.launch": "\uF135",
	"tool.task": "\uf4a0",
	"tool.todo": "\uEAB3",
	"tool.memory": "\uEACE",
	"tool.ask": "\uEAC7",
	"tool.resolve": "\uEBB1",
	"tool.review": "\uEA70",
	"tool.inspectImage": "\uEAEA",
	"tool.goal": "\uEBF8",
	"tool.irc": "\uF086",
	"tool.delete": "\uf12d",
	"tool.move": "\uf061",
};

export const ASCII_SYMBOLS: SymbolMap = {
	"status.success": "[ok]",
	"status.error": "[!!]",
	"status.warning": "[!]",
	"status.info": "[i]",
	"status.pending": "[*]",
	"status.disabled": "[ ]",
	"status.enabled": "[x]",
	"status.running": "[~]",
	"status.connecting": "o",
	"status.active": "*",
	"status.shadowed": "[/]",
	"status.aborted": "[-]",
	"status.done": "*",
	"nav.cursor": ">",
	"nav.selected": "->",
	"nav.expand": "+",
	"nav.collapse": "-",
	"nav.back": "<-",
	"nav.prev": "<",
	"nav.next": ">",
	"tree.branch": "|--",
	"tree.last": "'--",
	"tree.vertical": "|",
	"tree.horizontal": "-",
	"tree.hook": "`-",
	"boxRound.topLeft": "+",
	"boxRound.topRight": "+",
	"boxRound.bottomLeft": "+",
	"boxRound.bottomRight": "+",
	"boxRound.horizontal": "-",
	"boxRound.vertical": "|",
	"boxSharp.topLeft": "+",
	"boxSharp.topRight": "+",
	"boxSharp.bottomLeft": "+",
	"boxSharp.bottomRight": "+",
	"boxSharp.horizontal": "-",
	"boxSharp.vertical": "|",
	"boxSharp.cross": "+",
	"boxSharp.teeDown": "+",
	"boxSharp.teeUp": "+",
	"boxSharp.teeRight": "+",
	"boxSharp.teeLeft": "+",
	"sep.powerline": ">",
	"sep.powerlineThin": ">",
	"sep.powerlineLeft": ">",
	"sep.powerlineRight": "<",
	"sep.powerlineThinLeft": ">",
	"sep.powerlineThinRight": "<",
	"sep.block": "#",
	"sep.space": " ",
	"sep.asciiLeft": ">",
	"sep.asciiRight": "<",
	"sep.dot": " - ",
	"sep.slash": " / ",
	"sep.pipe": " | ",
	"icon.model": "[M]",
	"icon.plan": "plan",
	"icon.prewalk": "prewalk",
	"icon.goal": "goal",
	"icon.pause": "||",
	"icon.loop": "loop",
	"icon.folder": "[D]",
	"icon.worktree": "[wt]",
	"icon.search": "[/]",
	"icon.scratchFolder": "[T]",
	"icon.file": "[F]",
	"icon.git": "git:",
	"icon.branch": "@",
	"icon.pr": "PR",
	"icon.tokens": "tok:",
	"icon.context": "ctx:",
	"icon.cost": "$",
	"icon.time": "t:",
	"icon.pi": "pi",
	"icon.ghost": "@",
	"icon.agents": "AG",
	"icon.unread": "msg",
	"icon.job": "bg",
	"icon.output": "out:",
	"icon.throughput": "tok/s:",
	"icon.cache": "cache",
	"icon.cacheMiss": "!",
	"icon.input": "in:",
	"icon.host": "host",
	"icon.profile": "prof",
	"icon.session": "id",
	"icon.package": "[P]",
	"icon.warning": "[!]",
	"icon.rewind": "<-",
	"icon.auto": "[A]",
	"icon.fast": ">>",
	"icon.extensionSkill": "SK",
	"icon.extensionTool": "TL",
	"icon.extensionSlashCommand": "/",
	"icon.extensionMcp": "MCP",
	"icon.extensionRule": "RL",
	"icon.extensionHook": "HK",
	"icon.extensionPrompt": "PR",
	"icon.extensionContextFile": "CF",
	"icon.extensionInstruction": "IN",
	"icon.mic": "MIC",
	"icon.camera": "[o]",
	"thinking.minimal": "[min]",
	"thinking.low": "[low]",
	"thinking.medium": "[med]",
	"thinking.high": "[high]",
	"thinking.xhigh": "[xhi]",
	"thinking.max": "[max]",
	"thinking.autoPending": "[~]",
	"checkbox.checked": "[x]",
	"checkbox.unchecked": "[ ]",
	"checkbox.progress": "[~]",
	"radio.selected": "(o)",
	"radio.unselected": "( )",
	"format.bullet": "*",
	"format.dash": "-",
	"format.bracketLeft": "[",
	"format.bracketRight": "]",
	"md.quoteBorder": "|",
	"md.hrChar": "-",
	"md.bullet": "*",
	"md.colorSwatch": "[]",
	"advisor.rail": "|",
	"block.rail": "|",
	"lang.default": "code",
	"lang.typescript": "ts",
	"lang.javascript": "js",
	"lang.python": "py",
	"lang.rust": "rs",
	"lang.go": "go",
	"lang.java": "java",
	"lang.c": "c",
	"lang.cpp": "cpp",
	"lang.csharp": "cs",
	"lang.ruby": "rb",
	"lang.julia": "jl",
	"lang.php": "php",
	"lang.swift": "swift",
	"lang.kotlin": "kt",
	"lang.shell": "sh",
	"lang.html": "html",
	"lang.css": "css",
	"lang.json": "json",
	"lang.yaml": "yaml",
	"lang.markdown": "md",
	"lang.sql": "sql",
	"lang.docker": "docker",
	"lang.lua": "lua",
	"lang.text": "txt",
	"lang.env": "env",
	"lang.toml": "toml",
	"lang.xml": "xml",
	"lang.ini": "ini",
	"lang.conf": "conf",
	"lang.log": "log",
	"lang.csv": "csv",
	"lang.tsv": "tsv",
	"lang.image": "img",
	"lang.pdf": "pdf",
	"lang.archive": "zip",
	"lang.binary": "bin",
	"tab.appearance": "[A]",
	"tab.model": "[M]",
	"tab.interaction": "[I]",
	"tab.resources": "[U]",
	"tab.context": "[X]",
	"tab.rules": "[R]",
	"tab.files": "[F]",
	"tab.shell": "[S]",
	"tab.tools": "[T]",
	"tab.memory": "[Y]",
	"tab.tasks": "[K]",
	"tab.subagents": "[B]",
	"tab.providers": "[P]",
	"tab.global": "[G]",
	"tab.experimental": "[E]",
	"tool.write": "+f",
	"tool.edit": "~",
	"tool.bash": "$",
	"tool.ssh": "ssh",
	"tool.lsp": "lsp",
	"tool.gh": "gh",
	"tool.webSearch": "web",
	"tool.exa": "exa",
	"tool.browser": "[w]",
	"tool.eval": ">_",
	"tool.debug": "dbg",
	"tool.mcp": "<>",
	"tool.job": "job",
	"tool.launch": "run",
	"tool.task": ">>>",
	"tool.todo": "[x]",
	"tool.memory": "mem",
	"tool.ask": "[?]",
	"tool.resolve": "[v]",
	"tool.review": "rev",
	"tool.inspectImage": "[i]",
	"tool.goal": "(o)",
	"tool.irc": "irc",
	"tool.delete": "rm",
	"tool.move": "mv",
};

export const SYMBOL_PRESETS: Record<SymbolPreset, SymbolMap> = {
	unicode: UNICODE_SYMBOLS,
	nerd: NERD_SYMBOLS,
	ascii: ASCII_SYMBOLS,
};

export type SpinnerType = "status" | "activity" | "thinking";

export const SPINNER_FRAMES: Record<SymbolPreset, Record<SpinnerType, string[]>> = {
	unicode: {
		status: ["·", ":", "░", "▒", "▓", "█", "▓", "▒", "░", ":"],
		activity: ["·", ":", "░", "▒", "▓", "█", "▓", "▒", "░", ":"],
		thinking: ["✻", "✼", "❉", "❊", "✺", "✹", "✸", "✶"],
	},
	nerd: {
		status: ["·", ":", "░", "▒", "▓", "█", "▓", "▒", "░", ":"],
		activity: ["·", ":", "░", "▒", "▓", "█", "▓", "▒", "░", ":"],
		thinking: ["✻", "✼", "❉", "❊", "✺", "✹", "✸", "✶"],
	},
	ascii: {
		status: ["|", "/", "-", "\\"],
		activity: ["-", "\\", "|", "/"],
		thinking: ["*"],
	},
};

export function spinnerRampOneLevelShallower(frames: readonly string[]): string[] {
	if (frames.length < 4 || frames.length % 2 !== 0) return frames.slice();
	const peak = frames.length / 2;
	if (frames.filter(frame => frame === frames[peak]).length !== 1) return frames.slice();
	for (let i = 1; i < frames.length; i++) {
		if (i !== peak && frames[i] !== frames[frames.length - i]) return frames.slice();
	}
	return frames.filter((_, i) => i !== peak && i !== peak - 1);
}

export const BAR_RAMPS: Record<SymbolPreset, SubCellBarRamp> = {
	unicode: SUB_CELL_BAR_RAMP,
	nerd: SUB_CELL_BAR_RAMP,
	ascii: { full: "#", track: "-", partials: [] },
};

export type SpinnerFramesOverride = string[] | { status?: string[]; activity?: string[]; thinking?: string[] };

export function normalizeSpinnerFramesOverride(
	value: SpinnerFramesOverride | undefined,
): Partial<Record<SpinnerType, string[]>> {
	if (value === undefined) return {};
	if (Array.isArray(value)) return { status: value, activity: value };
	const result: Partial<Record<SpinnerType, string[]>> = {};
	if (value.status) result.status = value.status;
	if (value.activity) result.activity = value.activity;
	if (value.thinking) result.thinking = value.thinking;
	return result;
}
