import type { ImageContent, MessageAttribution, ServiceTierByFamily, TextContent, ToolResultMessage } from "@veyyon/ai";
import type { AgentMessage } from "../types";

/**
 * The session-entry vocabulary, owned here and nowhere else.
 *
 * WHY THIS FILE IS THE OWNER. These are the shapes a session file is made of, and they were
 * written out TWICE: once here and once in `@veyyon/coding-agent`'s
 * `src/session/session-entries.ts`, along with two copies of the `SessionEntry` union over
 * them. Twelve of the fifteen were byte-identical, which is the dangerous state rather than
 * the safe one -- nothing tells a reader the other copy exists, so a field lands in one of
 * them. Three had already drifted exactly that way: the coding agent's
 * `ThinkingLevelChangeEntry` had grown a `configured` field and its `SessionInitEntry` a
 * `spawns` and a `readSummarize`, none of which this copy knew about, so compaction reading
 * a session the coding agent wrote saw a type missing fields the file actually contained.
 *
 * The direction is forced: the coding agent depends on this package and not the reverse, so
 * the shared shapes live here and the coding agent re-exports them under the same names. Its
 * own additions arrive through {@link CustomCompactionSessionEntries}, the declaration-merging
 * hook that was already wired for exactly that purpose. Add a field HERE, not in a second copy.
 */

export interface SessionEntryBase {
	type: string;
	id: string;
	parentId: string | null;
	timestamp: string;
	/**
	 * Monotonic logical position assigned when lifecycle telemetry is enabled.
	 * Absent in older files and when session instrumentation is off.
	 */
	sequence?: number;
}

export interface SessionMessageEntry extends SessionEntryBase {
	type: "message";
	message: AgentMessage;
}

export interface ThinkingLevelChangeEntry extends SessionEntryBase {
	type: "thinking_level_change";
	thinkingLevel?: string | null;
	/**
	 * The user-configured selector at the time of this change: `"auto"` when auto
	 * mode was active, otherwise the concrete level. Absent on entries written
	 * before auto-mode persistence existed; readers fall back to `thinkingLevel`.
	 */
	configured?: string | null;
}

export interface ModelChangeEntry extends SessionEntryBase {
	type: "model_change";
	/** Model in "provider/modelId" format */
	model: string;
	/** Role: "default", "smol", "slow", etc. Undefined treated as "default" */
	role?: string;
}

export interface ServiceTierChangeEntry extends SessionEntryBase {
	type: "service_tier_change";
	serviceTier: ServiceTierByFamily | null;
}

export interface CompactionEntry<T = unknown> extends SessionEntryBase {
	type: "compaction";
	summary: string;
	shortSummary?: string;
	firstKeptEntryId: string;
	tokensBefore: number;
	/** Extension-specific data (e.g., ArtifactIndex, version markers for structured compaction) */
	details?: T;
	/** Hook-provided data to persist across compaction */
	preserveData?: Record<string, unknown>;
	/** True if generated by an extension, undefined/false if pi-generated (backward compatible) */
	fromExtension?: boolean;
	/**
	 * Dead-end warning from the post-pass progress guard: the pass completed
	 * but freed too little for maintenance to continue. Rendered on the
	 * compaction divider.
	 */
	warning?: string;
}

export interface BranchSummaryEntry<T = unknown> extends SessionEntryBase {
	type: "branch_summary";
	fromId: string;
	summary: string;
	/** Extension-specific data (not sent to LLM) */
	details?: T;
	/** True if generated by an extension, false if pi-generated */
	fromExtension?: boolean;
}

export interface CustomMessageEntry<T = unknown> extends SessionEntryBase {
	type: "custom_message";
	customType: string;
	content: string | (TextContent | ImageContent)[];
	details?: T;
	display: boolean;
	/** Who initiated this message for billing/attribution semantics. */
	attribution?: MessageAttribution;
}

export interface CustomEntry<T = unknown> extends SessionEntryBase {
	type: "custom";
	customType: string;
	data?: T;
}

export interface LabelEntry extends SessionEntryBase {
	type: "label";
	targetId: string;
	label: string | undefined;
}

export interface TitleChangeEntry extends SessionEntryBase {
	type: "title_change";
	title: string;
	previousTitle?: string;
	source: "auto" | "user";
	trigger?: string;
}

export interface TtsrInjectionEntry extends SessionEntryBase {
	type: "ttsr_injection";
	/** Names of rules that were injected */
	injectedRules: string[];
}

export interface MCPToolSelectionEntry extends SessionEntryBase {
	type: "mcp_tool_selection";
	/** MCP tool names selected for visibility in discovery mode. */
	selectedToolNames: string[];
}

export interface SessionInitEntry extends SessionEntryBase {
	type: "session_init";
	/** Full system prompt sent to the model */
	systemPrompt: string;
	/** Initial task/user message */
	task: string;
	/** Tools available to the agent */
	tools: string[];
	/** Output schema if structured output was requested */
	outputSchema?: unknown;
	/** Spawn allowlist the subagent ran with ("" = none, "*" = any, else CSV); absent on pre-spawns files. */
	spawns?: string;
	/** The agent's `readSummarize` setting (`false` = read summarization disabled); absent uses the session default. */
	readSummarize?: boolean;
	/** Resolved nested spawn limit for this agent; absent on older session files. */
	maxNestedSpawnDepth?: number;
}

export interface ModeChangeEntry extends SessionEntryBase {
	type: "mode_change";
	/** Current mode name, or "none" when exiting a mode */
	mode: string;
	/** Optional mode-specific data (e.g. plan file path) */
	data?: Record<string, unknown>;
}

/**
 * Entry shapes a consuming package adds to {@link SessionEntry}, by declaration merging.
 *
 * A package that persists its own entry kinds augments this interface rather than
 * redeclaring the union, which is what keeps one union over one vocabulary:
 *
 * ```ts
 * declare module "@veyyon/agent-core/compaction/entries" {
 *     interface CustomCompactionSessionEntries {
 *         subagentSpawn: SubagentSpawnEntry;
 *     }
 * }
 * ```
 */
export interface CustomCompactionSessionEntries {}

export type SessionEntry =
	| SessionMessageEntry
	| ThinkingLevelChangeEntry
	| ModelChangeEntry
	| ServiceTierChangeEntry
	| CompactionEntry
	| BranchSummaryEntry
	| CustomEntry
	| CustomMessageEntry
	| LabelEntry
	| TitleChangeEntry
	| TtsrInjectionEntry
	| MCPToolSelectionEntry
	| SessionInitEntry
	| ModeChangeEntry
	| CustomCompactionSessionEntries[keyof CustomCompactionSessionEntries];

export interface ReadonlySessionManager {
	getBranch(leafId?: string | null): SessionEntry[];
	getEntry(id: string): SessionEntry | undefined;
}

/**
 * The tool result an entry carries, or undefined when it carries something else.
 *
 * Compaction walks a whole branch looking for tool output to prune or shake, so nearly every
 * entry it sees is NOT a tool result and answering undefined is the ordinary case rather than a
 * failure. The narrowing lives with the {@link SessionEntry} union it narrows: both compaction
 * passes had their own copy, and a pass that recognised one message shape while its sibling
 * recognised another would prune output the other still counted.
 */
export function getToolResultMessage(entry: SessionEntry): ToolResultMessage | undefined {
	if (entry.type !== "message") return undefined;
	const message = entry.message as AgentMessage;
	if (message.role !== "toolResult") return undefined;
	return message as ToolResultMessage;
}

/**
 * `firstKeptEntryId` for a compaction that keeps no pre-compaction entry at all.
 *
 * A range can be one unbreakable oversized turn: a tool result is never a valid
 * cut point, because cutting there would separate it from the call it answers,
 * so a single enormous result leaves the assistant message in front of it as the
 * newest usable boundary, and keeping from there keeps everything. Summarizing
 * the whole range and keeping nothing is then the only way to free anything.
 *
 * Readers resolve the id against the entries in the path and there is
 * deliberately no entry with this one, so every reader that walks until it finds
 * the first kept entry keeps nothing, which is what this means.
 */
export const KEEP_NOTHING_ENTRY_ID = "compaction:keep-nothing";

/**
 * Array index of the compaction boundary named by a `firstKeptEntryId`. Entries
 * BEFORE it were summarized away by the latest compaction and are never sent, so
 * prune and shake passes skip them: rewriting them churns persisted history
 * without shrinking a single prompt.
 *
 * Three cases, and the third is why this is shared rather than inlined at each
 * call site. No boundary means no compaction, so the whole branch is live and
 * the index is 0. An ordinary id resolves to its entry. {@link
 * KEEP_NOTHING_ENTRY_ID} deliberately matches no entry, and a plain `findIndex`
 * answers -1 for it, which every caller clamped to 0 — the exact opposite of
 * what it means. It resolves to just past the compaction entry, because a
 * compaction that kept nothing left everything before itself summarized away.
 */
export function resolveCompactionBoundaryIndex(
	entries: readonly SessionEntry[],
	keepBoundaryId: string | undefined,
): number {
	if (keepBoundaryId === undefined) return 0;
	if (keepBoundaryId === KEEP_NOTHING_ENTRY_ID) {
		for (let i = entries.length - 1; i >= 0; i--) {
			if (entries[i].type === "compaction") return i + 1;
		}
		return 0;
	}
	const index = entries.findIndex(entry => entry.id === keepBoundaryId);
	return index < 0 ? 0 : index;
}
