import { describe, expect, test } from "bun:test";
import * as fs from "node:fs";
import * as path from "node:path";
import { GENERATOR_PATH, REFERENCE_DOC_PATH, renderReference } from "./gen-settings-reference";
import { generatedDocGenerator, generatedDocMarker, withGeneratedDocMarker } from "./lib/generated-doc";

// WHY: a generated handbook page stated its provenance three paragraphs in, as prose, so
// a mechanical docs sweep edited it twice in one session and both edits were recovered
// only from memory of the rule. The marker now sits on the first line, where a script
// reads it before writing.
//
// The class this closes: a sweep or a gate that recognizes generated documents from a
// hardcoded path list, which is the list that goes stale the day a second generator
// ships. Every handbook page is read here at run time, so a new generated page joins the
// sweep by carrying the marker, and a marker naming a script that does not exist is red.
//
// What it does not catch: a NEW generator that renders a page without going through
// `withGeneratedDocMarker`. Nothing in a test can see a script nobody wrote yet; what it
// can do is make the helper the cheapest path and fail the page the moment its marker
// names a missing script.

const REPO_ROOT = path.resolve(import.meta.dirname, "..");
const HANDBOOK_SRC = path.join(REPO_ROOT, "docs/handbook/src");

function handbookPages(dir: string): string[] {
	const pages: string[] = [];
	for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
		const full = path.join(dir, entry.name);
		if (entry.isDirectory()) pages.push(...handbookPages(full));
		else if (entry.name.endsWith(".md")) pages.push(full);
	}
	return pages;
}

describe("a generated doc says so on its first line", () => {
	test("the settings reference's first line names its generator", () => {
		const committed = fs.readFileSync(path.join(REPO_ROOT, REFERENCE_DOC_PATH), "utf-8");
		expect(committed.split("\n")[0]).toBe(generatedDocMarker(GENERATOR_PATH));
		expect(generatedDocGenerator(committed)).toBe(GENERATOR_PATH);
		// The marker is part of the rendered bytes, so the staleness gate covers it too.
		expect(renderReference().startsWith(`${generatedDocMarker(GENERATOR_PATH)}\n`)).toBe(true);
	});

	test("every marked handbook page names a generator that exists, and the rest are authored", () => {
		const marked: string[] = [];
		for (const page of handbookPages(HANDBOOK_SRC)) {
			const generator = generatedDocGenerator(fs.readFileSync(page, "utf-8"));
			if (generator === null) continue;
			marked.push(path.relative(REPO_ROOT, page));
			expect(fs.existsSync(path.join(REPO_ROOT, generator)), `${page} names a missing generator`).toBe(true);
		}
		// Exact equality, not a count: a second generated page must be decided here rather
		// than inherited by a sweep that stopped reading after the first one.
		expect(marked).toEqual([REFERENCE_DOC_PATH]);
	});

	test("an authored page carries no marker, and a marker cannot be applied twice", () => {
		const authored = fs.readFileSync(path.join(HANDBOOK_SRC, "reference/settings.md"), "utf-8");
		expect(generatedDocGenerator(authored)).toBeNull();

		const once = withGeneratedDocMarker("scripts/gen-x.ts", "# Title\n");
		expect(generatedDocGenerator(once)).toBe("scripts/gen-x.ts");
		expect(() => withGeneratedDocMarker("scripts/gen-x.ts", once)).toThrow(/already carries/);
	});

	test("a marker is recognized only as the whole first line", () => {
		expect(
			generatedDocGenerator("# Title\n<!-- generated by scripts/gen-x.ts -- do not edit by hand -->\n"),
		).toBeNull();
		expect(generatedDocGenerator("<!-- generated by  -- do not edit by hand -->\n")).toBeNull();
		expect(generatedDocGenerator("<!-- generated by scripts/gen-x.ts -->\n")).toBeNull();
	});
});
