/**
 * WHY THIS EXISTS. A shipped module that no test names is a blind spot nothing reports. A
 * pre-release sweep found twelve of them among the 266 modules changed since v1.2.0, including the
 * Startpage bot-wall refusal and both newly added authentication registries: three paths that had
 * shipped, changed, and never been named by a test. A sweep finds that once. A gate keeps finding it.
 *
 * WHAT IT DOES. It enumerates every shipped TypeScript module under `packages/<pkg>/src` at run time,
 * enumerates every test file at run time, and asserts that the set of modules no test names is
 * EXACTLY the list below. A module added without a test turns this red. The list is shrink-only:
 * deleting an entry because the module gained a test is the point, and adding one records a decision
 * that a shipped module ships unnamed rather than letting the silence pass.
 *
 * WHAT IT DOES NOT CATCH. "A test names it" is not "a test covers its behavior". A module can be
 * named by an import and have none of its branches exercised, and this gate calls that named. It is a
 * floor, not a coverage measurement. It is deliberately permissive in three ascending steps (exact
 * module key, bare path segment, raw substring), so a module reached only through a barrel or written
 * only as a basename still counts as named. It therefore under-reports and never over-reports, which
 * means a red here is a real new blind spot rather than a false alarm.
 */
import { describe, expect, it } from "bun:test";
import * as fs from "node:fs";
import * as path from "node:path";

const REPO_ROOT = path.resolve(import.meta.dir, "..");

/** This file lists unnamed modules by path, so counting itself would mark every one of them named. */
const SELF = path.join("scripts", "a-shipped-module-arrives-with-a-test-that-names-it.test.ts");

function walk(dir: string, keep: (file: string) => boolean): string[] {
	const found: string[] = [];
	let entries: fs.Dirent[];
	try {
		entries = fs.readdirSync(dir, { withFileTypes: true });
	} catch {
		return found;
	}
	for (const entry of entries) {
		const full = path.join(dir, entry.name);
		if (entry.isDirectory()) {
			if (entry.name === "node_modules") continue;
			found.push(...walk(full, keep));
		} else if (keep(full)) {
			found.push(full);
		}
	}
	return found;
}

function packageDirs(): string[] {
	const root = path.join(REPO_ROOT, "packages");
	return fs
		.readdirSync(root, { withFileTypes: true })
		.filter(entry => entry.isDirectory())
		.map(entry => path.join(root, entry.name));
}

/** Every shipped module: under `src`, TypeScript, not a declaration file and not a test. */
function shippedModules(): string[] {
	const files: string[] = [];
	for (const pkg of packageDirs()) {
		files.push(
			...walk(
				path.join(pkg, "src"),
				file => file.endsWith(".ts") && !file.endsWith(".d.ts") && !file.includes(".test."),
			),
		);
	}
	return files.map(file => path.relative(REPO_ROOT, file)).sort();
}

/** Every test file, which is what may name a module. */
function testFiles(): string[] {
	const files: string[] = [];
	for (const pkg of packageDirs()) {
		files.push(...walk(path.join(pkg, "test"), file => file.endsWith(".ts")));
	}
	files.push(...walk(path.join(REPO_ROOT, "scripts"), file => file.endsWith(".test.ts")));
	return files.map(file => path.relative(REPO_ROOT, file)).filter(file => file !== SELF);
}

const QUOTED_PATH = /['"`]([^'"`\n]*\/[^'"`\n]*)['"`]/g;

/** The `src`-relative path of a shipped module, which is the key every route compares against. */
const SRC_SUFFIX = /\/src\/(.+)\.ts$/;

/** Reduce a quoted specifier to the `src`-relative key a shipped module would carry. */
function moduleKey(literal: string): string {
	return literal
		.trim()
		.replace(/^@veyyon\/[^/]+\//, "")
		.replace(/^(?:\.\.\/)+/, "")
		.replace(/^\.\//, "")
		.replace(/^packages\/[^/]+\//, "")
		.replace(/^src\//, "")
		.replace(/\.(ts|tsx|js|mjs)$/, "");
}

/**
 * The modules no test names, by three routes in ascending cost: an exact module key, a bare path
 * segment (which covers a barrel or a basename reference), and a raw substring scan for the handful
 * neither route matched.
 *
 * A key that is itself a shipped module path contributes no segments. That reference is already
 * spent on the exact step, and letting it also credit a same-named module in another package is the
 * one way this can over-report: a test importing `swarm/pipeline` would otherwise mark
 * `commit/pipeline` covered, which is the opposite of what a floor is for.
 */
function unnamedModules(): string[] {
	const keys = new Set<string>();
	const texts: string[] = [];

	for (const file of testFiles()) {
		const text = fs.readFileSync(path.join(REPO_ROOT, file), "utf8");
		texts.push(text);
		for (const match of text.matchAll(QUOTED_PATH)) keys.add(moduleKey(match[1] ?? ""));
	}
	const corpus = texts.join("\n");

	const shipped = shippedModules();
	const shippedSuffixes = new Set<string>();
	for (const file of shipped) {
		const suffix = SRC_SUFFIX.exec(file)?.[1];
		if (suffix !== undefined) shippedSuffixes.add(suffix);
	}

	const segments = new Set<string>();
	for (const key of keys) {
		if (shippedSuffixes.has(key)) continue;
		for (const segment of key.split("/")) segments.add(segment);
	}

	const unnamed: string[] = [];
	for (const file of shipped) {
		const suffix = SRC_SUFFIX.exec(file)?.[1];
		if (suffix === undefined) continue;
		const base = suffix.slice(suffix.lastIndexOf("/") + 1);
		if (keys.has(suffix) || segments.has(base)) continue;
		if (suffix.endsWith("/index") && keys.has(suffix.slice(0, -"/index".length))) continue;
		if (corpus.includes(suffix)) continue;
		unnamed.push(file);
	}
	return unnamed.sort();
}

/**
 * Shrink-only. Remove an entry when the module gains a test. Adding one records that a shipped
 * module ships with no test naming it, which should be rare enough to argue about in review.
 */
const NAMED_BY_NO_TEST: readonly string[] = [
	"packages/agent/src/agent-helpers.ts",
	"packages/agent/src/append-only-context-helpers.ts",
	"packages/agent/src/compaction/legacy-provider-native.ts",
	"packages/agent/src/compaction/remote-compaction-entry.ts",
	"packages/agent/src/run-collector-helpers.ts",
	"packages/agent/src/tool-result-never-ran.ts",
	"packages/ai/src/auth-broker/client-helpers.ts",
	"packages/ai/src/auth-broker/refresher-helpers.ts",
	"packages/ai/src/auth-broker/refresher.ts",
	"packages/ai/src/auth-broker/remote-store-helpers.ts",
	"packages/ai/src/auth-broker/remote-store.ts",
	"packages/ai/src/auth-broker/server-helpers.ts",
	"packages/ai/src/auth-storage-helpers.ts",
	"packages/ai/src/cache/policy-helpers.ts",
	"packages/ai/src/cache/tracker.ts",
	"packages/ai/src/dialect/deepseek-helpers.ts",
	"packages/ai/src/dialect/factory.ts",
	"packages/ai/src/dialect/fenced-thinking-helpers.ts",
	"packages/ai/src/dialect/fenced-thinking.ts",
	"packages/ai/src/dialect/gemini-helpers.ts",
	"packages/ai/src/dialect/gemma-helpers.ts",
	"packages/ai/src/dialect/glm-helpers.ts",
	"packages/ai/src/dialect/harmony-helpers.ts",
	"packages/ai/src/dialect/kimi-helpers.ts",
	"packages/ai/src/dialect/pi-native-helpers.ts",
	"packages/ai/src/dialect/qwen3-helpers.ts",
	"packages/ai/src/dialect/thinking-helpers.ts",
	"packages/ai/src/error/classes-helpers.ts",
	"packages/ai/src/error/connect.ts",
	"packages/ai/src/error/domains/request.ts",
	"packages/ai/src/error/oauth-helpers.ts",
	"packages/ai/src/error/provider-helpers.ts",
	"packages/ai/src/providers/amazon-bedrock-helpers.ts",
	"packages/ai/src/providers/anthropic-client-helpers.ts",
	"packages/ai/src/providers/anthropic-messages-server-schema.ts",
	"packages/ai/src/providers/anthropic-schema.ts",
	"packages/ai/src/providers/cursor-helpers.ts",
	"packages/ai/src/providers/devin-helpers.ts",
	"packages/ai/src/providers/gitlab-duo-workflow-helpers.ts",
	"packages/ai/src/providers/google-gemini-cli-helpers.ts",
	"packages/ai/src/providers/google-shared-helpers.ts",
	"packages/ai/src/providers/grammar.ts",
	"packages/ai/src/providers/mock-helpers.ts",
	"packages/ai/src/providers/ollama-helpers.ts",
	"packages/ai/src/providers/openai-anthropic-shim.ts",
	"packages/ai/src/providers/openai-chat-server-schema.ts",
	"packages/ai/src/providers/openai-codex-responses-helpers.ts",
	"packages/ai/src/providers/openai-codex/response-handler-helpers.ts",
	"packages/ai/src/providers/openai-completions-helpers.ts",
	"packages/ai/src/providers/openai-responses-codec-helpers.ts",
	"packages/ai/src/providers/openai-responses-codec.ts",
	"packages/ai/src/providers/openai-responses-helpers.ts",
	"packages/ai/src/providers/openai-responses-server-helpers.ts",
	"packages/ai/src/providers/openai-responses-server-schema.ts",
	"packages/ai/src/providers/openai-shared-helpers.ts",
	"packages/ai/src/providers/pi-native-client-helpers.ts",
	"packages/ai/src/providers/synthetic.ts",
	"packages/ai/src/registry/api-key-login.ts",
	"packages/ai/src/registry/baseten.ts",
	"packages/ai/src/registry/llama-cpp.ts",
	"packages/ai/src/registry/lm-studio.ts",
	"packages/ai/src/registry/minimax-code-cn.ts",
	"packages/ai/src/registry/minimax-code.ts",
	"packages/ai/src/registry/mistral.ts",
	"packages/ai/src/registry/oauth/device-code.ts",
	"packages/ai/src/registry/oauth/devin-helpers.ts",
	"packages/ai/src/registry/oauth/gitlab-duo-helpers.ts",
	"packages/ai/src/registry/oauth/gitlab-duo-workflow-helpers.ts",
	"packages/ai/src/registry/oauth/google-oauth-shared-helpers.ts",
	"packages/ai/src/registry/oauth/openai-codex-helpers.ts",
	"packages/ai/src/registry/oauth/pkce.ts",
	"packages/ai/src/registry/oauth/success-page.ts",
	"packages/ai/src/registry/oauth/wafer.ts",
	"packages/ai/src/registry/openai-codex-device.ts",
	"packages/ai/src/registry/parallel.ts",
	"packages/ai/src/registry/qianfan.ts",
	"packages/ai/src/registry/qwen-portal.ts",
	"packages/ai/src/registry/sakana.ts",
	"packages/ai/src/registry/tavily.ts",
	"packages/ai/src/registry/together.ts",
	"packages/ai/src/registry/vllm.ts",
	"packages/ai/src/registry/xiaomi-token-plan-ams.ts",
	"packages/ai/src/registry/xiaomi-token-plan-cn.ts",
	"packages/ai/src/registry/xiaomi-token-plan-sgp.ts",
	"packages/ai/src/stream-helpers.ts",
	"packages/ai/src/utils/deterministic-id.ts",
	"packages/ai/src/utils/github-copilot-http.ts",
	"packages/ai/src/utils/openrouter-headers.ts",
	"packages/ai/src/utils/parse-bind.ts",
	"packages/ai/src/utils/provider-fetch.ts",
	"packages/ai/src/utils/schema/adapt.ts",
	"packages/ai/src/utils/schema/compatibility.ts",
	"packages/ai/src/utils/schema/dereference.ts",
	"packages/ai/src/utils/schema/equality.ts",
	"packages/ai/src/utils/schema/fields.ts",
	"packages/ai/src/utils/schema/json-schema-validator.ts",
	"packages/ai/src/utils/schema/meta-validator.ts",
	"packages/ai/src/utils/schema/multiple-of.ts",
	"packages/ai/src/utils/schema/normalize-helpers.ts",
	"packages/ai/src/utils/schema/spill.ts",
	"packages/ai/src/utils/schema/stamps.ts",
	"packages/ai/src/utils/schema/strict-tool-validation.ts",
	"packages/ai/src/utils/schema/zod-decontaminate.ts",
	"packages/ai/src/utils/sdk-stream-timeout.ts",
	"packages/ai/src/utils/stream-markup-healing-helpers.ts",
	"packages/ai/src/utils/tool-call-loop-guard-helpers.ts",
	"packages/ai/src/utils/validation-helpers.ts",
	"packages/catalog/src/discovery/devin-gen/buf/validate/validate_pb.ts",
	"packages/catalog/src/discovery/devin-gen/exa/analytics_pb/analytics_pb.ts",
	"packages/catalog/src/discovery/devin-gen/exa/auto_cascade_common_pb/auto_cascade_common_pb.ts",
	"packages/catalog/src/discovery/devin-gen/exa/bug_checker_pb/bug_checker_pb.ts",
	"packages/catalog/src/discovery/devin-gen/exa/cascade_plugins_pb/cascade_plugins_pb.ts",
	"packages/catalog/src/discovery/devin-gen/exa/chat_pb/chat_pb.ts",
	"packages/catalog/src/discovery/devin-gen/exa/code_edit/code_edit_pb/code_edit_pb.ts",
	"packages/catalog/src/discovery/devin-gen/exa/context_module_pb/context_module_pb.ts",
	"packages/catalog/src/discovery/devin-gen/exa/cortex_pb/cortex_pb.ts",
	"packages/catalog/src/discovery/devin-gen/exa/diff_action_pb/diff_action_pb.ts",
	"packages/catalog/src/discovery/devin-gen/exa/index_pb/index_pb.ts",
	"packages/catalog/src/discovery/devin-gen/exa/knowledge_base_pb/knowledge_base_pb.ts",
	"packages/catalog/src/discovery/devin-gen/exa/language_server_pb/language_server_pb.ts",
	"packages/catalog/src/discovery/devin-gen/exa/opensearch_clients_pb/opensearch_clients_pb.ts",
	"packages/catalog/src/discovery/devin-gen/exa/prompt_pb/prompt_pb.ts",
	"packages/catalog/src/discovery/devin-gen/exa/reactive_component_pb/reactive_component_pb.ts",
	"packages/catalog/src/discovery/devin-gen/exa/trust_pb/trust_pb.ts",
	"packages/catalog/src/provider-models/bundled-references.ts",
	"packages/catalog/src/provider-models/openai-compat/overrides-helpers.ts",
	"packages/catalog/src/provider-models/openai-compat/overrides.ts",
	"packages/catalog/src/provider-models/openai-compat/providers-helpers-2.ts",
	"packages/catalog/src/provider-models/openai-compat/providers-helpers.ts",
	"packages/catalog/src/provider-models/openai-compat/resolvers.ts",
	"packages/coding-agent/src/advisor/advise-tool-helpers.ts",
	"packages/coding-agent/src/advisor/emission-guard-helpers.ts",
	"packages/coding-agent/src/advisor/runtime-helpers.ts",
	"packages/coding-agent/src/argot-wire-helpers.ts",
	"packages/coding-agent/src/async/job-manager-helpers.ts",
	"packages/coding-agent/src/autolearn/controller-helpers.ts",
	"packages/coding-agent/src/autoresearch/dashboard.ts",
	"packages/coding-agent/src/autoresearch/shortcuts.ts",
	"packages/coding-agent/src/autoresearch/storage-helpers.ts",
	"packages/coding-agent/src/cli/auth-gateway-cli.ts",
	"packages/coding-agent/src/cli/commands/init-xdg.ts",
	"packages/coding-agent/src/cli/gallery-fixtures/codeintel.ts",
	"packages/coding-agent/src/cli/gallery-fixtures/misc.ts",
	"packages/coding-agent/src/cli/grep-cli.ts",
	"packages/coding-agent/src/cli/grievances-cli.ts",
	"packages/coding-agent/src/cli/read-cli.ts",
	"packages/coding-agent/src/cli/rollback-picker-host.ts",
	"packages/coding-agent/src/cli/session-picker.ts",
	"packages/coding-agent/src/cli/session-stats-cli.ts",
	"packages/coding-agent/src/cli/setup-model-picker.ts",
	"packages/coding-agent/src/cli/stats-cli.ts",
	"packages/coding-agent/src/cli/update-cli-helpers.ts",
	"packages/coding-agent/src/cli/worktree-cli.ts",
	"packages/coding-agent/src/collab/guest-helpers.ts",
	"packages/coding-agent/src/collab/host-helpers.ts",
	"packages/coding-agent/src/collab/relay-client-helpers.ts",
	"packages/coding-agent/src/commands/complete.ts",
	"packages/coding-agent/src/commands/dry-balance.ts",
	"packages/coding-agent/src/commands/gallery.ts",
	"packages/coding-agent/src/commands/gc.ts",
	"packages/coding-agent/src/commands/rollback.ts",
	"packages/coding-agent/src/commands/say.ts",
	"packages/coding-agent/src/commit/agentic/tools/analyze-file.ts",
	"packages/coding-agent/src/commit/agentic/tools/git-hunk.ts",
	"packages/coding-agent/src/commit/agentic/tools/git-overview.ts",
	"packages/coding-agent/src/commit/agentic/tools/propose-changelog.ts",
	"packages/coding-agent/src/commit/agentic/tools/propose-commit.ts",
	"packages/coding-agent/src/commit/analysis/conventional.ts",
	"packages/coding-agent/src/commit/pipeline.ts",
	"packages/coding-agent/src/config/config-file-helpers.ts",
	"packages/coding-agent/src/config/dialect-format.ts",
	"packages/coding-agent/src/config/keybindings-helpers.ts",
	"packages/coding-agent/src/config/model-registry-discovery.ts",
	"packages/coding-agent/src/config/model-registry-overrides.ts",
	"packages/coding-agent/src/config/model-registry-registration.ts",
	"packages/coding-agent/src/config/model-registry-resolution.ts",
	"packages/coding-agent/src/config/model-registry-stage.ts",
	"packages/coding-agent/src/config/model-resolver-helpers.ts",
	"packages/coding-agent/src/config/settings-domains/tasks.ts",
	"packages/coding-agent/src/config/settings-helpers.ts",
	"packages/coding-agent/src/cursor-helpers.ts",
	"packages/coding-agent/src/dap/client-helpers.ts",
	"packages/coding-agent/src/dap/session-helpers.ts",
	"packages/coding-agent/src/debug/debug-selector-helpers.ts",
	"packages/coding-agent/src/debug/debug-selector.ts",
	"packages/coding-agent/src/debug/log-viewer-helpers.ts",
	"packages/coding-agent/src/debug/protocol-probe-helpers.ts",
	"packages/coding-agent/src/debug/raw-sse-buffer-helpers.ts",
	"packages/coding-agent/src/debug/raw-sse-helpers.ts",
	"packages/coding-agent/src/debug/remote-debugger.ts",
	"packages/coding-agent/src/discovery/windsurf.ts",
	"packages/coding-agent/src/edit/diff-helpers.ts",
	"packages/coding-agent/src/edit/edit-tool-helpers.ts",
	"packages/coding-agent/src/edit/hashline/params.ts",
	"packages/coding-agent/src/edit/match-helpers.ts",
	"packages/coding-agent/src/edit/modes/patch-helpers.ts",
	"packages/coding-agent/src/eval/agent-bridge-name.ts",
	"packages/coding-agent/src/eval/completion-bridge.ts",
	"packages/coding-agent/src/eval/executor-base-helpers.ts",
	"packages/coding-agent/src/eval/jl/executor-helpers.ts",
	"packages/coding-agent/src/eval/jl/kernel-helpers.ts",
	"packages/coding-agent/src/eval/jl/prelude.ts",
	"packages/coding-agent/src/eval/js/shared/local-module-loader-helpers.ts",
	"packages/coding-agent/src/eval/js/shared/prelude.ts",
	"packages/coding-agent/src/eval/js/shared/runtime-helpers.ts",
	"packages/coding-agent/src/eval/js/worker-core-helpers.ts",
	"packages/coding-agent/src/eval/kernel-store-helpers.ts",
	"packages/coding-agent/src/eval/py/kernel-helpers.ts",
	"packages/coding-agent/src/eval/py/prelude.ts",
	"packages/coding-agent/src/eval/py/session-namespace.ts",
	"packages/coding-agent/src/eval/rb/kernel-helpers.ts",
	"packages/coding-agent/src/eval/rb/prelude.ts",
	"packages/coding-agent/src/eval/session-id.ts",
	"packages/coding-agent/src/exa/mcp-client-helpers.ts",
	"packages/coding-agent/src/export/redact-snapshot.ts",
	"packages/coding-agent/src/export/ttsr-helpers.ts",
	"packages/coding-agent/src/extensibility/custom-commands/bundled/ci-green/index-helpers.ts",
	"packages/coding-agent/src/extensibility/custom-commands/bundled/review/index-helpers.ts",
	"packages/coding-agent/src/extensibility/custom-tools/loader-helpers.ts",
	"packages/coding-agent/src/extensibility/extensions/loader-helpers.ts",
	"packages/coding-agent/src/extensibility/extensions/wrapper-helpers.ts",
	"packages/coding-agent/src/extensibility/legacy-pi-coding-agent-shim-helpers.ts",
	"packages/coding-agent/src/extensibility/plugins/manager-helpers.ts",
	"packages/coding-agent/src/extensibility/plugins/marketplace/factory.ts",
	"packages/coding-agent/src/extensibility/plugins/marketplace/manager-helpers.ts",
	"packages/coding-agent/src/extensibility/plugins/runtime-config.ts",
	"packages/coding-agent/src/extensibility/session-handler-types.ts",
	"packages/coding-agent/src/extensibility/utils-helpers.ts",
	"packages/coding-agent/src/goals/runtime-helpers.ts",
	"packages/coding-agent/src/goals/tools/goal-tool-helpers.ts",
	"packages/coding-agent/src/hindsight/client-helpers.ts",
	"packages/coding-agent/src/hindsight/state-helpers.ts",
	"packages/coding-agent/src/internal-urls/agent-protocol.ts",
	"packages/coding-agent/src/internal-urls/artifact-protocol-helpers.ts",
	"packages/coding-agent/src/internal-urls/history-protocol-helpers.ts",
	"packages/coding-agent/src/internal-urls/issue-pr-protocol-helpers.ts",
	"packages/coding-agent/src/internal-urls/local-protocol-helpers.ts",
	"packages/coding-agent/src/internal-urls/mcp-protocol-helpers.ts",
	"packages/coding-agent/src/internal-urls/memory-protocol-helpers.ts",
	"packages/coding-agent/src/internal-urls/relative-path.ts",
	"packages/coding-agent/src/internal-urls/ssh-protocol-helpers.ts",
	"packages/coding-agent/src/internal-urls/veyyon-protocol.ts",
	"packages/coding-agent/src/irc/bus-helpers.ts",
	"packages/coding-agent/src/json-transform-helpers.ts",
	"packages/coding-agent/src/jsonrpc/message-framing-helpers.ts",
	"packages/coding-agent/src/launch/broker-helpers.ts",
	"packages/coding-agent/src/launch/client-helpers.ts",
	"packages/coding-agent/src/lsp/clients/biome-client-helpers.ts",
	"packages/coding-agent/src/lsp/clients/lsp-linter-client.ts",
	"packages/coding-agent/src/lsp/clients/swiftlint-client-helpers.ts",
	"packages/coding-agent/src/lsp/deferred-diagnostics.ts",
	"packages/coding-agent/src/lsp/lsp-helpers.ts",
	"packages/coding-agent/src/lsp/lsp-tool.ts",
	"packages/coding-agent/src/main-helpers.ts",
	"packages/coding-agent/src/markit/converters/docx.ts",
	"packages/coding-agent/src/markit/converters/epub-helpers.ts",
	"packages/coding-agent/src/markit/converters/epub.ts",
	"packages/coding-agent/src/markit/converters/pdf/index-helpers.ts",
	"packages/coding-agent/src/markit/converters/pptx-helpers.ts",
	"packages/coding-agent/src/markit/converters/pptx.ts",
	"packages/coding-agent/src/markit/converters/xlsx-helpers.ts",
	"packages/coding-agent/src/mcp/auth-failure-helpers.ts",
	"packages/coding-agent/src/mcp/config-commands.ts",
	"packages/coding-agent/src/mcp/loader.ts",
	"packages/coding-agent/src/mcp/manager-helpers.ts",
	"packages/coding-agent/src/mcp/oauth-flow-helpers.ts",
	"packages/coding-agent/src/mcp/smithery-auth.ts",
	"packages/coding-agent/src/mcp/smithery-connect.ts",
	"packages/coding-agent/src/mcp/smithery-registry-helpers.ts",
	"packages/coding-agent/src/mcp/tool-bridge-helpers.ts",
	"packages/coding-agent/src/mcp/tool-cache-helpers.ts",
	"packages/coding-agent/src/mcp/transports/http-helpers.ts",
	"packages/coding-agent/src/mcp/transports/sse-helpers.ts",
	"packages/coding-agent/src/mcp/transports/stdio-helpers.ts",
	"packages/coding-agent/src/mcp/unresolved-placeholder-helpers.ts",
	"packages/coding-agent/src/memories/index-helpers.ts",
	"packages/coding-agent/src/mnemopi/embed-client-helpers.ts",
	"packages/coding-agent/src/mnemopi/embed-worker.ts",
	"packages/coding-agent/src/modes/acp/acp-helpers.ts",
	"packages/coding-agent/src/modes/components/account-manager-helpers.ts",
	"packages/coding-agent/src/modes/components/advisor-config-helpers.ts",
	"packages/coding-agent/src/modes/components/advisor-message.ts",
	"packages/coding-agent/src/modes/components/agent-dashboard-helpers.ts",
	"packages/coding-agent/src/modes/components/agent-model-badge.ts",
	"packages/coding-agent/src/modes/components/agent-transcript-viewer-helpers.ts",
	"packages/coding-agent/src/modes/components/ask-dialog-helpers.ts",
	"packages/coding-agent/src/modes/components/assistant-message-helpers.ts",
	"packages/coding-agent/src/modes/components/btw-panel-helpers.ts",
	"packages/coding-agent/src/modes/components/cache-invalidation-marker-helpers.ts",
	"packages/coding-agent/src/modes/components/chat-transcript-builder-helpers.ts",
	"packages/coding-agent/src/modes/components/collab-prompt-message.ts",
	"packages/coding-agent/src/modes/components/compaction-summary-message-helpers.ts",
	"packages/coding-agent/src/modes/components/composer-shortcuts-helpers.ts",
	"packages/coding-agent/src/modes/components/copy-selector-helpers.ts",
	"packages/coding-agent/src/modes/components/custom-editor-helpers.ts",
	"packages/coding-agent/src/modes/components/extensions/extension-dashboard-helpers.ts",
	"packages/coding-agent/src/modes/components/extensions/extension-list-helpers.ts",
	"packages/coding-agent/src/modes/components/extensions/inspector-panel-helpers.ts",
	"packages/coding-agent/src/modes/components/history-search-helpers.ts",
	"packages/coding-agent/src/modes/components/hook-editor-helpers.ts",
	"packages/coding-agent/src/modes/components/hook-selector-helpers.ts",
	"packages/coding-agent/src/modes/components/keybinding-hints.ts",
	"packages/coding-agent/src/modes/components/login-dialog-helpers.ts",
	"packages/coding-agent/src/modes/components/mcp-add-wizard-helpers.ts",
	"packages/coding-agent/src/modes/components/modal-select-list-helpers.ts",
	"packages/coding-agent/src/modes/components/model-browser-helpers.ts",
	"packages/coding-agent/src/modes/components/model-hub-helpers.ts",
	"packages/coding-agent/src/modes/components/model-picker-helpers.ts",
	"packages/coding-agent/src/modes/components/model-selector-helpers.ts",
	"packages/coding-agent/src/modes/components/move-overlay-helpers.ts",
	"packages/coding-agent/src/modes/components/oauth-selector-helpers.ts",
	"packages/coding-agent/src/modes/components/omfg-panel-helpers.ts",
	"packages/coding-agent/src/modes/components/overlay-box.ts",
	"packages/coding-agent/src/modes/components/pause-screen-helpers.ts",
	"packages/coding-agent/src/modes/components/pause-screen.ts",
	"packages/coding-agent/src/modes/components/plan-review-overlay-helpers.ts",
	"packages/coding-agent/src/modes/components/plugin-settings-helpers.ts",
	"packages/coding-agent/src/modes/components/read-tool-group-helpers.ts",
	"packages/coding-agent/src/modes/components/reset-usage-selector-helpers.ts",
	"packages/coding-agent/src/modes/components/rollback-panel-helpers.ts",
	"packages/coding-agent/src/modes/components/rollback-picker-helpers.ts",
	"packages/coding-agent/src/modes/components/select-list-mouse-routing.ts",
	"packages/coding-agent/src/modes/components/session-selector-helpers.ts",
	"packages/coding-agent/src/modes/components/settings-selector-helpers.ts",
	"packages/coding-agent/src/modes/components/settings-submenus.ts",
	"packages/coding-agent/src/modes/components/settings-submenus/compaction-submenu-helpers.ts",
	"packages/coding-agent/src/modes/components/settings-submenus/compaction-submenu.ts",
	"packages/coding-agent/src/modes/components/settings-submenus/effort-submenu-helpers.ts",
	"packages/coding-agent/src/modes/components/settings-submenus/effort-submenu.ts",
	"packages/coding-agent/src/modes/components/settings-submenus/lsp-submenu.ts",
	"packages/coding-agent/src/modes/components/settings-submenus/model-by-depth-submenu.ts",
	"packages/coding-agent/src/modes/components/settings-submenus/model-chain-submenu-helpers.ts",
	"packages/coding-agent/src/modes/components/settings-submenus/model-chain-submenu.ts",
	"packages/coding-agent/src/modes/components/settings-submenus/model-roles-submenu-helpers.ts",
	"packages/coding-agent/src/modes/components/settings-submenus/model-roles-submenu.ts",
	"packages/coding-agent/src/modes/components/settings-submenus/model-submenu.ts",
	"packages/coding-agent/src/modes/components/settings-submenus/provider-limits-submenu.ts",
	"packages/coding-agent/src/modes/components/settings-submenus/rules-submenu-helpers.ts",
	"packages/coding-agent/src/modes/components/settings-submenus/rules-submenu.ts",
	"packages/coding-agent/src/modes/components/settings-submenus/subagent-agents-submenu-helpers.ts",
	"packages/coding-agent/src/modes/components/settings-submenus/subagent-agents-submenu.ts",
	"packages/coding-agent/src/modes/components/skill-message.ts",
	"packages/coding-agent/src/modes/components/status-line/component-helpers.ts",
	"packages/coding-agent/src/modes/components/tiny-title-download-progress-helpers.ts",
	"packages/coding-agent/src/modes/components/tool-execution-helpers.ts",
	"packages/coding-agent/src/modes/components/transcript-container-helpers.ts",
	"packages/coding-agent/src/modes/components/transcript-note-helpers.ts",
	"packages/coding-agent/src/modes/components/tree-selector-helpers.ts",
	"packages/coding-agent/src/modes/components/user-message-selector-helpers.ts",
	"packages/coding-agent/src/modes/components/welcome-helpers.ts",
	"packages/coding-agent/src/modes/controllers/btw-controller-helpers.ts",
	"packages/coding-agent/src/modes/controllers/command-controller-helpers.ts",
	"packages/coding-agent/src/modes/controllers/event-controller-helpers.ts",
	"packages/coding-agent/src/modes/controllers/extension-ui-controller-helpers.ts",
	"packages/coding-agent/src/modes/controllers/input-controller-helpers.ts",
	"packages/coding-agent/src/modes/controllers/mcp-command-controller-helpers.ts",
	"packages/coding-agent/src/modes/controllers/omfg-controller-helpers.ts",
	"packages/coding-agent/src/modes/controllers/ssh-command-controller-helpers.ts",
	"packages/coding-agent/src/modes/controllers/streaming-reveal-helpers.ts",
	"packages/coding-agent/src/modes/controllers/tan-command-controller-helpers.ts",
	"packages/coding-agent/src/modes/controllers/todo-command-controller-helpers.ts",
	"packages/coding-agent/src/modes/controllers/tool-args-reveal-helpers.ts",
	"packages/coding-agent/src/modes/controllers/welcome-controller-helpers.ts",
	"packages/coding-agent/src/modes/interactive/command-dispatch.ts",
	"packages/coding-agent/src/modes/interactive/event-handlers.ts",
	"packages/coding-agent/src/modes/interactive/goal-mode-controller-helpers.ts",
	"packages/coding-agent/src/modes/interactive/goal-mode-controller.ts",
	"packages/coding-agent/src/modes/interactive/lifecycle.ts",
	"packages/coding-agent/src/modes/interactive/plan-mode-controller-helpers.ts",
	"packages/coding-agent/src/modes/interactive/plan-mode-controller.ts",
	"packages/coding-agent/src/modes/interactive/todo-board-manager.ts",
	"packages/coding-agent/src/modes/interactive/working-loader-manager-helpers.ts",
	"packages/coding-agent/src/modes/interactive/working-loader-manager.ts",
	"packages/coding-agent/src/modes/oauth-manual-input-helpers.ts",
	"packages/coding-agent/src/modes/prompt-action-autocomplete-helpers.ts",
	"packages/coding-agent/src/modes/rpc/host-tools-helpers.ts",
	"packages/coding-agent/src/modes/rpc/host-uris-helpers.ts",
	"packages/coding-agent/src/modes/rpc/rpc-client-helpers.ts",
	"packages/coding-agent/src/modes/rpc/rpc-mode-helpers.ts",
	"packages/coding-agent/src/modes/rpc/rpc-subagents-helpers.ts",
	"packages/coding-agent/src/modes/session-observer-registry-helpers.ts",
	"packages/coding-agent/src/modes/setup-wizard/scenes/agents-helpers.ts",
	"packages/coding-agent/src/modes/setup-wizard/scenes/approvals-helpers.ts",
	"packages/coding-agent/src/modes/setup-wizard/scenes/glyph-helpers.ts",
	"packages/coding-agent/src/modes/setup-wizard/scenes/outro.ts",
	"packages/coding-agent/src/modes/setup-wizard/scenes/sign-in-helpers.ts",
	"packages/coding-agent/src/modes/setup-wizard/scenes/theme-helpers.ts",
	"packages/coding-agent/src/modes/setup-wizard/scenes/web-search-helpers.ts",
	"packages/coding-agent/src/modes/setup-wizard/scenes/wizard-list.ts",
	"packages/coding-agent/src/modes/setup-wizard/startup-splash-helpers.ts",
	"packages/coding-agent/src/modes/setup-wizard/wizard-overlay-helpers.ts",
	"packages/coding-agent/src/modes/skill-command.ts",
	"packages/coding-agent/src/modes/theme/color-helpers.ts",
	"packages/coding-agent/src/modes/theme/theme-class-helpers.ts",
	"packages/coding-agent/src/modes/utils/interactive-context-helpers.ts",
	"packages/coding-agent/src/plan-mode/plan-path.ts",
	"packages/coding-agent/src/provider-boundary-helpers.ts",
	"packages/coding-agent/src/registry/agent-lifecycle-helpers.ts",
	"packages/coding-agent/src/registry/agent-registry-helpers.ts",
	"packages/coding-agent/src/sdk-helpers.ts",
	"packages/coding-agent/src/secrets/audit-helpers.ts",
	"packages/coding-agent/src/secrets/obfuscator-helpers.ts",
	"packages/coding-agent/src/secrets/regex-helpers.ts",
	"packages/coding-agent/src/secrets/secret-command-helpers.ts",
	"packages/coding-agent/src/secrets/secrets-loader.ts",
	"packages/coding-agent/src/secrets/standalone-runtime.ts",
	"packages/coding-agent/src/secrets/vault-helpers.ts",
	"packages/coding-agent/src/security/project-trust-helpers.ts",
	"packages/coding-agent/src/session/agent-session-helpers.ts",
	"packages/coding-agent/src/session/agent-storage-helpers.ts",
	"packages/coding-agent/src/session/background-sessions-helpers.ts",
	"packages/coding-agent/src/session/blob-store-helpers.ts",
	"packages/coding-agent/src/session/classifier-tokens.ts",
	"packages/coding-agent/src/session/cpu-limit-helpers.ts",
	"packages/coding-agent/src/session/history-storage-helpers.ts",
	"packages/coding-agent/src/session/indexed-session-storage-helpers.ts",
	"packages/coding-agent/src/session/operator-notices-helpers.ts",
	"packages/coding-agent/src/session/redis-session-storage-helpers.ts",
	"packages/coding-agent/src/session/session-drafts.ts",
	"packages/coding-agent/src/session/session-entry-index-helpers.ts",
	"packages/coding-agent/src/session/session-entry-index.ts",
	"packages/coding-agent/src/session/session-lifecycle.ts",
	"packages/coding-agent/src/session/session-loader-helpers.ts",
	"packages/coding-agent/src/session/session-manager-helpers.ts",
	"packages/coding-agent/src/session/session-storage-helpers.ts",
	"packages/coding-agent/src/session/side-complete.ts",
	"packages/coding-agent/src/session/sql-session-storage-helpers.ts",
	"packages/coding-agent/src/session/streaming-output-helpers.ts",
	"packages/coding-agent/src/session/tool-choice-queue-helpers.ts",
	"packages/coding-agent/src/session/verification-evidence-ledger-helpers.ts",
	"packages/coding-agent/src/session/write-accounting-helpers.ts",
	"packages/coding-agent/src/session/yield-queue-helpers.ts",
	"packages/coding-agent/src/slash-commands/bare-subcommand.ts",
	"packages/coding-agent/src/slash-commands/builtin-registry-helpers.ts",
	"packages/coding-agent/src/stt/asr-client-helpers.ts",
	"packages/coding-agent/src/stt/asr-worker.ts",
	"packages/coding-agent/src/stt/endpointer-helpers.ts",
	"packages/coding-agent/src/stt/stt-controller-helpers.ts",
	"packages/coding-agent/src/task/agents-helpers.ts",
	"packages/coding-agent/src/task/executor-helpers.ts",
	"packages/coding-agent/src/task/index-helpers.ts",
	"packages/coding-agent/src/task/parallel-helpers.ts",
	"packages/coding-agent/src/task/render-helpers.ts",
	"packages/coding-agent/src/task/subprocess-tool-registry-helpers.ts",
	"packages/coding-agent/src/tiny/title-client-helpers.ts",
	"packages/coding-agent/src/tools/argot-helpers.ts",
	"packages/coding-agent/src/tools/ask-helpers.ts",
	"packages/coding-agent/src/tools/ast-edit-helpers.ts",
	"packages/coding-agent/src/tools/ast-grep-helpers.ts",
	"packages/coding-agent/src/tools/bash-helpers.ts",
	"packages/coding-agent/src/tools/browser-helpers.ts",
	"packages/coding-agent/src/tools/browser/cmux/cmux-tab-helpers.ts",
	"packages/coding-agent/src/tools/browser/cmux/socket-client-helpers.ts",
	"packages/coding-agent/src/tools/browser/handle-release.ts",
	"packages/coding-agent/src/tools/browser/tab-worker-entry.ts",
	"packages/coding-agent/src/tools/browser/tab-worker-helpers.ts",
	"packages/coding-agent/src/tools/checkpoint-helpers.ts",
	"packages/coding-agent/src/tools/conflict-detect-helpers.ts",
	"packages/coding-agent/src/tools/debug-helpers.ts",
	"packages/coding-agent/src/tools/eval-helpers.ts",
	"packages/coding-agent/src/tools/fetch-helpers.ts",
	"packages/coding-agent/src/tools/gh-helpers.ts",
	"packages/coding-agent/src/tools/glob-helpers.ts",
	"packages/coding-agent/src/tools/grep-helpers.ts",
	"packages/coding-agent/src/tools/image-gen-helpers.ts",
	"packages/coding-agent/src/tools/inspect-image-helpers.ts",
	"packages/coding-agent/src/tools/irc-helpers.ts",
	"packages/coding-agent/src/tools/irc-render.ts",
	"packages/coding-agent/src/tools/job-helpers.ts",
	"packages/coding-agent/src/tools/launch-exit-watch-helpers.ts",
	"packages/coding-agent/src/tools/launch-helpers.ts",
	"packages/coding-agent/src/tools/learn-helpers.ts",
	"packages/coding-agent/src/tools/manage-skill-helpers.ts",
	"packages/coding-agent/src/tools/memory-edit-helpers.ts",
	"packages/coding-agent/src/tools/memory-recall-helpers.ts",
	"packages/coding-agent/src/tools/memory-reflect-helpers.ts",
	"packages/coding-agent/src/tools/memory-retain-helpers.ts",
	"packages/coding-agent/src/tools/output-meta-helpers.ts",
	"packages/coding-agent/src/tools/path-utils-helpers.ts",
	"packages/coding-agent/src/tools/read-helpers.ts",
	"packages/coding-agent/src/tools/read-render-helpers.ts",
	"packages/coding-agent/src/tools/reroot-hint-helpers.ts",
	"packages/coding-agent/src/tools/result-notice.ts",
	"packages/coding-agent/src/tools/search-tool-bm25-helpers.ts",
	"packages/coding-agent/src/tools/set-cwd-helpers.ts",
	"packages/coding-agent/src/tools/ssh-helpers.ts",
	"packages/coding-agent/src/tools/todo-helpers.ts",
	"packages/coding-agent/src/tools/todo-markdown-helpers.ts",
	"packages/coding-agent/src/tools/tool-result-helpers.ts",
	"packages/coding-agent/src/tools/vibe-helpers.ts",
	"packages/coding-agent/src/tools/write-helpers.ts",
	"packages/coding-agent/src/tools/yield-helpers.ts",
	"packages/coding-agent/src/tts/downloader.ts",
	"packages/coding-agent/src/tts/speakable-helpers.ts",
	"packages/coding-agent/src/tts/speech-enhancer-helpers.ts",
	"packages/coding-agent/src/tts/streaming-player-helpers.ts",
	"packages/coding-agent/src/tts/tts-client-helpers.ts",
	"packages/coding-agent/src/tts/tts-worker.ts",
	"packages/coding-agent/src/tts/vocalizer-helpers.ts",
	"packages/coding-agent/src/tui/output-block-helpers.ts",
	"packages/coding-agent/src/tui/utils-helpers.ts",
	"packages/coding-agent/src/tui/width-aware-text.ts",
	"packages/coding-agent/src/utils/enhanced-paste-helpers.ts",
	"packages/coding-agent/src/utils/git-helpers.ts",
	"packages/coding-agent/src/utils/image-loading-helpers.ts",
	"packages/coding-agent/src/utils/jj-helpers.ts",
	"packages/coding-agent/src/utils/qrcode-helpers.ts",
	"packages/coding-agent/src/utils/zip-helpers.ts",
	"packages/coding-agent/src/vibe/runtime-helpers.ts",
	"packages/coding-agent/src/web/kagi-helpers.ts",
	"packages/coding-agent/src/web/parallel-helpers.ts",
	"packages/coding-agent/src/web/scrapers/choosealicense.ts",
	"packages/coding-agent/src/web/scrapers/cisa-kev.ts",
	"packages/coding-agent/src/web/scrapers/clojars.ts",
	"packages/coding-agent/src/web/scrapers/crossref.ts",
	"packages/coding-agent/src/web/scrapers/discourse.ts",
	"packages/coding-agent/src/web/scrapers/fdroid.ts",
	"packages/coding-agent/src/web/scrapers/firefox-addons.ts",
	"packages/coding-agent/src/web/scrapers/flathub.ts",
	"packages/coding-agent/src/web/scrapers/jetbrains-marketplace.ts",
	"packages/coding-agent/src/web/scrapers/lemmy.ts",
	"packages/coding-agent/src/web/scrapers/musicbrainz.ts",
	"packages/coding-agent/src/web/scrapers/orcid.ts",
	"packages/coding-agent/src/web/scrapers/rawg.ts",
	"packages/coding-agent/src/web/scrapers/searchcode.ts",
	"packages/coding-agent/src/web/scrapers/snapcraft.ts",
	"packages/coding-agent/src/web/scrapers/sourcegraph.ts",
	"packages/coding-agent/src/web/scrapers/spdx.ts",
	"packages/coding-agent/src/web/scrapers/vscode-marketplace.ts",
	"packages/coding-agent/src/web/search/providers/brave-helpers.ts",
	"packages/coding-agent/src/web/search/providers/codex-helpers.ts",
	"packages/coding-agent/src/web/search/providers/duckduckgo-helpers.ts",
	"packages/coding-agent/src/web/search/providers/firecrawl-helpers.ts",
	"packages/coding-agent/src/web/search/providers/gemini-helpers.ts",
	"packages/coding-agent/src/web/search/providers/google-helpers.ts",
	"packages/coding-agent/src/web/search/providers/jina-helpers.ts",
	"packages/coding-agent/src/web/search/providers/jina.ts",
	"packages/coding-agent/src/web/search/providers/kagi-provider-helpers.ts",
	"packages/coding-agent/src/web/search/providers/kimi-helpers.ts",
	"packages/coding-agent/src/web/search/providers/mojeek-helpers.ts",
	"packages/coding-agent/src/web/search/providers/parallel-helpers.ts",
	"packages/coding-agent/src/web/search/providers/public-helpers.ts",
	"packages/coding-agent/src/web/search/providers/searxng-helpers.ts",
	"packages/coding-agent/src/web/search/providers/startpage-helpers.ts",
	"packages/coding-agent/src/web/search/providers/synthetic-helpers.ts",
	"packages/coding-agent/src/web/search/providers/synthetic.ts",
	"packages/coding-agent/src/web/search/providers/tavily-helpers.ts",
	"packages/coding-agent/src/web/search/providers/tinyfish-helpers.ts",
	"packages/coding-agent/src/web/search/providers/xai-helpers.ts",
	"packages/coding-agent/src/web/search/providers/zai-helpers.ts",
	"packages/coding-agent/src/web/search/web-search-tool-helpers.ts",
	"packages/coding-agent/src/web/search/web-search-tool.ts",
	"packages/collab-web/src/lib/client-helpers.ts",
	"packages/collab-web/src/lib/use-guest.ts",
	"packages/hashline/src/apply-helpers.ts",
	"packages/hashline/src/fs-helpers.ts",
	"packages/hashline/src/input-helpers.ts",
	"packages/hashline/src/mismatch-helpers.ts",
	"packages/hashline/src/parser-helpers.ts",
	"packages/hashline/src/patcher-helpers.ts",
	"packages/hashline/src/recovery-helpers.ts",
	"packages/hashline/src/snapshots-helpers.ts",
	"packages/hashline/src/tokenizer-helpers.ts",
	"packages/metaharness/src/bench-report.ts",
	"packages/metaharness/src/launch-args.ts",
	"packages/metaharness/src/runner-helpers.ts",
	"packages/metaharness/src/server-helpers.ts",
	"packages/metaharness/src/store-helpers.ts",
	"packages/mnemopi/src/cli-helpers.ts",
	"packages/mnemopi/src/core/annotations-helpers.ts",
	"packages/mnemopi/src/core/beam/beam-memory-helpers.ts",
	"packages/mnemopi/src/core/beam/beam-memory.ts",
	"packages/mnemopi/src/core/beam/consolidate-helpers.ts",
	"packages/mnemopi/src/core/binary-vectors-helpers.ts",
	"packages/mnemopi/src/core/episodic-graph-helpers.ts",
	"packages/mnemopi/src/core/extraction/client-helpers.ts",
	"packages/mnemopi/src/core/extraction/diagnostics-helpers.ts",
	"packages/mnemopi/src/core/patterns-helpers.ts",
	"packages/mnemopi/src/core/plugins-helpers.ts",
	"packages/mnemopi/src/core/polyphonic-recall-helpers.ts",
	"packages/mnemopi/src/core/query-cache-helpers.ts",
	"packages/mnemopi/src/core/recall-diagnostics-helpers.ts",
	"packages/mnemopi/src/core/streaming-helpers.ts",
	"packages/mnemopi/src/core/triples-helpers.ts",
	"packages/mnemopi/src/core/veracity-consolidation-helpers.ts",
	"packages/mnemopi/src/mcp-tools-helpers.ts",
	"packages/mnemopi/src/util/ids.ts",
	"packages/simulations/src/cache-sim/harness-helpers.ts",
	"packages/simulations/src/cache-sim/harness.ts",
	"packages/simulations/src/paint-sim/harness-helpers.ts",
	"packages/simulations/src/paint-sim/harness.ts",
	"packages/simulations/src/turn-sim/harness-helpers.ts",
	"packages/simulations/src/turn-sim/invariants.ts",
	"packages/stats/src/client/components/range-meta.ts",
	"packages/stats/src/client/data/charts.ts",
	"packages/stats/src/client/data/useHashRoute.ts",
	"packages/stats/src/client/data/useResource.ts",
	"packages/swarm-extension/src/swarm/pipeline-helpers.ts",
	"packages/swarm-extension/src/swarm/state-helpers.ts",
	"packages/tui/src/autocomplete-helpers.ts",
	"packages/tui/src/bracketed-paste-helpers.ts",
	"packages/tui/src/components/box-helpers.ts",
	"packages/tui/src/components/cancellable-loader.ts",
	"packages/tui/src/components/editor-helpers.ts",
	"packages/tui/src/components/input-helpers.ts",
	"packages/tui/src/components/loader-helpers.ts",
	"packages/tui/src/components/markdown-helpers.ts",
	"packages/tui/src/components/scroll-view-helpers.ts",
	"packages/tui/src/components/select-list-helpers.ts",
	"packages/tui/src/components/settings-list-helpers.ts",
	"packages/tui/src/components/settings-search.ts",
	"packages/tui/src/components/spacer-helpers.ts",
	"packages/tui/src/components/tab-bar-helpers.ts",
	"packages/tui/src/keybindings-helpers.ts",
	"packages/tui/src/latex-block-helpers.ts",
	"packages/tui/src/latex-to-unicode-helpers.ts",
	"packages/tui/src/loop-watchdog-helpers.ts",
	"packages/tui/src/motion-helpers.ts",
	"packages/tui/src/stdin-buffer-helpers.ts",
	"packages/tui/src/terminal-capabilities-helpers.ts",
	"packages/tui/src/tui-helpers.ts",
	"packages/typescript-edit-benchmark/src/edit-prompt-bench.ts",
	"packages/typescript-edit-benchmark/src/goal-budget-context-bench.ts",
	"packages/typescript-edit-benchmark/src/in-process-client-helpers.ts",
	"packages/typescript-edit-benchmark/src/in-process-client.ts",
	"packages/typescript-edit-benchmark/src/mutations-helpers.ts",
	"packages/utils/src/async-helpers.ts",
	"packages/utils/src/cli-helpers.ts",
	"packages/utils/src/file-lock-helpers.ts",
	"packages/utils/src/frontmatter-helpers.ts",
	"packages/utils/src/json-parse-helpers.ts",
	"packages/utils/src/prompt-variables-helpers.ts",
	"packages/utils/src/ptree-helpers.ts",
	"packages/utils/src/strip-ansi-helpers.ts",
	"packages/utils/src/vendor/mermaid-ascii/ascii/ansi.ts",
	"packages/utils/src/vendor/mermaid-ascii/ascii/canvas.ts",
	"packages/utils/src/vendor/mermaid-ascii/ascii/class-diagram.ts",
	"packages/utils/src/vendor/mermaid-ascii/ascii/converter.ts",
	"packages/utils/src/vendor/mermaid-ascii/ascii/draw.ts",
	"packages/utils/src/vendor/mermaid-ascii/ascii/edge-bundling.ts",
	"packages/utils/src/vendor/mermaid-ascii/ascii/edge-routing.ts",
	"packages/utils/src/vendor/mermaid-ascii/ascii/er-diagram.ts",
	"packages/utils/src/vendor/mermaid-ascii/ascii/grid.ts",
	"packages/utils/src/vendor/mermaid-ascii/ascii/multiline-utils.ts",
	"packages/utils/src/vendor/mermaid-ascii/ascii/sequence.ts",
	"packages/utils/src/vendor/mermaid-ascii/ascii/shapes/circle.ts",
	"packages/utils/src/vendor/mermaid-ascii/ascii/shapes/corners.ts",
	"packages/utils/src/vendor/mermaid-ascii/ascii/shapes/hexagon.ts",
	"packages/utils/src/vendor/mermaid-ascii/ascii/shapes/rectangle.ts",
	"packages/utils/src/vendor/mermaid-ascii/ascii/shapes/rounded.ts",
	"packages/utils/src/vendor/mermaid-ascii/ascii/shapes/special.ts",
	"packages/utils/src/vendor/mermaid-ascii/ascii/shapes/stadium.ts",
	"packages/utils/src/vendor/mermaid-ascii/ascii/xychart.ts",
	"packages/utils/src/vendor/mermaid-ascii/multiline-utils.ts",
	"packages/utils/src/vendor/mermaid-ascii/text-metrics.ts",
	"packages/utils/src/vendor/mermaid-ascii/xychart/colors.ts",
	"packages/utils/src/windows-acl.ts",
];

describe("a shipped module arrives with a test that names it", () => {
	it("scans a corpus large enough for the answer to mean anything", () => {
		expect(shippedModules().length).toBeGreaterThan(1500);
		expect(testFiles().length).toBeGreaterThan(3000);
	});

	it("has exactly the recorded set of modules that no test names", () => {
		expect(unnamedModules()).toEqual([...NAMED_BY_NO_TEST]);
	});
});
