/**
 * The committed handbook pages contain the text and links from their Markdown sources.
 *
 * WHY THIS SUITE EXISTS. `docs/handbook/book` is committed build output. Editing a
 * page under `docs/handbook/src` without rebuilding can leave the published handbook
 * behind its source while ordinary package tests remain green. This fast local gate
 * compares source-owned visible text and inline link targets with the corresponding
 * committed HTML page.
 *
 * WHY IT DOES NOT RUN MDBOOK. A test that shells out to `mdbook build` needs the
 * pinned binary, writes into the shared tree, and would have to skip when mdbook is
 * unavailable. The `docs.yml` rebuild-and-diff gate remains authoritative for exact
 * generated bytes, theme assets, removed-only stale HTML, and renderer behavior.
 *
 * This local comparison covers paragraphs, headings, lists, quotes, table cells,
 * inline code and formatting, and inline link/image targets. Fenced code is excluded
 * because syntax highlighting splits its bytes across renderer-owned markup.
 */

import { describe, expect, it } from "bun:test";
import * as fs from "node:fs";
import * as path from "node:path";

const ROOT = path.resolve(import.meta.dir, "..");
const SRC = path.join(ROOT, "docs", "handbook", "src");
const BOOK = path.join(ROOT, "docs", "handbook", "book");

/** Every handbook page source, `SUMMARY.md` excluded: it renders into the nav, not a page. */
function sourcePages(dir: string = SRC, found: string[] = []): string[] {
	for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
		const full = path.join(dir, entry.name);
		if (entry.isDirectory()) sourcePages(full, found);
		else if (entry.name.endsWith(".md") && entry.name !== "SUMMARY.md") found.push(full);
	}
	return found;
}

/** The built page for a source page. */
function bookPageFor(source: string): string {
	return path.join(BOOK, path.relative(SRC, source).replace(/\.md$/, ".html"));
}

/**
 * Readable text from a rendered page.
 *
 * A tag becomes a SPACE rather than nothing, because `<code>x</code>.` and `x.` are
 * different strings and collapsing the tag to nothing would silently join words that
 * the browser shows apart.
 */
function readableText(html: string): string {
	return html
		.replace(/<script[\s\S]*?<\/script>/g, " ")
		.replace(/<style[\s\S]*?<\/style>/g, " ")
		.replace(/<[^>]+>/g, " ")
		.replace(/&quot;/g, '"')
		.replace(/&#39;/g, "'")
		.replace(/&amp;/g, "&")
		.replace(/&lt;/g, "<")
		.replace(/&gt;/g, ">")
		.replace(/&nbsp;/g, " ")
		.replace(/\s+/g, " ");
}

/**
 * Fold the transformations mdbook applies to punctuation.
 *
 * Smart punctuation is on, so `'` arrives as `’`, `"` as `“ ”` and `--` as `–`. All
 * of them fold back to ASCII on BOTH sides, and dash runs collapse so a source `--`
 * matches a rendered en dash.
 */
function foldPunctuation(text: string): string {
	return text
		.replace(/[‘’]/g, "'")
		.replace(/[“”]/g, '"')
		.replace(/[–—]/g, "-")
		.replace(/…/g, "...")
		.replace(/-+/g, "-");
}

/** How many words ordinary prose needs before a coincidental match stops being plausible. */
const RUN_WORDS = 8;

/** Fold source presentation and punctuation into browser-visible word sequences. */
function visibleMarkdownText(text: string): string {
	return text
		.replace(/!\[([^\]]*)\]\([^)]*\)/g, "$1")
		.replace(/\[([^\]]+)\]\([^)]*\)/g, "$1")
		.replace(/[`*_~{}]/g, "")
		.replace(/\\([\\`*_[\]{}()#+\-.!|>])/g, "$1")
		.replace(/[^\p{L}\p{N}']+/gu, " ")
		.replace(/\s+/g, " ")
		.trim();
}

/**
 * Visible source text runs.
 *
 * Structural lines are exact contracts even when short. Ordinary prose keeps the
 * longer threshold to avoid matching tiny fragments split by source line wrapping.
 */
export function sourceTextRuns(markdown: string): string[] {
	const runs: string[] = [];
	let insideFence = false;
	const presentationFolded = foldPunctuation(markdown)
		.replace(/!\[([^\]]*)\]\([^)]*\)/g, "$1")
		.replace(/\[([^\]]+)\]\([^)]*\)/g, "$1");
	for (const raw of presentationFolded.split("\n")) {
		const trimmed = raw.trim();
		if (trimmed.startsWith("```")) {
			insideFence = !insideFence;
			continue;
		}
		if (insideFence || !trimmed) continue;
		const structural = /^(?:#{1,6}\s|>\s?|[-*+]\s|\d+\.\s|\|)/.test(trimmed);
		if (/^\|?(?:\s*:?-+:?\s*\|)+\s*$/.test(trimmed)) continue;
		const withoutPrefix = trimmed
			.replace(/^#{1,6}\s+/, "")
			.replace(/^>\s?/, "")
			.replace(/^(?:[-*+]|\d+\.)\s+/, "");
		const pieces = trimmed.includes("|")
			? withoutPrefix
					.split("|")
					.map(part => part.trim())
					.filter(Boolean)
			: [withoutPrefix];
		for (const piece of pieces) {
			const visible = visibleMarkdownText(piece);
			const words = visible.split(/\s+/).filter(Boolean);
			if (visible && (structural || words.length >= RUN_WORDS)) runs.push(visible);
		}
	}
	return runs;
}

interface SourceTarget {
	attribute: "href" | "src";
	target: string;
}

/** Inline Markdown links and images whose destination is source-owned. */
export function sourceTargets(markdown: string): SourceTarget[] {
	const targets: SourceTarget[] = [];
	const pattern = /(!?)\[[^\]]*\]\(\s*<?([^\s)>]+)>?(?:\s+["'][^)]*["'])?\s*\)/g;
	for (const match of markdown.matchAll(pattern)) {
		const target = match[2];
		if (!target) continue;
		targets.push({
			attribute: match[1] === "!" ? "src" : "href",
			target: /^[a-z][a-z\d+.-]*:/i.test(target) ? target : target.replace(/\.md(?=([?#]|$))/, ".html"),
		});
	}
	return targets;
}

interface Stale {
	page: string;
	run: string;
}

/** Link and image destinations emitted by the rendered page. */
function renderedTargets(html: string): Set<string> {
	const targets = new Set<string>();
	for (const match of html.matchAll(/\b(href|src)="([^"]*)"/g)) {
		const attribute = match[1];
		const target = match[2]
			?.replace(/&quot;/g, '"')
			.replace(/&#39;/g, "'")
			.replace(/&amp;/g, "&")
			.replace(/&lt;/g, "<")
			.replace(/&gt;/g, ">");
		if (attribute && target) targets.add(`${attribute}:${target}`);
	}
	return targets;
}

function staleSourceContracts(): { checked: number; checkedTargets: number; stale: Stale[] } {
	const stale: Stale[] = [];
	let checked = 0;
	let checkedTargets = 0;
	for (const source of sourcePages()) {
		const page = bookPageFor(source);
		const relative = path.relative(ROOT, page);
		if (!fs.existsSync(page)) {
			stale.push({ page: relative, run: "(no built page at all)" });
			continue;
		}
		const sourceMarkdown = fs.readFileSync(source, "utf8");
		const pageHtml = fs.readFileSync(page, "utf8");
		const rendered = visibleMarkdownText(foldPunctuation(readableText(pageHtml)));
		for (const run of sourceTextRuns(sourceMarkdown)) {
			checked += 1;
			if (!rendered.includes(run)) stale.push({ page: relative, run });
		}
		const targets = renderedTargets(pageHtml);
		for (const { attribute, target } of sourceTargets(sourceMarkdown)) {
			checkedTargets += 1;
			if (!targets.has(`${attribute}:${target}`)) {
				stale.push({ page: relative, run: `(missing ${attribute}="${target}")` });
			}
		}
	}
	return { checked, checkedTargets, stale };
}

describe("the committed handbook contains source-owned text and links", () => {
	/**
	 * The scan reads both trees. A walk that found no pages, text, or destinations
	 * would satisfy the comparison while checking nothing.
	 */
	it("reads every handbook page and finds text and links", () => {
		const pages = sourcePages();
		const { checked, checkedTargets } = staleSourceContracts();

		expect(pages.length).toBeGreaterThan(50);
		expect(checked).toBeGreaterThan(1000);
		expect(checkedTargets).toBeGreaterThan(100);
		expect(pages.some(page => path.basename(page) === "subagents.md")).toBe(true);
	});

	/**
	 * A failure names the page and missing source-owned contract. Rebuilding with the
	 * pinned mdbook version is the only accepted repair.
	 */
	it("has no source text or destination missing from its built page", () => {
		const { stale } = staleSourceContracts();

		expect(
			stale.map(entry => `${entry.page}: ${entry.run.slice(0, 100)}`),
			"the committed book is behind its source. Run `mdbook build docs/handbook` (v0.5.2, pinned in docs.yml) and commit the result.",
		).toEqual([]);
	});

	/**
	 * Every source page has a built page. A source added without a rebuild produces
	 * no HTML at all, which the rule above reports but which is worth its own check
	 * because the cause and the message differ: nothing to compare rather than a
	 * comparison that failed.
	 */
	it("has a built page for every source page", () => {
		const missing = sourcePages()
			.filter(source => !fs.existsSync(bookPageFor(source)))
			.map(source => path.relative(ROOT, source));

		expect(missing).toEqual([]);
	});
});

describe("the source contract extractor follows visible Markdown semantics", () => {
	/**
	 * Fenced code is skipped because mdbook's syntax highlighter splits it across
	 * renderer-owned spans.
	 */
	it("takes no run out of a fenced code block", () => {
		const source = [
			"```ts",
			"const example = someFunction(withArguments, andMore, andEvenMore, plusOne);",
			"```",
			"This is ordinary prose with more than eight words in it.",
		].join("\n");

		expect(sourceTextRuns(source)).toEqual(["This is ordinary prose with more than eight words in it"]);
	});

	/**
	 * Short structural text carries operator contracts such as option names and table
	 * defaults, so every visible heading, list item, quote, and cell is retained.
	 */
	it("keeps headings, list items, quotes, and table cells", () => {
		const source = ["# Install", "- default: off", "| Setting | Default |", "> Read this first."].join("\n");

		expect(sourceTextRuns(source)).toEqual(["Install", "default off", "Setting", "Default", "Read this first"]);
	});

	/** Inline presentation disappears while its visible label and code remain. */
	it("normalizes inline markdown into the rendered sentence", () => {
		const source =
			"The setting `subagent.model` decides which [model](./models.md) a spawned agent runs on by default.";

		expect(sourceTextRuns(source)).toEqual([
			"The setting subagent model decides which model a spawned agent runs on by default",
		]);
		expect(sourceTargets(source)).toEqual([{ attribute: "href", target: "./models.html" }]);
	});

	/**
	 * Smart punctuation folds on the source side, which makes apostrophes and mdbook's
	 * generated en dashes compare with their ASCII source.
	 */
	it("folds smart punctuation so an apostrophe is not a difference", () => {
		const source = "A subagent inherits that project's configuration when it starts there.";

		expect(sourceTextRuns(source)[0]).toContain("project's");
		expect(foldPunctuation("project’s")).toBe("project's");
		expect(foldPunctuation("gated on – your personality")).toBe("gated on - your personality");
	});

	/**
	 * And a tag becomes a space rather than nothing, so a word ending a code span
	 * does not get glued to the word after it.
	 */
	it("reads a tag as a separator", () => {
		expect(readableText("<p>one<code>two</code>three</p>")).toBe(" one two three ");
	});

	/**
	 * The non-vacuity twin for the whole comparison: a sentence that is NOT in a
	 * page really is reported. Without this, an extractor that returned nothing
	 * would make the rule above pass forever.
	 */
	it("reports a run the page does not contain", () => {
		const page = readableText(fs.readFileSync(bookPageFor(path.join(SRC, "features", "subagents.md")), "utf8"));

		expect(page).not.toContain("this sentence has never appeared in the handbook at all");
	});
});
