import { describe, expect, it } from "bun:test";
import * as fs from "node:fs";
import * as path from "node:path";

/**
 * Both installers must leave the user with working tab completion, and must be
 * able to take it back.
 *
 * Windows had none at all. The three POSIX shells each autoload a file by
 * command name, which is what install.sh writes; PowerShell has no such
 * directory, so its completion is registered at runtime by a script the profile
 * dot-sources. That structural difference is why the Windows half was missing
 * rather than merely untested, and it is why the two halves cannot share code.
 * This suite is what keeps them from drifting.
 *
 * The POSIX behavior runs for real in scripts/install-tests/functions.test.sh.
 * pwsh is not available on the Linux development host, so the Windows half is
 * asserted against the script source here and exercised behaviorally in
 * scripts/install-tests/functions.test.ps1 when a Windows host runs it.
 */

const repoRoot = path.resolve(import.meta.dir, "..");
const installSh = fs.readFileSync(path.join(repoRoot, "scripts", "install.sh"), "utf8");
const installPs1 = fs.readFileSync(path.join(repoRoot, "scripts", "install.ps1"), "utf8");

/** A named PowerShell function's body, from its opening line to the next one. */
function psFn(source: string, name: string): string {
	const from = source.indexOf(`function ${name} {`);
	expect(from, `missing function ${name}`).toBeGreaterThan(-1);
	const to = source.indexOf("\nfunction ", from + 1);
	return source.slice(from, to === -1 ? undefined : to);
}

/** A named POSIX shell function's body, so a call site is asserted inside the
 * install path that owns it rather than anywhere in the file. */
function shFn(name: string): string {
	const from = installSh.indexOf(`${name}() {`);
	expect(from, `missing function ${name}`).toBeGreaterThan(-1);
	const to = installSh.indexOf("\n}\n", from);
	return installSh.slice(from, to === -1 ? undefined : to);
}

describe("every installer installs completions for the shells its platform has", () => {
	it("install.sh writes one file per POSIX shell, generated by the installed binary", () => {
		expect(installSh).toContain("install_completions() {");
		expect(installSh).toContain("for sh in bash zsh fish; do");
		expect(installSh).toContain('out=$(completions_dir_for "$sh")');
		expect(installSh).toContain('"$bin" completions "$sh" $alias_flag > "$tmp"');
	});

	it("install.ps1 generates the PowerShell script from the binary it just installed", () => {
		// Generating from the installed binary rather than shipping a static
		// script is what keeps completions from describing a different version
		// than the one on disk.
		expect(installPs1).toContain("function Install-Completions {");
		expect(installPs1).toContain("$generated = & $BinPath completions powershell 2>$null");
	});

	/**
	 * Each installer used to have two consumer paths that could drift — a binary
	 * install and a source build — and the source one was the half that had been
	 * left without completions. The source build is gone. The paths that remain
	 * are the release download and the `--local`/`-Local` install of a binary
	 * this checkout already built, and each still has to leave the user with
	 * working tab completion.
	 */
	it("install.ps1 installs completions on both surviving install paths", () => {
		expect(psFn(installPs1, "Install-Binary")).toContain("Install-Completions -BinPath $OutPath");
		expect(psFn(installPs1, "Install-LocalBinary")).toContain("Install-Completions -BinPath $OutPath");
	});

	it("install.sh installs completions on both surviving install paths", () => {
		expect(shFn("install_binary")).toContain('install_completions "$(install_dir)/$BIN_NAME"');
		expect(shFn("install_local")).toContain('install_completions "$(install_dir)/$BIN_NAME"');
	});

	it("neither installer still has a source-install path to install them on", () => {
		// The removed spellings, named so the branch cannot come back by
		// copy-paste and quietly acquire a third completions call site.
		expect(installPs1).not.toContain("Install-Completions -BinPath $shim");
		expect(installPs1).not.toContain("function Install-FromSource {");
		expect(installSh).not.toContain("install_via_bun");
		expect(installSh).not.toContain("fetch_source_tree");
	});

	it("both refuse to install an empty or failed generation", () => {
		// Writing an empty completion file replaces working completions with
		// nothing and reports success: the silent degrade this codebase forbids.
		expect(installSh).toContain('[ -s "$tmp" ]');
		expect(installPs1).toContain("if ($LASTEXITCODE -ne 0 -or -not $generated) {");
	});

	it("both say so out loud when completions could not be installed", () => {
		expect(installSh).toContain("could not generate $sh completions (skipped)");
		expect(installPs1).toContain("could not generate PowerShell completions (tab completion unavailable)");
	});

	it("both write through a temporary file before moving into place", () => {
		// A completion script is read at shell startup, so a half-written one
		// breaks every terminal the user opens until they find and delete it.
		expect(installSh).toContain('tmp="$out/.$name.$$"');
		const fn = psFn(installPs1, "Install-Completions");
		expect(fn).toContain('$staging = "$scriptPath.$PID.new"');
		expect(fn).toContain("Move-Item -LiteralPath $staging -Destination $scriptPath -Force");
	});
});

describe("the PowerShell profile edit is surgical and reversible", () => {
	it("the dot-source line has exactly one owner, shared by install and uninstall", () => {
		// If the removal guessed at the text the install wrote, it would either
		// leave the line forever or delete one the user typed themselves.
		expect(installPs1).toContain("function Get-CompletionSourceLine {");
		expect(installPs1).toContain(
			"Add-CompletionSourceLine -ProfilePath (Get-ProfilePath) -Line (Get-CompletionSourceLine $scriptPath)",
		);
		expect(installPs1).toContain(
			"Remove-CompletionSourceLine -ProfilePath (Get-ProfilePath) -Line (Get-CompletionSourceLine $scriptPath)",
		);
	});

	it("the line is written under the same marker comment install.sh uses", () => {
		// One phrase across both installers, so a user grepping their dotfiles
		// finds every line veyyon added with one search.
		expect(installSh).toContain('PATH_MARKER="# added by the veyyon installer"');
		expect(installPs1).toContain('$CompletionMarker = "# added by the veyyon installer"');
	});

	it("the line is added only once, however many times the installer runs", () => {
		const fn = psFn(installPs1, "Add-CompletionSourceLine");
		expect(fn).toContain("if ($existing -contains $Line) { return $false }");
	});

	it("removal drops the exact line and its marker, and nothing else", () => {
		// A profile is a file the user edits by hand; a broad match would take
		// their own configuration with it.
		const fn = psFn(installPs1, "Remove-CompletionSourceLine");
		expect(fn).toContain("if ($l -eq $Line) { $pending = $null; continue }");
		expect(fn).toContain("$pending = if ($l -eq $CompletionMarker) { $l } else { $null }");
	});

	it("removal leaves a profile that never held the line untouched", () => {
		// Rewriting the file anyway would rewrite its line endings and its final
		// newline for a user who never installed completions.
		const fn = psFn(installPs1, "Remove-CompletionSourceLine");
		expect(fn).toContain("if (-not ($lines -contains $Line)) { return $false }");
	});

	it("it targets the profile that loads in every host, not just the console", () => {
		// $PROFILE alone is the current host's profile, so completions would be
		// missing in the VS Code terminal and in the ISE.
		expect(installPs1).toContain("return $PROFILE.CurrentUserAllHosts");
	});
});

describe("uninstall reclaims the completions it wrote", () => {
	it("install.ps1 removes the script file and the profile line", () => {
		expect(installPs1).toContain("function Remove-Completions {");
		const fn = psFn(installPs1, "Remove-Completions");
		expect(fn).toContain("Remove-Item -Force $scriptPath");
		expect(installPs1).toContain("if (Remove-Completions) { $removed = $true }");
	});

	it("install.sh removes one completion file per shell", () => {
		expect(installSh).toContain('completion_file_for "$sh" "$BIN_NAME"');
	});
});

/**
 * Both installers rewrite a file the user owns by truncating it first, so a
 * failure partway leaves that file empty. install.sh's rc rewrite used to
 * delete its temp copy in exactly that case, destroying a file it had just
 * emptied; the PowerShell profile rewrite had no copy at all.
 */
describe("a failed profile or rc rewrite leaves the user a way back", () => {
	it("install.ps1 copies the profile before it truncates it", () => {
		const fn = psFn(installPs1, "Remove-CompletionSourceLine");
		expect(fn).toContain('$backup = "$ProfilePath.veyyon-uninstall.$PID"');
		expect(fn.indexOf("Copy-Item -LiteralPath $ProfilePath -Destination $backup")).toBeLessThan(
			fn.indexOf("Set-Content -LiteralPath $ProfilePath -Value $kept"),
		);
	});

	it("install.ps1 keeps that copy when the rewrite fails, and names it", () => {
		const fn = psFn(installPs1, "Remove-CompletionSourceLine");
		expect(fn).toContain("its previous contents are in $backup");
		expect(fn).toContain("restore it with: Copy-Item '$backup' '$ProfilePath'");
	});

	it("install.ps1 leaves the profile alone when it cannot even take a copy", () => {
		// Truncating a file you could not copy is the one outcome with no way back.
		const fn = psFn(installPs1, "Remove-CompletionSourceLine");
		expect(fn).toContain("could not back up $ProfilePath");
		expect(fn.indexOf("could not back up")).toBeLessThan(fn.indexOf("Set-Content -LiteralPath $ProfilePath"));
	});

	it("install.ps1 removes the copy once the rewrite succeeds", () => {
		const fn = psFn(installPs1, "Remove-CompletionSourceLine");
		expect(fn).toContain("Remove-Item -Force $backup -ErrorAction SilentlyContinue");
	});

	it("install.sh keeps its temp on the same failure, under the same name", () => {
		// One recognizable suffix across both platforms: a user grepping for
		// leftovers finds them with one pattern.
		expect(installSh).toContain('tmp="$rc.veyyon-uninstall.$$"');
		expect(installPs1).toContain('"$ProfilePath.veyyon-uninstall.$PID"');
	});
});

/**
 * The `.sha256` sidecar is the only thing standing between a user and a binary
 * someone else served, and four separate readers of it exist: install.sh,
 * install.ps1, the self-updater, and the native-addon provisioning. The two
 * TypeScript ones share a single owner (packages/natives/src/sha256-sidecar.ts);
 * the two shell ones cannot import it, so they are held to the same contract
 * here and behaviorally in each installer's own suite.
 *
 * They were not equal before. Both shell readers took the first whitespace
 * token whatever it was, so an HTML error page or a sidecar truncated by a
 * dropped connection was compared against the real digest and reported as
 * "checksum mismatch" — a corrupt-download story for a download that was fine.
 */
describe("every sidecar reader agrees on what a digest is", () => {
	it("both installers require exactly 64 hex characters", () => {
		expect(installSh).toContain("parse_sha256_sidecar() {");
		expect(installSh).toContain("$1 ~ /^[0-9a-fA-F]{64}$/");
		expect(installPs1).toContain("if ($token -notmatch '^[0-9a-fA-F]{64}$') { return $null }");
	});

	it("both read the FIRST line only, so a concatenated sidecar cannot verify the wrong asset", () => {
		expect(installSh).toContain("NR == 1 {");
		expect(installPs1).toContain("(($Text -split \"`n\")[0].Trim() -split '\\s+')[0]");
	});

	it("both lowercase the digest they return", () => {
		expect(installSh).toContain("print tolower($1)");
		expect(installPs1).toContain("return $token.ToLower()");
	});

	it("install.sh compares both sides lowercased, so hex case is never tampering", () => {
		// sha256sum emits lowercase; a sidecar written in uppercase hex described
		// the same bytes and was refused as a tampered binary.
		//
		// The two sides are lowercased in different places, and both are pinned
		// here. `expected` comes off the wire, so verify_sha256 folds it itself.
		// `actual` is computed locally and now comes back through
		// `sha256_of_file` -> `sha256_of_stdin` -> `parse_sha256_sidecar`, whose
		// `tolower` is the SAME fold the sidecar reader applies, which is why the
		// old explicit `tr` on `actual` was removed rather than kept as a second
		// spelling. Pinning the call chain keeps that route asserted: reintroduce a
		// raw `sha256sum | awk` in verify_sha256 and this fails, because the fold
		// would then be gone with nothing naming its absence.
		expect(installSh).toContain(`actual=$(sha256_of_file "$file")`);
		expect(installSh).toContain('_sha_digest=$(parse_sha256_sidecar "$_sha_output")');
		expect(installSh).toContain(`expected=$(printf '%s' "$expected" | tr 'A-F' 'a-f')`);
	});

	it("one sha256 implementation serves the download gate and the ownership receipts", () => {
		// Ownership receipts record a digest of the artifact they describe, so the
		// installer now hashes for two reasons. Two tool dispatches would be two
		// chances to disagree about what a digest is, on a machine where only one
		// of sha256sum/shasum exists. `verify_sha256` reads the shared helper, and
		// so does `artifact_identity`.
		expect(installSh).toContain("sha256_of_stdin() {");
		expect(installSh).toContain(`sha256_of_file() {\n    sha256_of_stdin < "$1"\n}`);
		expect(installSh).toContain('_identity_hash=$(sha256_of_file "$_identity_path") || return 1');
		expect(installSh).toContain('_identity_hash=$(sha256_of_text "$_identity_target") || return 1');
	});

	it("both point at the one TypeScript owner rather than describing their own rule", () => {
		// A reader that explains the contract in its own words is a reader that
		// drifts from it.
		expect(installSh).toContain("packages/natives/src/sha256-sidecar.ts");
		expect(installPs1).toContain("packages/natives/src/sha256-sidecar.ts");
	});

	it("neither installer still parses a sidecar with a bare first-token grab", () => {
		// The exact shape that was wrong, so it cannot come back by copy-paste.
		expect(installSh).not.toContain(`expected=$(printf '%s' "$sum" | awk '{print $1}')`);
		expect(installPs1).not.toContain("$token = ($Text.Trim() -split '\\s+')[0]");
	});
});
