use serde::{Deserialize, Serialize};

use crate::action::HostAction;

/// Discriminant enum for host actions.
#[derive(
	Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash, Serialize, Deserialize, strum::EnumIter,
)]
pub enum HostActionKind {
	Attach,
	Detach,
	RetryConnection,
	Shutdown,
	PauseAgents,
	ResumeAgents,
	ListSessions,
	SearchSessions,
	PreviewSessionTranscript,
	OpenSession,
	CreateSession,
	RenameSession,
	DeleteSession,
	BranchSession,
	ExportSession,
	CompactSession,
	HandoffSession,
	LoadTranscript,
	SubmitPrompt,
	Steer,
	FollowUp,
	AbortTurn,
	RetryTurn,
	RephraseReply,
	ReviewPlan,
	SetQueueMode,
	SetSessionMode,
	CancelTool,
	SetToolViewExpanded,
	DequeueQueuedPrompt,
	RespondToInteraction,
	LoadFileTree,
	ReadFile,
	SearchFiles,
	SearchContent,
	OpenExternal,
	RefreshChanges,
	SelectChangeScope,
	CreateTerminal,
	AttachTerminal,
	WriteTerminal,
	ResizeTerminal,
	RestartTerminal,
	ClearTerminal,
	CloseTerminal,
	RefreshProcesses,
	ProcessLogs,
	ProcessSend,
	ProcessSignal,
	ProcessStop,
	ProcessRestart,
	ProcessStart,
	RefreshModels,
	SelectModel,
	SetThinkingLevel,
	RefreshProviders,
	StartProviderAuth,
	SubmitAuthSecret,
	OpenAuthUrl,
	CancelAuthFlow,
	RetryAuthFlow,
	RefreshMcp,
	SetMcpEnabled,
	RefreshAgents,
	ReviveAgent,
	SpawnTask,
	CancelTask,
	ListCommands,
	RunCommand,
	LoadSettings,
	SetSetting,
	ResetSetting,
	LoadThemes,
	LoadKeybindings,
	SetKeybinding,
	RefreshDiagnostics,
	RetryDiagnosticSource,
	ClearOutput,
	GetUsage,
	GetContextBreakdown,
	SetGoal,
	ControlGoal,
	StartShare,
	StopShare,
	RefreshShare,
}

impl HostActionKind {
	/// Complete slice of action kinds for runtime test sweeps.
	pub const ALL: [Self; 85] = [
		Self::Attach,
		Self::Detach,
		Self::RetryConnection,
		Self::Shutdown,
		Self::PauseAgents,
		Self::ResumeAgents,
		Self::ListSessions,
		Self::SearchSessions,
		Self::PreviewSessionTranscript,
		Self::OpenSession,
		Self::CreateSession,
		Self::RenameSession,
		Self::DeleteSession,
		Self::BranchSession,
		Self::ExportSession,
		Self::CompactSession,
		Self::HandoffSession,
		Self::LoadTranscript,
		Self::SubmitPrompt,
		Self::Steer,
		Self::FollowUp,
		Self::AbortTurn,
		Self::RetryTurn,
		Self::RephraseReply,
		Self::ReviewPlan,
		Self::SetQueueMode,
		Self::SetSessionMode,
		Self::CancelTool,
		Self::SetToolViewExpanded,
		Self::DequeueQueuedPrompt,
		Self::RespondToInteraction,
		Self::LoadFileTree,
		Self::ReadFile,
		Self::SearchFiles,
		Self::SearchContent,
		Self::OpenExternal,
		Self::RefreshChanges,
		Self::SelectChangeScope,
		Self::CreateTerminal,
		Self::AttachTerminal,
		Self::WriteTerminal,
		Self::ResizeTerminal,
		Self::RestartTerminal,
		Self::ClearTerminal,
		Self::CloseTerminal,
		Self::RefreshProcesses,
		Self::ProcessLogs,
		Self::ProcessSend,
		Self::ProcessSignal,
		Self::ProcessStop,
		Self::ProcessRestart,
		Self::ProcessStart,
		Self::RefreshModels,
		Self::SelectModel,
		Self::SetThinkingLevel,
		Self::RefreshProviders,
		Self::StartProviderAuth,
		Self::SubmitAuthSecret,
		Self::OpenAuthUrl,
		Self::CancelAuthFlow,
		Self::RetryAuthFlow,
		Self::RefreshMcp,
		Self::SetMcpEnabled,
		Self::RefreshAgents,
		Self::ReviveAgent,
		Self::SpawnTask,
		Self::CancelTask,
		Self::ListCommands,
		Self::RunCommand,
		Self::LoadSettings,
		Self::SetSetting,
		Self::ResetSetting,
		Self::LoadThemes,
		Self::LoadKeybindings,
		Self::SetKeybinding,
		Self::RefreshDiagnostics,
		Self::RetryDiagnosticSource,
		Self::ClearOutput,
		Self::GetUsage,
		Self::GetContextBreakdown,
		Self::SetGoal,
		Self::ControlGoal,
		Self::StartShare,
		Self::StopShare,
		Self::RefreshShare,
	];

	/// Returns wire name identifier.
	#[must_use]
	pub const fn as_str(self) -> &'static str {
		match self {
			Self::Attach => "Attach",
			Self::Detach => "Detach",
			Self::RetryConnection => "RetryConnection",
			Self::Shutdown => "Shutdown",
			Self::PauseAgents => "PauseAgents",
			Self::ResumeAgents => "ResumeAgents",
			Self::ListSessions => "ListSessions",
			Self::SearchSessions => "SearchSessions",
			Self::PreviewSessionTranscript => "PreviewSessionTranscript",
			Self::OpenSession => "OpenSession",
			Self::CreateSession => "CreateSession",
			Self::RenameSession => "RenameSession",
			Self::DeleteSession => "DeleteSession",
			Self::BranchSession => "BranchSession",
			Self::ExportSession => "ExportSession",
			Self::CompactSession => "CompactSession",
			Self::HandoffSession => "HandoffSession",
			Self::LoadTranscript => "LoadTranscript",
			Self::SubmitPrompt => "SubmitPrompt",
			Self::Steer => "Steer",
			Self::FollowUp => "FollowUp",
			Self::AbortTurn => "AbortTurn",
			Self::RetryTurn => "RetryTurn",
			Self::RephraseReply => "RephraseReply",
			Self::ReviewPlan => "ReviewPlan",
			Self::SetQueueMode => "SetQueueMode",
			Self::SetSessionMode => "SetSessionMode",
			Self::CancelTool => "CancelTool",
			Self::SetToolViewExpanded => "SetToolViewExpanded",
			Self::DequeueQueuedPrompt => "DequeueQueuedPrompt",
			Self::RespondToInteraction => "RespondToInteraction",
			Self::LoadFileTree => "LoadFileTree",
			Self::ReadFile => "ReadFile",
			Self::SearchFiles => "SearchFiles",
			Self::SearchContent => "SearchContent",
			Self::OpenExternal => "OpenExternal",
			Self::RefreshChanges => "RefreshChanges",
			Self::SelectChangeScope => "SelectChangeScope",
			Self::CreateTerminal => "CreateTerminal",
			Self::AttachTerminal => "AttachTerminal",
			Self::WriteTerminal => "WriteTerminal",
			Self::ResizeTerminal => "ResizeTerminal",
			Self::RestartTerminal => "RestartTerminal",
			Self::ClearTerminal => "ClearTerminal",
			Self::CloseTerminal => "CloseTerminal",
			Self::RefreshProcesses => "RefreshProcesses",
			Self::ProcessLogs => "ProcessLogs",
			Self::ProcessSend => "ProcessSend",
			Self::ProcessSignal => "ProcessSignal",
			Self::ProcessStop => "ProcessStop",
			Self::ProcessRestart => "ProcessRestart",
			Self::ProcessStart => "ProcessStart",
			Self::RefreshModels => "RefreshModels",
			Self::SelectModel => "SelectModel",
			Self::SetThinkingLevel => "SetThinkingLevel",
			Self::RefreshProviders => "RefreshProviders",
			Self::StartProviderAuth => "StartProviderAuth",
			Self::SubmitAuthSecret => "SubmitAuthSecret",
			Self::OpenAuthUrl => "OpenAuthUrl",
			Self::CancelAuthFlow => "CancelAuthFlow",
			Self::RetryAuthFlow => "RetryAuthFlow",
			Self::RefreshMcp => "RefreshMcp",
			Self::SetMcpEnabled => "SetMcpEnabled",
			Self::RefreshAgents => "RefreshAgents",
			Self::ReviveAgent => "ReviveAgent",
			Self::SpawnTask => "SpawnTask",
			Self::CancelTask => "CancelTask",
			Self::ListCommands => "ListCommands",
			Self::RunCommand => "RunCommand",
			Self::LoadSettings => "LoadSettings",
			Self::SetSetting => "SetSetting",
			Self::ResetSetting => "ResetSetting",
			Self::LoadThemes => "LoadThemes",
			Self::LoadKeybindings => "LoadKeybindings",
			Self::SetKeybinding => "SetKeybinding",
			Self::RefreshDiagnostics => "RefreshDiagnostics",
			Self::RetryDiagnosticSource => "RetryDiagnosticSource",
			Self::ClearOutput => "ClearOutput",
			Self::GetUsage => "GetUsage",
			Self::GetContextBreakdown => "GetContextBreakdown",
			Self::SetGoal => "SetGoal",
			Self::ControlGoal => "ControlGoal",
			Self::StartShare => "StartShare",
			Self::StopShare => "StopShare",
			Self::RefreshShare => "RefreshShare",
		}
	}
}

impl HostAction {
	/// Resolves the discriminant kind for this action.
	#[must_use]
	pub const fn kind(&self) -> HostActionKind {
		match self {
			Self::Attach { .. } => HostActionKind::Attach,
			Self::Detach => HostActionKind::Detach,
			Self::RetryConnection => HostActionKind::RetryConnection,
			Self::Shutdown => HostActionKind::Shutdown,
			Self::PauseAgents => HostActionKind::PauseAgents,
			Self::ResumeAgents => HostActionKind::ResumeAgents,
			Self::ListSessions => HostActionKind::ListSessions,
			Self::SearchSessions { .. } => HostActionKind::SearchSessions,
			Self::PreviewSessionTranscript { .. } => HostActionKind::PreviewSessionTranscript,
			Self::OpenSession { .. } => HostActionKind::OpenSession,
			Self::CreateSession { .. } => HostActionKind::CreateSession,
			Self::RenameSession { .. } => HostActionKind::RenameSession,
			Self::DeleteSession { .. } => HostActionKind::DeleteSession,
			Self::BranchSession { .. } => HostActionKind::BranchSession,
			Self::ExportSession { .. } => HostActionKind::ExportSession,
			Self::CompactSession { .. } => HostActionKind::CompactSession,
			Self::HandoffSession { .. } => HostActionKind::HandoffSession,
			Self::LoadTranscript { .. } => HostActionKind::LoadTranscript,
			Self::SubmitPrompt { .. } => HostActionKind::SubmitPrompt,
			Self::Steer { .. } => HostActionKind::Steer,
			Self::FollowUp { .. } => HostActionKind::FollowUp,
			Self::AbortTurn { .. } => HostActionKind::AbortTurn,
			Self::RetryTurn { .. } => HostActionKind::RetryTurn,
			Self::RephraseReply { .. } => HostActionKind::RephraseReply,
			Self::ReviewPlan { .. } => HostActionKind::ReviewPlan,
			Self::SetQueueMode { .. } => HostActionKind::SetQueueMode,
			Self::SetSessionMode { .. } => HostActionKind::SetSessionMode,
			Self::CancelTool { .. } => HostActionKind::CancelTool,
			Self::SetToolViewExpanded { .. } => HostActionKind::SetToolViewExpanded,
			Self::DequeueQueuedPrompt { .. } => HostActionKind::DequeueQueuedPrompt,
			Self::RespondToInteraction { .. } => HostActionKind::RespondToInteraction,
			Self::LoadFileTree { .. } => HostActionKind::LoadFileTree,
			Self::ReadFile { .. } => HostActionKind::ReadFile,
			Self::SearchFiles { .. } => HostActionKind::SearchFiles,
			Self::SearchContent { .. } => HostActionKind::SearchContent,
			Self::OpenExternal { .. } => HostActionKind::OpenExternal,
			Self::RefreshChanges => HostActionKind::RefreshChanges,
			Self::SelectChangeScope { .. } => HostActionKind::SelectChangeScope,
			Self::CreateTerminal { .. } => HostActionKind::CreateTerminal,
			Self::AttachTerminal { .. } => HostActionKind::AttachTerminal,
			Self::WriteTerminal { .. } => HostActionKind::WriteTerminal,
			Self::ResizeTerminal { .. } => HostActionKind::ResizeTerminal,
			Self::RestartTerminal { .. } => HostActionKind::RestartTerminal,
			Self::ClearTerminal { .. } => HostActionKind::ClearTerminal,
			Self::CloseTerminal { .. } => HostActionKind::CloseTerminal,
			Self::RefreshProcesses => HostActionKind::RefreshProcesses,
			Self::ProcessLogs { .. } => HostActionKind::ProcessLogs,
			Self::ProcessSend { .. } => HostActionKind::ProcessSend,
			Self::ProcessSignal { .. } => HostActionKind::ProcessSignal,
			Self::ProcessStop { .. } => HostActionKind::ProcessStop,
			Self::ProcessRestart { .. } => HostActionKind::ProcessRestart,
			Self::ProcessStart { .. } => HostActionKind::ProcessStart,
			Self::RefreshModels => HostActionKind::RefreshModels,
			Self::SelectModel { .. } => HostActionKind::SelectModel,
			Self::SetThinkingLevel { .. } => HostActionKind::SetThinkingLevel,
			Self::RefreshProviders => HostActionKind::RefreshProviders,
			Self::StartProviderAuth { .. } => HostActionKind::StartProviderAuth,
			Self::SubmitAuthSecret { .. } => HostActionKind::SubmitAuthSecret,
			Self::OpenAuthUrl { .. } => HostActionKind::OpenAuthUrl,
			Self::CancelAuthFlow { .. } => HostActionKind::CancelAuthFlow,
			Self::RetryAuthFlow { .. } => HostActionKind::RetryAuthFlow,
			Self::RefreshMcp => HostActionKind::RefreshMcp,
			Self::SetMcpEnabled { .. } => HostActionKind::SetMcpEnabled,
			Self::RefreshAgents => HostActionKind::RefreshAgents,
			Self::ReviveAgent { .. } => HostActionKind::ReviveAgent,
			Self::SpawnTask { .. } => HostActionKind::SpawnTask,
			Self::CancelTask { .. } => HostActionKind::CancelTask,
			Self::ListCommands => HostActionKind::ListCommands,
			Self::RunCommand { .. } => HostActionKind::RunCommand,
			Self::LoadSettings => HostActionKind::LoadSettings,
			Self::SetSetting { .. } => HostActionKind::SetSetting,
			Self::ResetSetting { .. } => HostActionKind::ResetSetting,
			Self::LoadThemes => HostActionKind::LoadThemes,
			Self::LoadKeybindings => HostActionKind::LoadKeybindings,
			Self::SetKeybinding { .. } => HostActionKind::SetKeybinding,
			Self::RefreshDiagnostics => HostActionKind::RefreshDiagnostics,
			Self::RetryDiagnosticSource { .. } => HostActionKind::RetryDiagnosticSource,
			Self::ClearOutput { .. } => HostActionKind::ClearOutput,
			Self::GetUsage { .. } => HostActionKind::GetUsage,
			Self::GetContextBreakdown { .. } => HostActionKind::GetContextBreakdown,
			Self::SetGoal { .. } => HostActionKind::SetGoal,
			Self::ControlGoal { .. } => HostActionKind::ControlGoal,
			Self::StartShare { .. } => HostActionKind::StartShare,
			Self::StopShare => HostActionKind::StopShare,
			Self::RefreshShare => HostActionKind::RefreshShare,
		}
	}
}
