use serde::{Deserialize, Serialize};

/// Discriminant enum for each of the 72 host actions.
#[derive(
	Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash, Serialize, Deserialize, strum::EnumIter,
)]
pub enum HostActionKind {
	Attach,
	Detach,
	RetryConnection,
	Shutdown,
	ListSessions,
	OpenSession,
	CreateSession,
	RenameSession,
	DeleteSession,
	BranchSession,
	ExportSession,
	CompactSession,
	HandoffSession,
	LoadTranscript,
	SubmitPrompt,
	Steer,
	FollowUp,
	AbortTurn,
	SetQueueMode,
	CancelTool,
	RespondToInteraction,
	LoadFileTree,
	ReadFile,
	SearchFiles,
	OpenExternal,
	RefreshChanges,
	SelectChangeScope,
	CreateTerminal,
	AttachTerminal,
	WriteTerminal,
	ResizeTerminal,
	RestartTerminal,
	ClearTerminal,
	CloseTerminal,
	RefreshProcesses,
	ProcessLogs,
	ProcessSend,
	ProcessSignal,
	ProcessStop,
	ProcessRestart,
	ProcessStart,
	ProcessWait,
	ProcessDescribe,
	RefreshModels,
	SelectModel,
	SetThinkingLevel,
	RefreshProviders,
	StartProviderAuth,
	RefreshAuth,
	SubmitAuthSecret,
	OpenAuthUrl,
	CancelAuthFlow,
	RetryAuthFlow,
	RefreshMcp,
	ConnectMcp,
	DisconnectMcp,
	SetMcpEnabled,
	CallMcpTool,
	ReviveAgent,
	SpawnTask,
	CancelTask,
	LoadSettings,
	SetSetting,
	ResetSetting,
	LoadThemes,
	LoadKeybindings,
	SetKeybinding,
	RefreshDiagnostics,
	RetryDiagnosticSource,
	ClearOutput,
	GetUsage,
	GetContextBreakdown,
}

impl HostActionKind {
	/// Complete slice of all 72 action kinds for runtime test sweeps.
	pub const ALL: [Self; 72] = [
		Self::Attach,
		Self::Detach,
		Self::RetryConnection,
		Self::Shutdown,
		Self::ListSessions,
		Self::OpenSession,
		Self::CreateSession,
		Self::RenameSession,
		Self::DeleteSession,
		Self::BranchSession,
		Self::ExportSession,
		Self::CompactSession,
		Self::HandoffSession,
		Self::LoadTranscript,
		Self::SubmitPrompt,
		Self::Steer,
		Self::FollowUp,
		Self::AbortTurn,
		Self::SetQueueMode,
		Self::CancelTool,
		Self::RespondToInteraction,
		Self::LoadFileTree,
		Self::ReadFile,
		Self::SearchFiles,
		Self::OpenExternal,
		Self::RefreshChanges,
		Self::SelectChangeScope,
		Self::CreateTerminal,
		Self::AttachTerminal,
		Self::WriteTerminal,
		Self::ResizeTerminal,
		Self::RestartTerminal,
		Self::ClearTerminal,
		Self::CloseTerminal,
		Self::RefreshProcesses,
		Self::ProcessLogs,
		Self::ProcessSend,
		Self::ProcessSignal,
		Self::ProcessStop,
		Self::ProcessRestart,
		Self::ProcessStart,
		Self::ProcessWait,
		Self::ProcessDescribe,
		Self::RefreshModels,
		Self::SelectModel,
		Self::SetThinkingLevel,
		Self::RefreshProviders,
		Self::StartProviderAuth,
		Self::RefreshAuth,
		Self::SubmitAuthSecret,
		Self::OpenAuthUrl,
		Self::CancelAuthFlow,
		Self::RetryAuthFlow,
		Self::RefreshMcp,
		Self::ConnectMcp,
		Self::DisconnectMcp,
		Self::SetMcpEnabled,
		Self::CallMcpTool,
		Self::ReviveAgent,
		Self::SpawnTask,
		Self::CancelTask,
		Self::LoadSettings,
		Self::SetSetting,
		Self::ResetSetting,
		Self::LoadThemes,
		Self::LoadKeybindings,
		Self::SetKeybinding,
		Self::RefreshDiagnostics,
		Self::RetryDiagnosticSource,
		Self::ClearOutput,
		Self::GetUsage,
		Self::GetContextBreakdown,
	];

	/// Returns wire name identifier.
	#[must_use]
	pub const fn as_str(self) -> &'static str {
		match self {
			Self::Attach => "Attach",
			Self::Detach => "Detach",
			Self::RetryConnection => "RetryConnection",
			Self::Shutdown => "Shutdown",
			Self::ListSessions => "ListSessions",
			Self::OpenSession => "OpenSession",
			Self::CreateSession => "CreateSession",
			Self::RenameSession => "RenameSession",
			Self::DeleteSession => "DeleteSession",
			Self::BranchSession => "BranchSession",
			Self::ExportSession => "ExportSession",
			Self::CompactSession => "CompactSession",
			Self::HandoffSession => "HandoffSession",
			Self::LoadTranscript => "LoadTranscript",
			Self::SubmitPrompt => "SubmitPrompt",
			Self::Steer => "Steer",
			Self::FollowUp => "FollowUp",
			Self::AbortTurn => "AbortTurn",
			Self::SetQueueMode => "SetQueueMode",
			Self::CancelTool => "CancelTool",
			Self::RespondToInteraction => "RespondToInteraction",
			Self::LoadFileTree => "LoadFileTree",
			Self::ReadFile => "ReadFile",
			Self::SearchFiles => "SearchFiles",
			Self::OpenExternal => "OpenExternal",
			Self::RefreshChanges => "RefreshChanges",
			Self::SelectChangeScope => "SelectChangeScope",
			Self::CreateTerminal => "CreateTerminal",
			Self::AttachTerminal => "AttachTerminal",
			Self::WriteTerminal => "WriteTerminal",
			Self::ResizeTerminal => "ResizeTerminal",
			Self::RestartTerminal => "RestartTerminal",
			Self::ClearTerminal => "ClearTerminal",
			Self::CloseTerminal => "CloseTerminal",
			Self::RefreshProcesses => "RefreshProcesses",
			Self::ProcessLogs => "ProcessLogs",
			Self::ProcessSend => "ProcessSend",
			Self::ProcessSignal => "ProcessSignal",
			Self::ProcessStop => "ProcessStop",
			Self::ProcessRestart => "ProcessRestart",
			Self::ProcessStart => "ProcessStart",
			Self::ProcessWait => "ProcessWait",
			Self::ProcessDescribe => "ProcessDescribe",
			Self::RefreshModels => "RefreshModels",
			Self::SelectModel => "SelectModel",
			Self::SetThinkingLevel => "SetThinkingLevel",
			Self::RefreshProviders => "RefreshProviders",
			Self::StartProviderAuth => "StartProviderAuth",
			Self::RefreshAuth => "RefreshAuth",
			Self::SubmitAuthSecret => "SubmitAuthSecret",
			Self::OpenAuthUrl => "OpenAuthUrl",
			Self::CancelAuthFlow => "CancelAuthFlow",
			Self::RetryAuthFlow => "RetryAuthFlow",
			Self::RefreshMcp => "RefreshMcp",
			Self::ConnectMcp => "ConnectMcp",
			Self::DisconnectMcp => "DisconnectMcp",
			Self::SetMcpEnabled => "SetMcpEnabled",
			Self::CallMcpTool => "CallMcpTool",
			Self::ReviveAgent => "ReviveAgent",
			Self::SpawnTask => "SpawnTask",
			Self::CancelTask => "CancelTask",
			Self::LoadSettings => "LoadSettings",
			Self::SetSetting => "SetSetting",
			Self::ResetSetting => "ResetSetting",
			Self::LoadThemes => "LoadThemes",
			Self::LoadKeybindings => "LoadKeybindings",
			Self::SetKeybinding => "SetKeybinding",
			Self::RefreshDiagnostics => "RefreshDiagnostics",
			Self::RetryDiagnosticSource => "RetryDiagnosticSource",
			Self::ClearOutput => "ClearOutput",
			Self::GetUsage => "GetUsage",
			Self::GetContextBreakdown => "GetContextBreakdown",
		}
	}
}
