//! Enumeration and metadata for all dispatched terminal escape sequences.

/// Every sequence kind dispatched by the terminal byte stream parser.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum SequenceKind {
	// C0 control characters
	Bell,
	Backspace,
	HorizontalTab,
	LineFeed,
	CarriageReturn,

	// Cursor motion
	CursorUp,
	CursorDown,
	CursorForward,
	CursorBack,
	CursorNextLine,
	CursorPreviousLine,
	CursorHorizontalAbsolute,
	CursorPosition,
	HorizontalVerticalPosition,
	VerticalPositionAbsolute,

	// Erasing
	EraseInDisplay,
	EraseInLine,
	EraseCharacter,

	// Line and character edit
	InsertLine,
	DeleteLine,
	InsertCharacter,
	DeleteCharacter,

	// Scrolling and regions
	ScrollUp,
	ScrollDown,
	SetScrollRegion,

	// Text rendition (SGR)
	SgrReset,
	SgrBold,
	SgrDim,
	SgrItalic,
	SgrUnderline,
	SgrReverse,
	SgrHidden,
	SgrStrikethrough,
	SgrForegroundIndexed,
	SgrBackgroundIndexed,
	SgrForegroundRgb,
	SgrBackgroundRgb,
	SgrForegroundDefault,
	SgrBackgroundDefault,

	// Mode management
	DecSetCursorVisible,
	DecResetCursorVisible,
	DecSetAlternateScreen,
	DecResetAlternateScreen,
	DecSetAutoWrap,
	DecResetAutoWrap,

	// Save and restore
	SaveCursorEsc,
	RestoreCursorEsc,
	SaveCursorCsi,
	RestoreCursorCsi,

	// Other escape sequences
	ReverseIndex,
	NextLine,
	HorizontalTabSet,
	TabClear,
	DecScreenAlignment,
	ResetToInitialState,
}

impl SequenceKind {
	pub const ALL: &'static [SequenceKind] = &[
		SequenceKind::Bell,
		SequenceKind::Backspace,
		SequenceKind::HorizontalTab,
		SequenceKind::LineFeed,
		SequenceKind::CarriageReturn,
		SequenceKind::CursorUp,
		SequenceKind::CursorDown,
		SequenceKind::CursorForward,
		SequenceKind::CursorBack,
		SequenceKind::CursorNextLine,
		SequenceKind::CursorPreviousLine,
		SequenceKind::CursorHorizontalAbsolute,
		SequenceKind::CursorPosition,
		SequenceKind::HorizontalVerticalPosition,
		SequenceKind::VerticalPositionAbsolute,
		SequenceKind::EraseInDisplay,
		SequenceKind::EraseInLine,
		SequenceKind::EraseCharacter,
		SequenceKind::InsertLine,
		SequenceKind::DeleteLine,
		SequenceKind::InsertCharacter,
		SequenceKind::DeleteCharacter,
		SequenceKind::ScrollUp,
		SequenceKind::ScrollDown,
		SequenceKind::SetScrollRegion,
		SequenceKind::SgrReset,
		SequenceKind::SgrBold,
		SequenceKind::SgrDim,
		SequenceKind::SgrItalic,
		SequenceKind::SgrUnderline,
		SequenceKind::SgrReverse,
		SequenceKind::SgrHidden,
		SequenceKind::SgrStrikethrough,
		SequenceKind::SgrForegroundIndexed,
		SequenceKind::SgrBackgroundIndexed,
		SequenceKind::SgrForegroundRgb,
		SequenceKind::SgrBackgroundRgb,
		SequenceKind::SgrForegroundDefault,
		SequenceKind::SgrBackgroundDefault,
		SequenceKind::DecSetCursorVisible,
		SequenceKind::DecResetCursorVisible,
		SequenceKind::DecSetAlternateScreen,
		SequenceKind::DecResetAlternateScreen,
		SequenceKind::DecSetAutoWrap,
		SequenceKind::DecResetAutoWrap,
		SequenceKind::SaveCursorEsc,
		SequenceKind::RestoreCursorEsc,
		SequenceKind::SaveCursorCsi,
		SequenceKind::RestoreCursorCsi,
		SequenceKind::ReverseIndex,
		SequenceKind::NextLine,
		SequenceKind::HorizontalTabSet,
		SequenceKind::TabClear,
		SequenceKind::DecScreenAlignment,
		SequenceKind::ResetToInitialState,
	];

	pub const fn name(self) -> &'static str {
		match self {
			Self::Bell => "bell",
			Self::Backspace => "backspace",
			Self::HorizontalTab => "horizontal-tab",
			Self::LineFeed => "line-feed",
			Self::CarriageReturn => "carriage-return",
			Self::CursorUp => "cursor-up",
			Self::CursorDown => "cursor-down",
			Self::CursorForward => "cursor-forward",
			Self::CursorBack => "cursor-back",
			Self::CursorNextLine => "cursor-next-line",
			Self::CursorPreviousLine => "cursor-previous-line",
			Self::CursorHorizontalAbsolute => "cursor-horizontal-absolute",
			Self::CursorPosition => "cursor-position",
			Self::HorizontalVerticalPosition => "horizontal-vertical-position",
			Self::VerticalPositionAbsolute => "vertical-position-absolute",
			Self::EraseInDisplay => "erase-in-display",
			Self::EraseInLine => "erase-in-line",
			Self::EraseCharacter => "erase-character",
			Self::InsertLine => "insert-line",
			Self::DeleteLine => "delete-line",
			Self::InsertCharacter => "insert-character",
			Self::DeleteCharacter => "delete-character",
			Self::ScrollUp => "scroll-up",
			Self::ScrollDown => "scroll-down",
			Self::SetScrollRegion => "set-scroll-region",
			Self::SgrReset => "sgr-reset",
			Self::SgrBold => "sgr-bold",
			Self::SgrDim => "sgr-dim",
			Self::SgrItalic => "sgr-italic",
			Self::SgrUnderline => "sgr-underline",
			Self::SgrReverse => "sgr-reverse",
			Self::SgrHidden => "sgr-hidden",
			Self::SgrStrikethrough => "sgr-strikethrough",
			Self::SgrForegroundIndexed => "sgr-fg-indexed",
			Self::SgrBackgroundIndexed => "sgr-bg-indexed",
			Self::SgrForegroundRgb => "sgr-fg-rgb",
			Self::SgrBackgroundRgb => "sgr-bg-rgb",
			Self::SgrForegroundDefault => "sgr-fg-default",
			Self::SgrBackgroundDefault => "sgr-bg-default",
			Self::DecSetCursorVisible => "decset-cursor-visible",
			Self::DecResetCursorVisible => "decrst-cursor-visible",
			Self::DecSetAlternateScreen => "decset-alternate-screen",
			Self::DecResetAlternateScreen => "decrst-alternate-screen",
			Self::DecSetAutoWrap => "decset-auto-wrap",
			Self::DecResetAutoWrap => "decrst-auto-wrap",
			Self::SaveCursorEsc => "save-cursor-esc",
			Self::RestoreCursorEsc => "restore-cursor-esc",
			Self::SaveCursorCsi => "save-cursor-csi",
			Self::RestoreCursorCsi => "restore-cursor-csi",
			Self::ReverseIndex => "reverse-index",
			Self::NextLine => "next-line",
			Self::HorizontalTabSet => "horizontal-tab-set",
			Self::TabClear => "tab-clear",
			Self::DecScreenAlignment => "dec-screen-alignment",
			Self::ResetToInitialState => "reset-to-initial-state",
		}
	}

	/// Example byte sequence for this sequence kind.
	pub const fn sample_bytes(self) -> &'static [u8] {
		match self {
			Self::Bell => b"\x07",
			Self::Backspace => b"\x08",
			Self::HorizontalTab => b"\t",
			Self::LineFeed => b"\n",
			Self::CarriageReturn => b"\r",
			Self::CursorUp => b"\x1b[2A",
			Self::CursorDown => b"\x1b[2B",
			Self::CursorForward => b"\x1b[3C",
			Self::CursorBack => b"\x1b[2D",
			Self::CursorNextLine => b"\x1b[2E",
			Self::CursorPreviousLine => b"\x1b[1F",
			Self::CursorHorizontalAbsolute => b"\x1b[5G",
			Self::CursorPosition => b"\x1b[3;4H",
			Self::HorizontalVerticalPosition => b"\x1b[2;6f",
			Self::VerticalPositionAbsolute => b"\x1b[4d",
			Self::EraseInDisplay => b"\x1b[2J",
			Self::EraseInLine => b"\x1b[2K",
			Self::EraseCharacter => b"\x1b[3X",
			Self::InsertLine => b"\x1b[2L",
			Self::DeleteLine => b"\x1b[2M",
			Self::InsertCharacter => b"\x1b[2@",
			Self::DeleteCharacter => b"\x1b[2P",
			Self::ScrollUp => b"\x1b[2S",
			Self::ScrollDown => b"\x1b[2T",
			Self::SetScrollRegion => b"\x1b[2;5r",
			Self::SgrReset => b"\x1b[0m",
			Self::SgrBold => b"\x1b[1m",
			Self::SgrDim => b"\x1b[2m",
			Self::SgrItalic => b"\x1b[3m",
			Self::SgrUnderline => b"\x1b[4m",
			Self::SgrReverse => b"\x1b[7m",
			Self::SgrHidden => b"\x1b[8m",
			Self::SgrStrikethrough => b"\x1b[9m",
			Self::SgrForegroundIndexed => b"\x1b[38;5;196m",
			Self::SgrBackgroundIndexed => b"\x1b[48;5;22m",
			Self::SgrForegroundRgb => b"\x1b[38;2;100;150;200m",
			Self::SgrBackgroundRgb => b"\x1b[48;2;50;60;70m",
			Self::SgrForegroundDefault => b"\x1b[39m",
			Self::SgrBackgroundDefault => b"\x1b[49m",
			Self::DecSetCursorVisible => b"\x1b[?25h",
			Self::DecResetCursorVisible => b"\x1b[?25l",
			Self::DecSetAlternateScreen => b"\x1b[?1049h",
			Self::DecResetAlternateScreen => b"\x1b[?1049l",
			Self::DecSetAutoWrap => b"\x1b[?7h",
			Self::DecResetAutoWrap => b"\x1b[?7l",
			Self::SaveCursorEsc => b"\x1b7",
			Self::RestoreCursorEsc => b"\x1b8",
			Self::SaveCursorCsi => b"\x1b[s",
			Self::RestoreCursorCsi => b"\x1b[u",
			Self::ReverseIndex => b"\x1bM",
			Self::NextLine => b"\x1bE",
			Self::HorizontalTabSet => b"\x1bH",
			Self::TabClear => b"\x1b[3g",
			Self::DecScreenAlignment => b"\x1b#8",
			Self::ResetToInitialState => b"\x1bc",
		}
	}
}
