import { describe, expect, it } from "bun:test";
import { SecretObfuscator } from "@veyyon/coding-agent/secrets/obfuscator";

const PLACEHOLDER_KEY = new Uint8Array(32).fill(1);

describe("substitution outputs are atomic", () => {
	/**
	 * A regex-created HMAC placeholder contains digits. A short literal replace rule must never scan
	 * those generated bytes, or the placeholder becomes malformed and cannot restore the credential.
	 */
	it("protects regex placeholders from the final literal pass", () => {
		const obfuscator = new SecretObfuscator(
			[
				{ type: "plain", content: "0", mode: "replace", replacement: "X" },
				{ type: "regex", content: "secretvalue" },
			],
			{ placeholderKey: PLACEHOLDER_KEY },
		);

		const outbound = obfuscator.obfuscate("secretvalue");
		expect(outbound).toMatch(/^#0[A-F0-9]{24}#$/);
		expect(obfuscator.deobfuscate(outbound)).toBe("secretvalue");
	});

	/**
	 * A readable placeholder is already protected output. Regex rules may match its visible name in
	 * ordinary input, but cannot reinterpret the same bytes after a literal secret emitted them.
	 */
	it("protects named placeholders from regex rules", () => {
		const obfuscator = new SecretObfuscator(
			[
				{ type: "plain", content: "named-secret-value", name: "GITHUB_TOKEN" },
				{ type: "regex", content: "GITHUB_TOKEN" },
			],
			{ placeholderKey: new Uint8Array(32).fill(6) },
		);

		const outbound = obfuscator.obfuscate("named-secret-value");
		expect(outbound).toBe("#GITHUB_TOKEN#");
		expect(obfuscator.deobfuscate(outbound)).toBe("named-secret-value");
	});

	/**
	 * Replace-mode aliases are one-way terminal output. A later regex that happens to match an alias
	 * must not wrap it in a reversible placeholder and change the configured wire representation.
	 */
	it("protects literal replacement aliases from regex reinterpretation", () => {
		const obfuscator = new SecretObfuscator(
			[
				{
					type: "plain",
					content: "literal-source-secret",
					mode: "replace",
					replacement: "alias-12345678",
				},
				{ type: "regex", content: "alias-[0-9]{8}" },
			],
			{ placeholderKey: PLACEHOLDER_KEY },
		);

		const outbound = obfuscator.obfuscate("literal-source-secret");
		expect(outbound).toBe("alias-12345678");
		expect(obfuscator.deobfuscate(outbound)).toBe("alias-12345678");
	});

	/**
	 * Earlier regex entries also emit terminal output. Later entries cannot reinterpret a custom
	 * alias, while a genuine copy of the same text elsewhere remains eligible for the later rule.
	 */
	it("protects regex aliases by provenance rather than by global value", () => {
		const obfuscator = new SecretObfuscator(
			[
				{
					type: "regex",
					content: "source-[0-9]{8}",
					mode: "replace",
					replacement: "alias-12345678",
				},
				{ type: "regex", content: "alias-[0-9]{8}" },
			],
			{ placeholderKey: PLACEHOLDER_KEY },
		);

		const outbound = obfuscator.obfuscate("source-87654321 and alias-12345678");
		const [protectedAlias, genuineAliasPlaceholder] = outbound.split(" and ");
		expect(protectedAlias).toBe("alias-12345678");
		expect(genuineAliasPlaceholder).toMatch(/^#0[A-F0-9]{24}#$/);
		expect(obfuscator.deobfuscate(outbound)).toBe("alias-12345678 and alias-12345678");
	});

	/**
	 * A live placeholder supplied in existing transcript text is atomic before any new rule runs.
	 * Re-obfuscating resumed history therefore preserves both the token and its expansion right.
	 */
	it("preserves an existing live placeholder across every phase", () => {
		const obfuscator = new SecretObfuscator(
			[
				{ type: "plain", content: "resumed-secret-value", name: "RESUME_TOKEN" },
				{ type: "plain", content: "TOKEN", mode: "replace", replacement: "LABEL" },
				{ type: "regex", content: "RESUME_[A-Z]+" },
			],
			{ placeholderKey: PLACEHOLDER_KEY },
		);

		expect(obfuscator.obfuscate("use #RESUME_TOKEN#")).toBe("use #RESUME_TOKEN#");
		expect(obfuscator.deobfuscate("use #RESUME_TOKEN#")).toBe("use resumed-secret-value");
	});

	/**
	 * A rule whose source crosses a protected token is skipped rather than consuming part of the
	 * token. Independent matches before and after the token still apply normally.
	 */
	it("does not allow a literal match to cross a protected span", () => {
		const obfuscator = new SecretObfuscator(
			[
				{ type: "plain", content: "crossing-secret-value", name: "CROSS_TOKEN" },
				{ type: "plain", content: "prefix#CROSS_TOKEN#suffix", mode: "replace", replacement: "bad" },
			],
			{ placeholderKey: PLACEHOLDER_KEY },
		);

		const input = "prefix#CROSS_TOKEN#suffix";
		expect(obfuscator.obfuscate(input)).toBe(input);
	});
});
