import { describe, expect, it } from "bun:test";
import { SecretObfuscator } from "@veyyon/coding-agent/secrets/obfuscator";

const PLACEHOLDER_KEY = new Uint8Array(32).fill(1);

describe("substitution outputs are atomic", () => {
	/**
	 * A regex-created HMAC placeholder contains digits. A short literal replace rule must never scan
	 * those generated bytes, or the placeholder becomes malformed and cannot restore the credential.
	 */
	it("protects regex placeholders from the final literal pass", () => {
		const obfuscator = new SecretObfuscator(
			[
				{ type: "plain", origin: "config", content: "0", mode: "replace", replacement: "X" },
				{ type: "regex", origin: "config", content: "secretvalue" },
			],
			{ placeholderKey: PLACEHOLDER_KEY },
		);

		const outbound = obfuscator.obfuscate("secretvalue");
		expect(outbound).toMatch(/^#0[A-F0-9]{24}#$/);
		expect(obfuscator.deobfuscate(outbound)).toBe("secretvalue");
	});

	/**
	 * A readable placeholder is already protected output. Regex rules may match its visible name in
	 * ordinary input, but cannot reinterpret the same bytes after a literal secret emitted them.
	 */
	it("protects named placeholders from regex rules", () => {
		const obfuscator = new SecretObfuscator(
			[
				{ type: "plain", origin: "config", content: "named-secret-value", name: "GITHUB_TOKEN" },
				{ type: "regex", origin: "config", content: "GITHUB_TOKEN" },
			],
			{ placeholderKey: new Uint8Array(32).fill(6) },
		);

		const outbound = obfuscator.obfuscate("named-secret-value");
		expect(outbound).toBe("#GITHUB_TOKEN#");
		expect(obfuscator.deobfuscate(outbound)).toBe("named-secret-value");
	});

	/**
	 * A literal alias captured by a regex would either change on the next call or globally shadow
	 * genuine regex matches, so the ambiguous pair is refused independent of rule order.
	 */
	it("rejects a literal alias captured by a regex rule", () => {
		expect(
			() =>
				new SecretObfuscator(
					[
						{
							type: "plain",
							origin: "config",
							content: "literal-source-secret",
							mode: "replace",
							replacement: "alias-12345678",
						},
						{ type: "regex", origin: "config", content: "alias-[0-9]{8}" },
					],
					{ placeholderKey: PLACEHOLDER_KEY },
				),
		).toThrow(/alias captured by another secret rule/i);
	});

	/**
	 * Regex-produced aliases have the same cross-call identity contract. A different regex that
	 * captures the alias makes that contract ambiguous and is rejected at construction.
	 */
	it("rejects a regex alias captured by a different regex rule", () => {
		expect(
			() =>
				new SecretObfuscator(
					[
						{
							type: "regex",
							origin: "config",
							content: "source-[0-9]{8}",
							mode: "replace",
							replacement: "alias-12345678",
						},
						{ type: "regex", origin: "config", content: "alias-[0-9]{8}" },
					],
					{ placeholderKey: PLACEHOLDER_KEY },
				),
		).toThrow(/alias captured by another secret rule/i);
	});

	/**
	 * A live placeholder supplied in existing transcript text is atomic before any new rule runs.
	 * Re-obfuscating resumed history therefore preserves both the token and its expansion right.
	 */
	it("preserves an existing live placeholder across every phase", () => {
		const obfuscator = new SecretObfuscator(
			[
				{ type: "plain", origin: "config", content: "resumed-secret-value", name: "RESUME_TOKEN" },
				{ type: "plain", origin: "config", content: "TOKEN", mode: "replace", replacement: "LABEL" },
				{ type: "regex", origin: "config", content: "RESUME_[A-Z]+" },
			],
			{ placeholderKey: PLACEHOLDER_KEY },
		);

		expect(obfuscator.obfuscate("use #RESUME_TOKEN#")).toBe("use #RESUME_TOKEN#");
		expect(obfuscator.deobfuscate("use #RESUME_TOKEN#")).toBe("use resumed-secret-value");
	});

	/**
	 * A rule whose source crosses a protected token is skipped rather than consuming part of the
	 * token. Independent matches before and after the token still apply normally.
	 */
	it("does not allow a literal match to cross a protected span", () => {
		const obfuscator = new SecretObfuscator(
			[
				{ type: "plain", origin: "config", content: "crossing-secret-value", name: "CROSS_TOKEN" },
				{
					type: "plain",
					origin: "config",
					content: "prefix#CROSS_TOKEN#suffix",
					mode: "replace",
					replacement: "bad",
				},
			],
			{ placeholderKey: PLACEHOLDER_KEY },
		);

		const input = "prefix#CROSS_TOKEN#suffix";
		expect(obfuscator.obfuscate(input)).toBe(input);
	});
});
