[package]
name = "veyyon-desktop-motion"
version.workspace = true
publish = false
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true

[lints]
workspace = true

[dependencies]
serde.workspace = true
thiserror.workspace = true
toml.workspace = true
veyyon-desktop-tokens.workspace = true
