import * as fs from "node:fs/promises";
import * as path from "node:path";
import { findStaleAddon, staleAddonMessage } from "../native/loader-state.js";

const reset = process.argv.includes("--reset");
/**
 * Refresh the archive but leave the metadata module as the checked-in stub.
 *
 * `embedded-addon.js` is the loader's authoritative "am I a compiled binary?" signal
 * (`detectCompiledBinary`, issue 823), and that only holds while the premise behind it does:
 * the module is `null` in a source tree and populated only inside a `--compile` bundle. A
 * plain `bun run build:native` used to break that premise and leave it populated, after
 * which every ordinary `bun packages/coding-agent/src/cli.ts` in that checkout believed it
 * was a standalone binary and extracted 290 MB of addon into `$HOME/.veyyon/natives/`.
 * Multiplied by a test suite that spawns the CLI with a fresh temp `HOME`, that filled a
 * 915 GB disk.
 *
 * The archive still has to be refreshed by a rebuild, because a compiled binary loads what
 * the ARCHIVE holds and the two artifacts must not drift. The metadata module does not: the
 * release path (`scripts/ci-release-build-binaries.ts`) regenerates it immediately before
 * each `bun build --compile` and resets it in a `finally`. So a rebuild writes the archive
 * and keeps the stub, and nothing in a source tree ever claims to be compiled.
 */
const stubMetadata = process.argv.includes("--stub-metadata");
const outputPath = path.join(import.meta.dir, "../native/embedded-addon.js");
const packageJsonPath = path.join(import.meta.dir, "../package.json");
const nativeDir = path.join(import.meta.dir, "../native");
const archivePrefix = "embedded-addons.";
const archiveSuffix = ".tar.gz";

const embeddedAddonTypedefs = `/** @typedef {"modern" | "baseline" | "default"} EmbeddedAddonVariant */

/**
 * @typedef {Object} EmbeddedAddonFile
 * @property {EmbeddedAddonVariant} variant
 * @property {string} filename
 * @property {number} size
 * @property {string=} filePath
 */

/**
 * @typedef {Object} EmbeddedAddonArchive
 * @property {"tar.gz"} format
 * @property {string} filename
 * @property {string} filePath
 */

/**
 * @typedef {Object} EmbeddedAddon
 * @property {string} platformTag
 * @property {string} version
 * @property {EmbeddedAddonFile[]} files
 * @property {EmbeddedAddonArchive=} archive
 */`;

const stubContent = `
// AUTOGENERATED FILE -- DO NOT EDIT DIRECTLY
// See scripts/embed-native.ts

${embeddedAddonTypedefs}

/** @type {EmbeddedAddon|null} */
export const embeddedAddon = null;
`;
if (reset) {
	await Bun.write(outputPath, stubContent);
	try {
		const entries = await fs.readdir(nativeDir);
		await Promise.all(
			entries
				.filter(entry => entry.startsWith(archivePrefix) && entry.endsWith(archiveSuffix))
				.map(entry => fs.unlink(path.join(nativeDir, entry))),
		);
	} catch (err) {
		if ((err as NodeJS.ErrnoException).code !== "ENOENT") throw err;
	}
	process.exit(0);
}

interface CandidateAddon {
	variant: "modern" | "baseline" | "default";
	filename: string;
}

interface AvailableAddon extends CandidateAddon {
	path: string;
	size: number;
}

const targetPlatform = Bun.env.TARGET_PLATFORM || process.platform;
const targetArch = Bun.env.TARGET_ARCH || process.arch;
const platformTag = `${targetPlatform}-${targetArch}`;
const candidates: CandidateAddon[] =
	targetArch === "x64"
		? [
				{ variant: "modern", filename: `veyyon_natives.${platformTag}-modern.node` },
				{ variant: "baseline", filename: `veyyon_natives.${platformTag}-baseline.node` },
			]
		: [{ variant: "default", filename: `veyyon_natives.${platformTag}.node` }];

const available: AvailableAddon[] = [];
for (const candidate of candidates) {
	const candidatePath = path.join(nativeDir, candidate.filename);
	try {
		const stat = await fs.stat(candidatePath);
		available.push({ ...candidate, path: candidatePath, size: stat.size });
	} catch (err) {
		if ((err as NodeJS.ErrnoException).code !== "ENOENT") throw err;
	}
}

if (available.length === 0) {
	const expected = candidates.map(candidate => `  - ${candidate.filename}`).join("\n");
	throw new Error(`No native addons found for ${platformTag}. Expected one of:\n${expected}`);
}
const packageJson = (await Bun.file(packageJsonPath).json()) as { version: string };

const archiveFilename = `${archivePrefix}${platformTag}${archiveSuffix}`;
const archivePath = path.join(nativeDir, archiveFilename);
const archiveEntries: Record<string, Uint8Array> = {};
const addonBytes = await Promise.all(
	available.map(async addon => ({ filename: addon.filename, bytes: await fs.readFile(addon.path) })),
);

// Refuse to embed a native built for a DIFFERENT version than this package.
// The loader keys the addon on `__veyyonNativesV<version>`; a `.node` left
// stale by a version bump (or a variant rebuilt at a different version, e.g.
// modern at 1.0.14 while baseline is 1.0.15) carries the wrong sentinel, so
// the compiled binary would extract it and then hard-fail at first native use
// — bricking exactly the CPUs that select that variant. Catch it here, at
// build time, instead of in a user's terminal. (Law 10: fail closed, never
// ship a fallback that cannot load.) The staleness contract lives in one place
// (`findStaleAddon`/`staleAddonMessage`) so this guard and the loader can never
// disagree on what "stale" means.
const stale = findStaleAddon(addonBytes, packageJson.version);
if (stale) {
	throw new Error(staleAddonMessage(stale, packageJson.version));
}
for (const addon of addonBytes) {
	archiveEntries[addon.filename] = addon.bytes;
}
await Bun.write(archivePath, await new Bun.Archive(archiveEntries, { compress: "gzip", level: 9 }).bytes());

const files = available
	.map(
		addon =>
			`\t\t{ variant: ${JSON.stringify(addon.variant)}, filename: ${JSON.stringify(addon.filename)}, size: ${addon.size} },`,
	)
	.join("\n");

const content = `
// AUTOGENERATED FILE -- DO NOT EDIT DIRECTLY
// See scripts/embed-native.ts

${embeddedAddonTypedefs}

import archivePath from ${JSON.stringify(`../native/${archiveFilename}`)} with { type: "file" };

export const embeddedAddon = {
\tplatformTag: ${JSON.stringify(platformTag)},
\tversion: ${JSON.stringify(packageJson.version)},
\tarchive: {
\t\tformat: "tar.gz",
\t\tfilename: ${JSON.stringify(archiveFilename)},
\t\tfilePath: archivePath,
\t},
\tfiles: [
${files}
\t],
};
`;

await Bun.write(outputPath, stubMetadata ? stubContent : content);
