//! `veyyon_uutils_ctx`: the path and environment shim under every in-process uutils builtin.
//!
//! WHY THIS CRATE IS WORTH FUZZING DESPITE BEING SMALL. It is the layer through which every embedded
//! utility resolves a relative path and reads an environment variable, because the shell those
//! utilities run inside has its own working directory and its own exported variables, and neither is
//! the host process's. So a defect here is not one command misbehaving: it is `cat`, `grep`, `diff`
//! and everything else reading a different directory than the shell they were typed into. The
//! failure mode is silent by nature. A resolution that quietly drops the scope's working directory
//! still produces a path, and that path still names a real file, just the wrong one.
//!
//! WHAT MAKES IT FUZZABLE WITHOUT A FILESYSTEM. `resolve` is pure path arithmetic and never calls the
//! operating system, and `scope` is a thread-local install with a `Drop` guard that restores the
//! previous context. Both can be exercised entirely in memory, which is the only reason this target
//! can exist: fuzzing anything that resolved a path and then opened it would be fuzzing the disk.
//!
//! WHAT IS CHECKED.
//!
//! 1. An absolute path comes back unchanged. A shim that joined it onto the working directory anyway
//!    would produce `/work//etc/passwd`-shaped paths, and on Windows a rooted path joined onto a
//!    drive letter silently becomes a different drive.
//! 2. A relative path resolves under the scope's working directory, and the resolved path still ends
//!    with what was asked for. Together these say the shim neither dropped the base nor lost the
//!    caller's path.
//! 3. `var` answers exactly what the scope was given and nothing for a key it was not, since the
//!    utilities read the shell's exports through it rather than the process environment.
//! 4. The scope is fully torn down afterwards. This is the one that matters most: the context is
//!    thread-local and threads are reused, so a leaked scope hands the NEXT builtin the previous
//!    invocation's working directory. Nesting is checked for the same reason, because the guard
//!    restores the previous context rather than clearing it, and only a nested case can tell those
//!    two behaviours apart.
//! 5. `format_usage` indents every line after the first by exactly the width of clap's `Usage: `
//!    prefix, and adds nothing else. Misaligned help is cosmetic; losing a line is not.

#![no_main]

use std::{
	collections::HashMap,
	io,
	path::{Path, PathBuf},
	sync::{Arc, atomic::AtomicBool},
};

use arbitrary::Arbitrary;
use libfuzzer_sys::fuzz_target;
use veyyon_fuzz::PathLike;
use veyyon_uutils_ctx::{ScopeIo, cwd, format_usage, is_active, resolve, scope, var};

/// A working directory, a path to resolve against it, and an environment.
#[derive(Arbitrary, Debug)]
struct Case {
	/// Made absolute below: a relative working directory is a shell state that
	/// cannot occur, and resolving against one would test nothing real.
	base:    PathLike,
	nested:  PathLike,
	operand: PathLike,
	env:     Vec<(PathLike, PathLike)>,
	/// Fed to `format_usage`, which is line-oriented, so it wants the same
	/// path-ish alphabet only for its newlines and spaces.
	usage:   PathLike,
}

/// Discards writes. The target never asserts on output; it is here because
/// `ScopeIo` requires the streams and a real one would be I/O.
struct Sink;

impl io::Write for Sink {
	fn write(&mut self, buf: &[u8]) -> io::Result<usize> {
		Ok(buf.len())
	}

	fn flush(&mut self) -> io::Result<()> {
		Ok(())
	}
}

fn scope_io(cwd: PathBuf, env: HashMap<String, String>) -> ScopeIo {
	ScopeIo {
		stdin: Box::new(io::empty()),
		stdin_fd: None,
		stdin_is_search_input: false,
		stdout: Box::new(Sink),
		stdout_is_terminal: false,
		stderr: Box::new(Sink),
		cwd,
		env,
		cancel: Arc::new(AtomicBool::new(false)),
	}
}

/// An absolute directory built from generated bytes, since only an absolute
/// working directory is reachable in production.
fn absolute(relative: &str) -> PathBuf {
	let mut path = PathBuf::from(std::path::MAIN_SEPARATOR.to_string());
	path.push(relative.trim_start_matches(std::path::MAIN_SEPARATOR));
	path
}

fn check_resolution(base: &Path, operand: &str) {
	let resolved = resolve(operand);
	let requested = Path::new(operand);

	if requested.is_absolute() {
		assert_eq!(
			resolved, requested,
			"an absolute operand must be returned unchanged"
		);
		return;
	}

	assert!(
		resolved.starts_with(base),
		"resolved {resolved:?} escaped the scope working directory {base:?}"
	);
	assert_eq!(
		resolved,
		base.join(requested),
		"resolution is not the working directory joined with the operand"
	);
}

fuzz_target!(|case: Case| {
	assert!(
		!is_active(),
		"a scope from a previous input is still installed on this thread"
	);

	let base = absolute(&case.base.0);
	let env: HashMap<String, String> = case
		.env
		.iter()
		.map(|(key, value)| (key.0.clone(), value.0.clone()))
		.collect();

	scope(scope_io(base.clone(), env.clone()), || {
		assert!(is_active(), "scope did not install a context");
		assert_eq!(cwd(), base, "the scope reported a different working directory");

		check_resolution(&base, &case.operand.0);

		for (key, value) in &env {
			assert_eq!(
				var(key).as_ref(),
				Some(value),
				"the scope environment lost the value for {key:?}"
			);
		}
		// A key the scope was not given must not be answered from the host process
		// environment, which is the whole reason utilities read through this shim.
		let absent = format!("veyyon-fuzz-absent-{}", case.operand.0);
		if !env.contains_key(&absent) {
			assert_eq!(var(&absent), None, "the shim answered a key it was never given");
		}

		// Nested: the inner scope wins while it runs, and the outer one comes back
		// afterwards rather than the context being cleared.
		let inner = absolute(&case.nested.0);
		scope(scope_io(inner.clone(), HashMap::new()), || {
			assert_eq!(cwd(), inner, "the nested scope did not take effect");
			check_resolution(&inner, &case.operand.0);
		});
		assert_eq!(
			cwd(),
			base,
			"leaving a nested scope did not restore the outer working directory"
		);
	});

	assert!(!is_active(), "the scope outlived the call it was installed for");
	assert_eq!(
		cwd(),
		PathBuf::from("."),
		"a torn-down scope must leave the documented default working directory"
	);

	// `format_usage` is the one pure function here: it indents continuation lines
	// by seven spaces to sit under clap's `Usage: ` prefix, and does nothing else.
	let usage = case.usage.0.replace("{}", "");
	let formatted = format_usage(&usage);
	let lines: Vec<&str> = formatted.split('\n').collect();
	assert_eq!(
		lines.len(),
		usage.split('\n').count(),
		"formatting changed the line count of {usage:?}"
	);
	for (index, (formatted_line, original)) in lines.iter().zip(usage.split('\n')).enumerate() {
		if index == 0 {
			assert_eq!(*formatted_line, original, "the first line must not be indented");
		} else {
			assert_eq!(
				*formatted_line,
				format!("       {original}"),
				"line {index} is not indented to clap's usage column"
			);
		}
	}
});
